function qsnInitQsnManage(){initResetArea({selection:"#qsn_search_param_div",id:"qsn_search_param_div"});window.L.openCom("wDate",{obj:$("#create_tm_start").get(0),params:{readOnly:!0}});window.L.openCom("wDate",{obj:$("#create_tm_end").get(0),params:{readOnly:!0}});qsnSetQsnTotalCount();window.L.strVar("L.extension.pageTable.callback.initLoadList[]",qsnSetQsnTotalCount);window.L.openCom("oDialogDiv")}
function qsnSetQsnTotalCount(){$("#qsn_total_count_lab").html($('table[_pagetabledataset="admin_question_questionCtl::displayQsnList"]').attr("_pagetabletotalitems"))}function qsnResetSearchParams(){resetArea("qsn_search_param_div");qsnInitQsnManage()}function qsnSearchQsnList(){var a=qsnGetSearchCondition(),b=$('table[_pagetabledataset="admin_question_questionCtl::displayQsnList"]');window.L.extension.pageTable.classObj.params(b.get(0),a,!0)}
function qsnGetSearchCondition(){return{qsn_id:$.trim($("#qsn_id").val()),qsn_category:"1"==$("#qsn_category").val()?"":$("#qsn_category").val(),qsn_source:"0104"==$("#qsn_source").val()?"":$("#qsn_source").val(),qsn_status:$("#qsn_status").val(),qsn_level:$("#qsn_level").val(),qsn_point:$.trim($("#qsn_point").val()),qsn_type:$("#qsn_type").val(),create_user_name:$.trim($("#create_user_name").val()),create_tm_start:$("#create_tm_start").val(),create_tm_end:$("#create_tm_end").val(),tag_names:$.trim($("#tag_names").val()),
qsn_content:$.trim($("#qsn_content").val())}}
function qsnUpdateQsn(a){var b=$('table[_pagetabledataset="admin_question_questionCtl::displayQsnList"]').attr("_pagetablecurpage"),c=$('table[_pagetabledataset="admin_question_questionCtl::displayQsnList"]').attr("_pagetablepagesize"),d=$('table[_pagetabledataset="admin_question_questionCtl::displayQsnList"]').attr("_pagetableparams");$("#search_condition").val(d);$("#cur_page").val(b);$("#page_size").val(c);$("#update_qsn_id").val(a);$("form#update_qsn_form").submit();return!1}QSN_LINE_COUNT=null;
function qsnModifyQsnStatus(a,b,c){var c=c?c:"",d=0,e={qsn_status:{target_status:b,qsn_ids:{}}},f="success",g="";if("selected"==a){var h=!1;$(":checkbox[name='qsn_cb']:checked").each(function(b){d++;e.qsn_status.qsn_ids[b]=$(this).val();h=!0});h||(f="failed",g=window.L.getText("\u8bf7\u81f3\u5c11\u9009\u4e2d\u4e00\u9053\u8bd5\u9898"));c=window.L.getText("\u8fd9")+d+window.L.getText("\u9053\u8bd5\u9898")}else e.qsn_status.qsn_ids[0]=a,c="&nbsp;"+a+"&nbsp;"+window.L.getText("\u8fd9\u9053\u8bd5\u9898");
if("success"==f){a=window.L.getText("\u786e\u8ba4\u5220\u9664")+c+"\uff1f";switch(b){case "010302":a=window.L.getText("\u786e\u8ba4\u7981\u7528")+c+"\uff1f";break;case "010301":a=window.L.getText("\u786e\u8ba4\u53ef\u7528")+c+"\uff1f"}oDialogDiv(window.L.getText("\u4fee\u6539\u8bd5\u9898\u72b6\u6001"),"text:<div>"+a+"</div>","400px","auto",[2,function(a){if(a){var a=window.L._adminUrl+"/question/questionCtl.php?a=modifyQsnStatus",c="modify_info="+encodeURIComponent(L.JSON.stringify(e));$.ajax({type:"POST",
async:!1,url:a,data:c,dataType:"json",success:function(a){if("success"==a.res){a=window.L.getText("\u8bd5\u9898\u5220\u9664\u6210\u529f");switch(b){case "010302":a=window.L.getText("\u8bd5\u9898\u7981\u7528\u6210\u529f");break;case "010301":a=window.L.getText("\u8bd5\u9898\u53ef\u7528\u6210\u529f")}oDialogDivInfo(a);var c=$('table[_pagetabledataset="admin_question_questionCtl::displayQsnList"]'),a=L.extension.pageTable.classObj,c=c.get(0);a.params(c,null,!0)}else oDialogDivInfo(a.info)},error:function(){}})}}])}else oDialogDivInfo(g)}
function qsnManageALotQsn(a){var b="success",c="";0==a&&void 0==$(":checkbox[name='qsn_cb']:checked").val()&&(b="failed",c=window.L.getText("\u6700\u5c11\u9009\u4e2d\u4e00\u9053\u8bd5\u9898"));"success"==b?0==a?window.L.openCom("oDialogDiv")&&(b=window.L._adminUrl+"/question/questionCtl.php?",QSN_SUB_DIV_MARK=oDialogDiv(window.L.getText("\u4fee\u6539\u9009\u4e2d\u8bd5\u9898"),"url:post?"+b+"{'get' : {'a':'manageAlotQsn'},'post':{'is_selected':"+a+"}}","943px","190px",[1],"200px")):window.L.openCom("oDialogDiv")&&
(b=window.L._adminUrl+"/question/questionCtl.php?",QSN_SUB_DIV_MARK=oDialogDiv(window.L.getText("\u4fee\u6539\u641c\u7d22\u8bd5\u9898"),"url:post?"+b+"{'get' : {'a':'manageAlotQsn'},'post':{'is_selected':"+a+"}}","943px","190px",[1],"200px")):oDialogDivInfo(c)}
function qsnModifyALotQsn(a){var b={qsn_ids:{},modify_target:{},select_conditions:""},c=!1,d="success",e="";""!=$("#modify_qsn_category").val()&&"1"!=$("#modify_qsn_category").val()&&(c=!0,b.modify_target.qsn_category=$("#modify_qsn_category").val());""!=$("#modify_qsn_source").val()&&"0104"!=$("#modify_qsn_source").val()&&(c=!0,b.modify_target.qsn_source=$("#modify_qsn_source").val());""!=$("#modify_qsn_level").val()&&(c=!0,b.modify_target.qsn_level=$("#modify_qsn_level").val());""!=$("#modify_qsn_status").val()&&
(c=!0,b.modify_target.qsn_status=$("#modify_qsn_status").val());""!=$.trim($("#modify_qsn_point").val())&&(c=!0,b.modify_target.qsn_point=$.trim($("#modify_qsn_point").val()));""!=$.trim($("#modify_create_user_name").val())&&(c=!0,b.modify_target.create_user_name=$.trim($("#modify_create_user_name").val()));""!=$.trim($("#modify_qsn_limit_tm").val())&&(c=!0,b.modify_target.qsn_limit_tm=formatTnToHis($.trim($("#modify_qsn_limit_tm").val()),$("#modify_time_unit").val()));""!=$.trim($("#qsn_group_div > input").attr("key"))&&
(c=!0,b.modify_target.qsn_group="1");""!=$.trim($("#modify_qsn_limit_tm").val())&&!validPositive($.trim($("#modify_qsn_limit_tm").val()))?(d="failed",e=window.L.getText("\u7b54\u9898\u65f6\u9650\u5fc5\u987b\u4e3a\u4e00\u4e2a\u6709\u6548\u7684\u6570\u5b57")):""!=$.trim($("#modify_qsn_point").val())&&!validPositive($.trim($("#modify_qsn_point").val()))?(d="failed",e=window.L.getText("\u7f3a\u7701\u5206\u6570\u5fc5\u987b\u4e3a\u4e00\u4e2a\u6709\u6548\u7684\u6570\u5b57")):a&&void 0==$(":checkbox[name='qsn_cb']:checked").val()?
(d="failed",e=window.L.getText("\u6700\u5c11\u9009\u4e2d\u4e00\u9053\u8bd5\u9898")):c||(d="failed",e=window.L.getText("\u6700\u5c11\u8bbe\u5b9a\u4e00\u4e2a\u4fee\u6539\u6761\u4ef6"));"success"==d?(a?$(":checkbox[name='qsn_cb']:checked").each(function(a){b.qsn_ids[a]=$(this).val()}):(a=$('table[_pagetabledataset="admin_question_questionCtl::displayQsnList"]').get(0),b.select_conditions=a.getAttribute("_pageTableParams")),a=window.L._adminUrl+"/question/questionCtl.php?a=modifyAlotQsn",c="modify_info="+
encodeURIComponent(L.JSON.stringify(b)),$.ajax({type:"POST",async:!1,url:a,data:c,dataType:"json",success:function(a){if(a.res=="success"){qsnCloseSubQsn();oDialogDivInfo(window.L.getText("\u4fee\u6539\u6210\u529f"),null,false,false);a=$('table[_pagetabledataset="admin_question_questionCtl::displayQsnList"]');window.L.extension.pageTable.classObj.pageClickFn(a.get(0),0)()}else oDialogDivInfo(a.info)},error:function(){}})):oDialogDivInfo(e)}
function qsnManageCopyQsn(a){var b="success",c="";a&&void 0==$(":checkbox[name='qsn_cb']:checked").val()&&(b="failed",c=window.L.getText("\u6700\u5c11\u9009\u4e2d\u4e00\u9053\u8bd5\u9898"));"success"==b?window.L.openCom("oDialogDiv")&&(b=window.L._adminUrl+"/question/questionCtl.php?",QSN_SUB_DIV_MARK=oDialogDiv(window.L.getText("\u590d\u5236\u8bd5\u9898"),"url:post?"+b+"{'get' : {'a':'manageCopyQsn'},'post':{'is_select':'"+a+"'}}","715px","190px",[1],"200px")):oDialogDivInfo(c)}
function qsnModifyCopyQsn(a){var b={qsn_ids:{},modify_target:{},select_conditions:""},c="success",d="";b.modify_target.qsn_category="1"==$("#modify_qsn_category").val()?"":$("#modify_qsn_category").val();b.modify_target.qsn_source="0104"==$("#modify_qsn_source").val()?"":$("#modify_qsn_source").val();b.modify_target.qsn_level=$("#modify_qsn_level").val();b.modify_target.qsn_status=$("#modify_qsn_status").val();b.modify_target.qsn_point=$.trim($("#modify_qsn_point").val());b.modify_target.qsn_limit_tm=
""!=$.trim($("#modify_qsn_limit_tm").val())?formatTnToHis($.trim($("#modify_qsn_limit_tm").val()),$("#modify_time_unit").val()):"";""!=$.trim($("#modify_qsn_limit_tm").val())&&!validPositive($.trim($("#modify_qsn_limit_tm").val()))?(c="failed",d=window.L.getText("\u7b54\u9898\u65f6\u9650\u5fc5\u987b\u4e3a\u4e00\u4e2a\u6709\u6548\u7684\u6570\u5b57")):""!=$.trim($("#modify_qsn_point").val())&&!validPositive($.trim($("#modify_qsn_point").val()))?(c="failed",d=window.L.getText("\u7f3a\u7701\u5206\u6570\u5fc5\u987b\u4e3a\u4e00\u4e2a\u6709\u6548\u7684\u6570\u5b57")):
a&&void 0==$(":checkbox[name='qsn_cb']:checked").val()&&(c="failed",d=window.L.getText("\u6700\u5c11\u9009\u4e2d\u4e00\u9053\u8bd5\u9898"));"success"==c?(a?$(":checkbox[name='qsn_cb']:checked").each(function(a){b.qsn_ids[a]=$(this).val()}):(a=$('table[_pagetabledataset="admin_question_questionCtl::displayQsnList"]').get(0),b.select_conditions=a.getAttribute("_pageTableParams")),a=window.L._adminUrl+"/question/questionCtl.php?a=modifyCopyQsn",c="modify_info="+encodeURIComponent(L.JSON.stringify(b)),
$.ajax({type:"POST",async:!1,url:a,data:c,dataType:"json",success:function(a){if(a.res=="success"){var a=qsnGetSearchCondition(),b=$('table[_pagetabledataset="admin_question_questionCtl::displayQsnList"]');window.L.extension.pageTable.classObj.params(b.get(0),a,true);qsnCloseSubQsn();oDialogDivInfo(window.L.getText("\u590d\u5236\u6210\u529f"))}else oDialogDivInfo(a.info)},error:function(){}})):oDialogDivInfo(d)}
function qsnPreviewQsn(a){if(window.L.openCom("oDialogDiv")){var b=window.L._adminUrl+"/question/questionCtl.php?";ALERT_DIV_MARK=oDialogDiv(window.L.getText("\u9884\u89c8\u8bd5\u9898"),"iframe:"+b+"{'get':{'a':'previewQsn'}, 'post' : {'qsn_id':'"+a+"'}}","1000px","400px",[1],null,!0)}}
function qsnExportQsn(a){var b={qsn_ids:{},modify_target:{},select_conditions:""},c="success",d="";a&&void 0==$(":checkbox[name='qsn_cb']:checked").val()&&(c="failed",d=window.L.getText("\u6700\u5c11\u9009\u4e2d\u4e00\u9053\u8bd5\u9898"));"success"==c?(a?$(":checkbox[name='qsn_cb']:checked").each(function(a){b.qsn_ids[a]=$(this).val()}):(a=$('table[_pagetabledataset="admin_question_questionCtl::displayQsnList"]').get(0),b.select_conditions=a.getAttribute("_pageTableParams")),ALERT_DIV_MARK=oDialogDiv(window.L.getText("\u5bfc\u51fa\u8bd5\u9898"),
"text:<div id='qsn_export_res_div' style='width:200px;height:36px;' align='center'><img style='left:95px;top:60px;'  src='"+L._rootUrl+"/images/preload.gif'/></div>","auto","auto",[1]),a=window.L._adminUrl+"/question/questionCtl.php?a=exportQsn",c="modify_info="+encodeURIComponent(L.JSON.stringify(b)),$.ajax({type:"POST",async:!0,url:a,data:c,dataType:"json",success:function(a){a.res=="success"?$("#qsn_export_res_div").html("<a href='?a=downLoadExportQsnFile&file_key="+a.info.file_key+"&export_cont=1' target='_blank' class='btn'>"+
window.L.getText("\u5bfc\u51fa\u8bd5\u9898\u6a21\u677f")+"</a><a href='?a=downLoadExportQsnFile&file_key="+a.info.file_key+"&export_cont=2' target='_blank' class='btn'>"+window.L.getText("\u5bfc\u51fa\u7b54\u6848\u6a21\u677f")+"</a>"):oDialogDivInfo(a.info)},error:function(){$("#qsn_export_res_div").html(window.L.getText("\u5bfc\u51fa\u5931\u8d25"))}})):oDialogDivInfo(d)}
function qsnDownloadExportFile(a,b){window.open(window.L._adminUrl+"/question/questionCtl.php?a=downLoadExportQsnFile&file_key="+b+"&export_cont="+a,window.L.getText("\u4e0b\u8f7d"))};
