function qsnImportInitqsnImportManage(){initResetArea({selection:"#qsnimport_search_param_div",id:"qsnimport_search_param_div"});initResetArea({selection:"#qsnimport_param_div",id:"qsnimport_param_div"});var a=window.L.openCom("upload");a("qsn_file",function(a){oDialogDivInfo(window.L.getText("\u4e0a\u4f20\u6210\u529f"));$("#qsn_file_name").val(a)},"txt",'<font color="#0000ff" size="14" >'+window.L.getText("\u4e0a\u4f20")+"</font>",95,28,{folder:"/qsnImport/"},{auto:!0,queueID:!0,multi:!1});a("answer_file",
function(a){oDialogDivInfo(window.L.getText("\u4e0a\u4f20\u6210\u529f"));$("#answer_file_name").val(a)},"txt",'<font color="#0000ff" size="14" >'+window.L.getText("\u4e0a\u4f20")+"</font>",95,28,{folder:"/qsnImport/"},{auto:!0,queueID:!0,multi:!1})}function qsnImportResetSearchParams(){resetArea("qsnimport_search_param_div");resetArea("qsnimport_param_div");qsnImportInitqsnImportManage()}
function qsnGetImportSearchCondition(){return{qsn_category:"1"==$("#qsn_category").val()?"":$("#qsn_category").val(),qsn_source:"0104"==$("#qsn_source").val()?"":$("#qsn_source").val(),qsn_level:$("#qsn_level").val(),qsn_type:$("#qsn_type").val()}}function qsnImportSearchQsnList(){var a=qsnGetImportSearchCondition(),b=$('table[_pagetabledataset="admin_question_questionCtl::displayImportQsnList"]');window.L.extension.pageTable.classObj.params(b.get(0),a,!0)}
function showUserGroup(){getTree({targetId:"select_target_name",targetNameId:"group_name",targetValueId:"group",dataType:"group",isCheckBox:!1,showRoot:!1,allowCheckParent:!0,expandLevel:2})}
function qsnImport(){var a="success",b="";""==$("#qsn_file_name").val()?(a="failed",b=window.L.getText("\u8bf7\u4e0a\u4f20\u8bd5\u9898\u6a21\u677f")):""==$("#answer_file_name").val()?(a="failed",b=window.L.getText("\u8bf7\u4e0a\u4f20\u7b54\u6848\u6a21\u677f")):""==$("#qsnimp_category").val()||"1"==$("#qsn_source").val()?(a="failed",b=window.L.getText("\u8bf7\u9009\u62e9\u9ed8\u8ba4\u8bd5\u9898\u5206\u7c7b")):""==$("#qsnimp_source").val()||"0104"==$("#qsn_source").val()?(a="failed",b=window.L.getText("\u8bf7\u9009\u62e9\u9ed8\u8ba4\u8bd5\u9898\u6765\u6e90")):
""==$("#qsnimp_level").val()?(a="failed",b=window.L.getText("\u8bf7\u9009\u62e9\u9ed8\u8ba4\u96be\u5ea6")):""==$("#group").val()&&(a="failed",b=window.L.getText("\u8bf7\u9009\u62e9\u9ed8\u8ba4\u5206\u7ec4"));"success"==a?(oDialogDivInfo(window.L.getText("\u64cd\u4f5c\u4e2d..."),3E5),disableBtn("qsn_import_btn"),a=window.L._adminUrl+"/question/questionCtl.php?a=importQsn",b="qsn_file_name="+$("#qsn_file_name").val()+"&answer_file_name="+$("#answer_file_name").val()+"&qsn_category="+$("#qsnimp_category").val()+
"&qsn_source="+$("#qsnimp_source").val()+"&qsn_level="+$("#qsnimp_level").val()+"&groupId="+$("#group").val(),$.ajax({type:"POST",async:!0,url:a,data:b,dataType:"json",success:function(a){if(a.res=="success"){oDialogDivInfo(window.L.getText("\u5bfc\u5165\u6210\u529f"));qsnImportSearchQsnList(true)}else oDialogDivInfo(a.info);qsnImportDisplayImportResult(a);enableBtn("qsn_import_btn")},error:function(){oDialogDivInfo(window.L.getText("\u5bfc\u5165\u5931\u8d25,\u8bf7\u68c0\u67e5\u5bfc\u5165\u6587\u4ef6\u662f\u5426\u5df2\u5927\u4e8e5M\u6216\u8005\u670d\u52a1\u5668/data\u53ca\u5b50\u6587\u4ef6\u5939\u662f\u5426\u6709\u53ef\u5199\u6743\u9650"));
enableBtn("qsn_import_btn")}})):oDialogDivInfo(b)}
function qsnImportDisplayImportResult(a){var b=window.L.getText("\u5bfc\u5165\u8bd5\u9898\u603b\u6570\uff1a")+a.total_num+"<br>"+window.L.getText("\u6210\u529f\u6570\uff1a")+a.success_num+"<br>"+window.L.getText("\u9519\u8bef\u6570\uff1a")+a.error_num+"<br>"+window.L.getText("\u5931\u8d25\u6570\uff1a")+a.failed_num+"<br>";if("0"!=a.error_num||"0"!=a.failed_num)b+='<a href="?a=printImportQsnError&dir=/data/importQsnError/'+a.error_info_log+'" target="_blank" class="btn2" >'+window.L.getText("\u67e5\u770b\u9519\u8bef\u5217\u8868")+
"</a>";b+='<a href="javascript:void(0)" onclick="qsnCloseSubQsn()" class="btn2" >\u5173\u95ed</a>';QSN_SUB_DIV_MARK=oDialogDiv(window.L.getText("\u5bfc\u5165\u7ed3\u679c"),"text:"+b,"auto","auto",[1])}
function qsnAlertDeleteImportQsn(a){a='\u6ce8\uff1a\u6b64\u64cd\u4f5c\u4e0d\u53ef\u6062\u590d<br><a href="javascript:void(0)" onclick="qsnDeleteImportQsn(\''+a+'\')" class="btn2" >'+window.L.getText("\u786e\u5b9a")+'</a><a href="javascript:void(0)" onclick="qsnCloseSubQsn()" class="btn2" >'+window.L.getText("\u5173\u95ed")+"</a>";QSN_SUB_DIV_MARK=oDialogDiv(window.L.getText("\u5220\u9664\u8bd5\u9898"),"text:"+a,"400px","auto",[1])}
function qsnDeleteImportQsn(a){var b=!0,c={qsn_ids:{},del_method:"selected",del_condition:{}},d="success",e="";"selected"==a?($(":checkbox[name='qsn_cb']:checked").each(function(a){c.qsn_ids[a]=$(this).val()}),void 0==c.qsn_ids[0]&&(d="failed",e=window.L.getText("\u8bf7\u9009\u4e2d\u81f3\u5c11\u4e00\u6761\u6570\u636e"))):"search"==a?(c.del_method="search",c.del_condition=qsnGetImportSearchCondition()):(c.qsn_ids[0]=a,b=!1);var a=window.L._adminUrl+"/question/questionCtl.php?a=deleteImportQsn",f="delete_info="+
encodeURIComponent(L.JSON.stringify(c));"success"==d?$.ajax({type:"POST",async:!1,url:a,data:f,dataType:"json",success:function(a){if(a.res=="success"){oDialogDivInfo(window.L.getText("\u5220\u9664\u6210\u529f"));b&&qsnCloseSubQsn();var c=$('table[_pagetabledataset="admin_question_questionCtl::displayImportQsnList"]'),a=L.extension.pageTable.classObj,c=c.get(0);a.params(c,null,true)}else oDialogDivInfo(a.info)},error:function(){}}):oDialogDivInfo(e)}
function qsnAlertMoveImportQsn(a){a=window.L.getText("\u6ce8\uff1a\u6b64\u64cd\u4f5c\u4e0d\u53ef\u6062\u590d")+'<br><a href="javascript:void(0)" onclick="qsnMoveImportQsn(\''+a+'\')" class="btn2" >'+window.L.getText("\u786e\u5b9a")+'</a><a href="javascript:void(0)" onclick="qsnCloseSubQsn()" class="btn2" >'+window.L.getText("\u5173\u95ed")+"</a>";QSN_SUB_DIV_MARK=oDialogDiv(window.L.getText("\u5bfc\u5165\u8bd5\u9898\u81f3\u6b63\u5f0f\u5e93"),"text:"+a,"200px","auto",[1])}
function qsnMoveImportQsn(a){var b={qsn_ids:{},move_method:"selected",move_condition:{}},c="success",d="";"selected"==a?($(":checkbox[name='qsn_cb']:checked").each(function(a){b.qsn_ids[a]=$(this).val()}),void 0==b.qsn_ids[0]&&(c="failed",d=window.L.getText("\u8bf7\u9009\u4e2d\u81f3\u5c11\u4e00\u6761\u6570\u636e"))):"search"==a?(b.move_method="search",b.move_condition=qsnGetImportSearchCondition()):b.qsn_ids[0]=a;var a=window.L._adminUrl+"/question/questionCtl.php?a=moveImportQsn",e="move_info="+
encodeURIComponent(L.JSON.stringify(b));"success"==c?$.ajax({type:"POST",async:!1,url:a,data:e,dataType:"json",success:function(a){if(a.res=="success"){oDialogDivInfo(window.L.getText("\u5bfc\u5165\u6210\u529f"));qsnCloseSubQsn();a=document.getElementById("displayImportQsnList");window.L.extension.pageTable.classObj.params(a,null,true)}else oDialogDivInfo(a.info)},error:function(){}}):oDialogDivInfo(d)}
function qsnUpdateImportQsn(a){var b=$('table[_pagetabledataset="admin_question_questionCtl::displayImportQsnList"]').attr("_pagetablecurpage"),c=$('table[_pagetabledataset="admin_question_questionCtl::displayImportQsnList"]').attr("_pagetablepagesize"),d=$('table[_pagetabledataset="admin_question_questionCtl::displayImportQsnList"]').attr("_pagetableparams");$("#search_condition").val(d);$("#cur_page").val(b);$("#page_size").val(c);$("#update_qsn_id").val(a);$("#qsn_type").val();$("form#update_import_qsn_form").submit();
return!1}
function qsnAddOrUpdateImportQsn(){oDialogDivInfo(window.L.getText("\u64cd\u4f5c\u4e2d..."),3E5);disableBtn("qsn_save_btn");var a=qsnValidateQsnInfo();if("success"==a.res){var b=qsnFormatQsnInfo(),a=window.L._adminUrl+"/question/questionCtl.php?a=modifyImportQsn",b="qsn_info="+encodeURIComponent(L.JSON.stringify(b));$.ajax({type:"POST",async:!0,url:a,data:b,dataType:"json",success:function(a){"success"===a.res?oDialogDivInfo(window.L.getText("\u4fee\u6539\u6210\u529f")):oDialogDivInfo(a.info);enableBtn("qsn_save_btn")},
error:function(){oDialogDivInfo(window.L.getText("\u7f51\u7edc\u8fde\u63a5\u51fa\u9519,\u8bf7\u7a0d\u540e\u518d\u8bd5"));enableBtn("qsn_save_btn")}})}else oDialogDivInfo(a.info),enableBtn("qsn_save_btn")}function qsnModifyImportQsn(){return result}
function qsnManageALotImportQsn(a){var b="success",c="";0==a&&void 0==$(":checkbox[name='qsn_cb']:checked").val()&&(b="failed",c=window.L.getText("\u6700\u5c11\u9009\u4e2d\u4e00\u9053\u8bd5\u9898"));"success"==b?window.L.openCom("oDialogDiv")&&(b=window.L._adminUrl+"/question/questionCtl.php?",QSN_SUB_DIV_MARK=oDialogDiv(window.L.getText("\u6279\u91cf\u4fee\u6539\u8bd5\u9898"),"url:post?"+b+"{'get' : {'a':'manageAlotQsn'},'post':{'is_import':true,'is_selected':"+a+"}}","943px","190px",[1],"200px")):
oDialogDivInfo(c)}
function qsnModifyALotImportQsn(a){var b={qsn_ids:{},modify_target:{},select_conditions:""},c=!1,d="success",e="";""!=$("#modify_qsn_category").val()&&(c=!0,b.modify_target.qsn_category=$("#modify_qsn_category").val());""!=$("#modify_qsn_source").val()&&(c=!0,b.modify_target.qsn_source=$("#modify_qsn_source").val());""!=$("#modify_qsn_level").val()&&(c=!0,b.modify_target.qsn_level=$("#modify_qsn_level").val());""!=$("#modify_qsn_status").val()&&(c=!0,b.modify_target.qsn_status=$("#modify_qsn_status").val());""!=
$.trim($("#modify_qsn_point").val())&&(c=!0,b.modify_target.qsn_point=$.trim($("#modify_qsn_point").val()));""!=$.trim($("#modify_create_user_name").val())&&(c=!0,b.modify_target.create_user_name=$.trim($("#modify_create_user_name").val()));""!=$.trim($("#modify_qsn_limit_tm").val())&&(c=!0,b.modify_target.qsn_limit_tm=formatTnToHis($.trim($("#modify_qsn_limit_tm").val()),$("#modify_time_unit").val()));""!=$.trim($("#qsn_group_div > input").attr("key"))&&(c=!0,b.modify_target.qsn_group="1");""!=$.trim($("#modify_qsn_limit_tm").val())&&
!validPositive($.trim($("#modify_qsn_limit_tm").val()))?(d="failed",e=window.L.getText("\u7b54\u9898\u65f6\u9650\u5fc5\u987b\u4e3a\u4e00\u4e2a\u6709\u6548\u7684\u6570\u5b57")):""!=$.trim($("#modify_qsn_point").val())&&!validPositive($.trim($("#modify_qsn_point").val()))?(d="failed",e=window.L.getText("\u7f3a\u7701\u5206\u6570\u5fc5\u987b\u4e3a\u4e00\u4e2a\u6709\u6548\u7684\u6570\u5b57")):a&&void 0==$(":checkbox[name='qsn_cb']:checked").val()?(d="failed",e=window.L.getText("\u6700\u5c11\u9009\u4e2d\u4e00\u9053\u8bd5\u9898")):
c||(d="failed",e=window.L.getText("\u6700\u5c11\u8bbe\u5b9a\u4e00\u4e2a\u4fee\u6539\u6761\u4ef6"));"success"==d?(a?$(":checkbox[name='qsn_cb']:checked").each(function(a){b.qsn_ids[a]=$(this).val()}):(a=$('table[_pagetabledataset="admin_question_questionCtl::displayImportQsnList"]').get(0),b.select_conditions=a.getAttribute("_pageTableParams")),a=window.L._adminUrl+"/question/questionCtl.php?a=modifyAlotQsn",c="modify_info="+encodeURIComponent(L.JSON.stringify(b))+"&is_import=true",$.ajax({type:"POST",
async:!1,url:a,data:c,dataType:"json",success:function(a){if(a.res=="success"){a=$('table[_pagetabledataset="admin_question_questionCtl::displayImportQsnList"]');window.L.extension.pageTable.classObj.pageClickFn(a.get(0),0)();qsnCloseSubQsn();oDialogDivInfo(window.L.getText("\u4fee\u6539\u6210\u529f"),null,false,false)}else oDialogDivInfo(a.info)},error:function(){}})):oDialogDivInfo(e)}
function qsnPreviewImportQsn(a){if(window.L.openCom("oDialogDiv")){var b=window.L._adminUrl+"/question/questionCtl.php?";ALERT_DIV_MARK=oDialogDiv(window.L.getText("\u9884\u89c8\u8bd5\u9898"),"iframe:"+b+"{'get':{'a':'previewQsn'}, 'post' : {'qsn_id':'"+a+"','is_import':1}}","1000px","400px",[1],null,!0)}};
