var QSN_OPTION_LOADED_COUNT=0,QSN_IS_LOADED_NORMAL_CONTENT=!1,QSN_IS_LOADED_BLANK_CONTENT=!1,QSN_IS_LOADED_CLOZE_CONTENT=!1,QSN_IS_LOADED_QNA_ANSWER=!1,QSN_SUB_DIV_MARK="",DEFAULT_IS_SUB_QSN=!1;
function qsnInitEditPage(b){initResetArea({selection:"#qsn_params_div",id:"qsn_params_div",is_keep:!0});DEFAULT_IS_SUB_QSN=b=b?b:!1;window.L.openCom("oEditor")&&(new oEditor({buttonList:"bold italic underline left center right justify ol ul fontSize fontFamily fontFormat image forecolor bgcolor table subscript superscript strikethrough removeformat hr media".split(" "),maxHeight:60,CustomConfig:{AnswerSelect:{AnswerType:"textbox"},oFileManager:{quickUploadDir:{img:img_quick_upload_dir,media:media_quick_upload_dir,
attachment:attachment_quick_upload_dir},browseDir:{img:img_browse_upload_dir,media:media_browse_upload_dir,attachment:attachment_browse_upload_dir}}}})).panelInstance("qsn_guide");qsnTypeChange(b);qsnQnaInitLoadSubQsnEditer(b);var c={tableArea:"#qsn_qna_sub_answers_div",btnArea:'[name="qsn_qna_func_span"]',orderNumArea:'[name="qsn_qna_sub_num_h"]',trArea:">table",orderMark:"qsn_qna_div",showOrderNum:!0};orderInitOrder(c);c={tableArea:"#qsn_integrate_tbody",btnArea:"td:nth-child(3)",orderNumArea:"td:nth-child(2)",
orderMark:"qsn_integrate_tbody",showOrderNum:!0};orderInitOrder(c);qsnMatInitLoadSubQsnEditer(b);c={tableArea:"#qsn_mat_sub_answers_div",btnArea:'[name="qsn_mat_func_span"]',orderNumArea:'[name="qsn_mat_sub_num_h"]',trArea:">table",orderMark:"qsn_mat_div",showOrderNum:!0};orderInitOrder(c);loadFunctionBar()}
function qsnTypeChange(b){var b=b?b:!1,c=$("#qsn_type").val();"010102"===c?$("#qsn_multi_fewhalf_span").show():$("#qsn_multi_fewhalf_span").hide();switch(c){case "010101":$("#qsn_option_count").removeAttr("disabled");$("#qsn_option_count").val($("#qsn_single_count").val());$("div[name='qsn_content_div']").hide();$("#qsn_normal_content_div").show();$("#qsn_options_div").show();$("#qsn_judge_div").hide();$("#qsn_qna_div").hide();$("#qsn_cloze_div").hide();$("#qsn_blank_div").hide();$("#qsn_integrate_div").hide();
$("#qsn_blank_cond_span").hide();$("input[name='qsn_single_option']").show();$("input[name='qsn_multi_option']").hide();$("#qsn_mat_div").hide();qsnLoadNormalContentOEditor(b);qsnOptionCountChange(b);break;case "010102":$("#qsn_option_count").removeAttr("disabled");$("#qsn_option_count").val($("#qsn_multi_count").val());$("div[name='qsn_content_div']").hide();$("#qsn_normal_content_div").show();$("#qsn_options_div").show();$("#qsn_judge_div").hide();$("#qsn_qna_div").hide();$("#qsn_cloze_div").hide();
$("#qsn_blank_div").hide();$("#qsn_integrate_div").hide();$("#qsn_blank_cond_span").hide();$("input[name='qsn_single_option']").hide();$("input[name='qsn_multi_option']").show();$("#qsn_mat_div").hide();qsnLoadNormalContentOEditor(b);qsnOptionCountChange(b);break;case "010103":$("#qsn_option_count").attr("disabled","disabled");$("div[name='qsn_content_div']").hide();$("#qsn_normal_content_div").show();$("#qsn_options_div").hide();$("#qsn_qna_div").hide();$("#qsn_judge_div").show();$("#qsn_cloze_div").hide();
$("#qsn_blank_div").hide();$("#qsn_integrate_div").hide();$("#qsn_blank_cond_span").hide();$("#qsn_mat_div").hide();qsnLoadNormalContentOEditor(b);break;case "010104":$("#qsn_option_count").attr("disabled","disabled");$("div[name='qsn_content_div']").hide();$("#qsn_blank_content_div").show();$("#qsn_options_div").hide();$("#qsn_judge_div").hide();$("#qsn_qna_div").hide();$("#qsn_cloze_div").hide();$("#qsn_blank_div").show();$("#qsn_integrate_div").hide();$("#qsn_blank_cond_span").show();$("#qsn_mat_div").hide();
qsnLoadBlankContentOEditor(b);break;case "010105":$("#qsn_option_count").attr("disabled","disabled");$("div[name='qsn_content_div']").hide();$("#qsn_normal_content_div").show();$("#qsn_options_div").hide();$("#qsn_judge_div").hide();$("#qsn_qna_div").show();$("#qsn_cloze_div").hide();$("#qsn_blank_div").hide();$("#qsn_integrate_div").hide();$("#qsn_blank_cond_span").hide();$("#qsn_mat_div").hide();qsnLoadNormalContentOEditor(b);qsnQnaIsSubChange(b);break;case "010106":$("#qsn_option_count").attr("disabled",
"disabled");$("div[name='qsn_content_div']").hide();$("#qsn_normal_content_div").show();$("#qsn_options_div").hide();$("#qsn_judge_div").hide();$("#qsn_qna_div").show();$("#qsn_cloze_div").hide();$("#qsn_blank_div").hide();$("#qsn_integrate_div").hide();$("#qsn_blank_cond_span").hide();$("#qsn_mat_div").hide();qsnLoadNormalContentOEditor(b);qsnQnaIsSubChange(b);break;case "010107":$("#qsn_option_count").attr("disabled","disabled");$("div[name='qsn_content_div']").hide();$("#qsn_normal_content_div").show();
$("#qsn_options_div").hide();$("#qsn_judge_div").hide();$("#qsn_qna_div").hide();$("#qsn_cloze_div").hide();$("#qsn_blank_div").hide();$("#qsn_integrate_div").show();$("#qsn_blank_cond_span").hide();$("#qsn_mat_div").hide();qsnLoadNormalContentOEditor(b);break;case "010108":$("#qsn_option_count").attr("disabled","disabled");$("div[name='qsn_content_div']").hide();$("#qsn_cloze_content_div").show();$("#qsn_options_div").hide();$("#qsn_judge_div").hide();$("#qsn_qna_div").hide();$("#qsn_cloze_div").show();
$("#qsn_blank_div").hide();$("#qsn_integrate_div").hide();$("#qsn_blank_cond_span").hide();$("#qsn_mat_div").hide();qsnLoadClozeContentOEditor(b);break;case "010109":$("#qsn_option_count").removeAttr("disabled"),$("#qsn_option_count").val($("#qsn_single_count").val()),$("div[name='qsn_content_div']").hide(),$("#qsn_normal_content_div").show(),$("#qsn_options_div").show(),$("#qsn_judge_div").hide(),$("#qsn_qna_div").hide(),$("#qsn_cloze_div").hide(),$("#qsn_blank_div").hide(),$("#qsn_integrate_div").hide(),
$("#qsn_blank_cond_span").hide(),$("#qsn_mat_div").show(),$("input[name='qsn_single_option']").hide(),$("input[name='qsn_multi_option']").hide(),qsnLoadNormalContentOEditor(b),qsnOptionCountChange(b),qsnQnaIsSubChange(b)}is_hide="010109"==c?!0:!1;qsnOptionRemarkHide(is_hide);qsnResetDivHeight(b)}
function qsnOptionCountChange(b){b=b?b:!1;switch($("#qsn_type").val()){case "010101":$("#qsn_single_count").val($("#qsn_option_count").val());qsnLoadOptionOEditor(b);break;case "010102":$("#qsn_multi_count").val($("#qsn_option_count").val());qsnLoadOptionOEditor(b);break;case "010109":$("#qsn_single_count").val($("#qsn_option_count").val()),qsnLoadOptionOEditor(b),qsnMatReplaceSubQsn(b)}qsnResetDivHeight(b)}
function qsnLoadNormalContentOEditor(){QSN_IS_LOADED_NORMAL_CONTENT||((new oEditor({buttonList:"bold italic underline left center right justify ol ul fontSize fontFamily fontFormat image forecolor bgcolor table subscript superscript strikethrough removeformat hr media".split(" "),maxHeight:140,CustomConfig:{AnswerSelect:{AnswerType:"textbox"},oFileManager:{quickUploadDir:{img:img_quick_upload_dir,media:media_quick_upload_dir,attachment:attachment_quick_upload_dir},browseDir:{img:img_browse_upload_dir,
media:media_browse_upload_dir,attachment:attachment_browse_upload_dir}}}})).panelInstance("qsn_normal_content"),QSN_IS_LOADED_NORMAL_CONTENT=!0)}
function qsnLoadBlankContentOEditor(){QSN_IS_LOADED_BLANK_CONTENT||((new oEditor({buttonList:"bold italic underline left center right justify ol ul fontSize fontFamily fontFormat image AnswerSelect forecolor bgcolor table subscript superscript strikethrough removeformat hr media".split(" "),maxHeight:140,CustomConfig:{AnswerSelect:{AnswerType:"textbox",ExtensionFun:["qsnAddBlank"]},oFileManager:{quickUploadDir:{img:img_quick_upload_dir,media:media_quick_upload_dir,attachment:attachment_quick_upload_dir},
browseDir:{img:img_browse_upload_dir,media:media_browse_upload_dir,attachment:attachment_browse_upload_dir}}}})).panelInstance("qsn_blank_content"),QSN_IS_LOADED_BLANK_CONTENT=!0)}
function qsnLoadClozeContentOEditor(){QSN_IS_LOADED_CLOZE_CONTENT||((new oEditor({buttonList:"bold italic underline left center right justify ol ul fontSize fontFamily fontFormat image AnswerSelect forecolor bgcolor table subscript superscript strikethrough removeformat hr media".split(" "),maxHeight:140,CustomConfig:{AnswerSelect:{AnswerType:"select",ExtensionFun:["qsnAddCloze"]},oFileManager:{quickUploadDir:{img:img_quick_upload_dir,media:media_quick_upload_dir,attachment:attachment_quick_upload_dir},
browseDir:{img:img_browse_upload_dir,media:media_browse_upload_dir,attachment:attachment_browse_upload_dir}}}})).panelInstance("qsn_cloze_content"),QSN_IS_LOADED_CLOZE_CONTENT=!0)}
function qsnLoadOptionOEditor(){$("textarea[name='qsn_option_content']").each(function(b){$("#qsn_option_item_div_"+(b+1)).show();b>=QSN_OPTION_LOADED_COUNT&&b<$("#qsn_option_count").val()&&((new oEditor({buttonList:"bold italic underline fontSize image forecolor bgcolor table subscript superscript strikethrough removeformat hr media".split(" "),maxHeight:60,CustomConfig:{AnswerSelect:{AnswerType:"select"},oFileManager:{quickUploadDir:{img:img_quick_upload_dir,media:media_quick_upload_dir,attachment:attachment_quick_upload_dir},
browseDir:{img:img_browse_upload_dir,media:media_browse_upload_dir,attachment:attachment_browse_upload_dir}}}})).panelInstance(this.id),QSN_OPTION_LOADED_COUNT=b+1);b>=$("#qsn_option_count").val()&&$("#qsn_option_item_div_"+(b+1)).hide()})}
function qsnAddBlank(b){b=b.ne.CustomConfig.AnswerSelect.AnswerNum;b=DEFAULT_IS_SUB_QSN?'<li id="qsn_blank_answer_div_'+b+'"  style=" height:30px; line-height:30px; padding-right:10px; margin:0px auto;" > <table class="editor_exam" border="0" cellSpacing="0" cellPadding="0" width="100%"><colgroup><col span="1"><col span="1"></colgroup><tbody><tr><td style="background: rgb(100, 180, 255); border: 1px solid rgb(1, 193, 255); width: 30px; height: 25px; text-align: center; color: rgb(255, 255, 255); line-height: 25px; margin-right: 5px; float: left;" class="item_left">'+b+
'</td><td style="background: rgb(189, 234, 248); margin: 0px auto; border: 1px solid rgb(1, 193, 255); width: 80px; height: 25px; line-height: 25px; float: left;" class="item_right"><div class="editor_item"><input style="background: rgb(189, 234, 248); height: 23px; line-height: 23px; width:80px; margin-top: 2px;"  type="text" qsn_item_id="'+b+'" name="qsn_blank_answer" id="qsn_blank_answer_'+b+'" value=""/></div></td><td style="line-height: 25px;"><div class="toolbar_bottom"><a href="javascript:void(0)" class="icon_link" onclick="qsnCleanBlank('+
b+')"><span class="icon_del"></span>'+window.L.getText("\u5220\u9664")+"</a></div></td> </tr></tbody></table></li>":'<li id="qsn_blank_answer_div_'+b+'"  style=" height:30px; line-height:30px; padding-right:10px; margin:0px auto;" > <table class="editor_exam" border="0" cellSpacing="0" cellPadding="0" width="100%"><colgroup><col span="1"><col span="1"></colgroup><tbody><tr><td style="background: rgb(100, 180, 255); border: 1px solid rgb(1, 193, 255); width: 30px; height: 25px; text-align: center; color: rgb(255, 255, 255); line-height: 25px; margin-right: 5px; float: left;" class="item_left">'+
b+'</td><td style="background: rgb(189, 234, 248); margin: 0px auto; border: 1px solid rgb(1, 193, 255); width: 130px; height: 25px; line-height: 25px; float: left;" class="item_right"><div class="editor_item"><input style="background: rgb(189, 234, 248); height: 23px; line-height: 23px; width:130px; margin-top: 2px;"  type="text" qsn_item_id="'+b+'" name="qsn_blank_answer" id="qsn_blank_answer_'+b+'" value=""/></div></td><td style="line-height: 25px;"><div class="toolbar_bottom"><a href="javascript:void(0)" class="icon_link" onclick="qsnCleanBlank('+
b+')"><span class="icon_del"></span>'+window.L.getText("\u5220\u9664")+"</a></div></td> </tr></tbody></table></li>";$("#qsn_blank_div").append(b);qsnResetDivHeight(DEFAULT_IS_SUB_QSN)}function qsnCleanBlank(b){var c=RegExp("\\[textbox\\]"+b+"\\[\\/textbox\\]","ig");$("#qsn_blank_content").html($("#qsn_blank_content").html().replace(c,""));$("#qsn_blank_content_Editer img[Num="+b+"]").remove();$("#qsn_blank_answer_div_"+b).remove();qsnResetDivHeight(DEFAULT_IS_SUB_QSN)}
function qsnAddCloze(b){var b=b.ne.CustomConfig.AnswerSelect.AnswerNum,c='<tr id="qsn_cloze_answer_tr_'+b+'" name="qsn_cloze_answer_tr" qsn_item_id="'+b+'"><td class="align_center"><input name="qsn_cloze_answer_checkbox" type="checkbox" class="checkbox" id="qsn_cloze_answer_checkbox'+b+'" value="'+b+'" /></td><td class="align_center">'+b+'</td><td><select id="qsn_cloze_option_count_'+b+'" onchange="qsnClozeOptionCountChange('+b+')">'+qsn_option_cloze_count+'</select></td><td><div id="qsn_cloze_option_items_div_'+
b+'"></div></td><td class="action">&nbsp;<div class="action_toolbar"><div class="inner"><div class="right"></div><div class="inner_box"><div class="action_link"><a class="iframe" href="javascript:void(0)" onclick="qsnCleanCloze('+b+')"  title="'+window.L.getText("\u5220\u9664")+'">'+window.L.getText("\u5220\u9664")+"</a></div></div></div></div></td></tr>";$("#qsn_cloze_tb tbody").append(c);qsnClozeOptionCountChange(b);loadFunctionBar();qsnResetDivHeight(DEFAULT_IS_SUB_QSN)}
function qsnClozeOptionCountChange(b){var c="",d=$("#qsn_cloze_option_count_"+b).val();for(option_item_num=0;option_item_num<QSN_MAX_OPTION_COUNT;option_item_num++)"1"!=$("#qsn_cloze_option_item_div_"+b+"_"+option_item_num).attr("value")&&option_item_num<d&&(c='<div style="float:left" id="qsn_cloze_option_item_div_'+b+"_"+option_item_num+'" value="1"><input type="radio" name="qsn_cloze_value_'+b+'" value="'+QSN_OPTION_TAG[option_item_num]+'"/>'+QSN_OPTION_TAG[option_item_num]+'<input type="text" name="qsn_cloze_option_item_'+
b+'" id="qsn_cloze_option_item_'+b+"_"+option_item_num+'" value="" /></div>',$("#qsn_cloze_option_items_div_"+b).append(c)),"1"==$("#qsn_cloze_option_item_div_"+b+"_"+option_item_num).attr("value")&&option_item_num>=d&&$("#qsn_cloze_option_item_div_"+b+"_"+option_item_num).remove()}
function qsnCleanCloze(b){var c=RegExp("\\[select\\]"+b+"\\[\\/select\\]","ig");$("#qsn_cloze_content").html($("#qsn_cloze_content").html().replace(c,""));$("#qsn_cloze_content_Editer img[Num="+b+"]").remove();$("#qsn_cloze_answer_tr_"+b).remove();qsnResetDivHeight(DEFAULT_IS_SUB_QSN)}
function qsnQnaInitLoadSubQsnEditer(){$("textarea[name='qsn_qna_content']").each(function(){(new oEditor({buttonList:"bold italic underline left center right justify ol ul fontSize fontFamily fontFormat image forecolor bgcolor table subscript superscript strikethrough removeformat hr media".split(" "),maxHeight:60,CustomConfig:{AnswerSelect:{AnswerType:"textbox"},oFileManager:{quickUploadDir:{img:img_quick_upload_dir,media:media_quick_upload_dir,attachment:attachment_quick_upload_dir},browseDir:{img:img_browse_upload_dir,
media:media_browse_upload_dir,attachment:attachment_browse_upload_dir}}}})).panelInstance(this.id)});$("textarea[name='qsn_qna_answer']").each(function(){(new oEditor({buttonList:"bold italic underline left center right justify ol ul fontSize fontFamily fontFormat image forecolor bgcolor table subscript superscript strikethrough removeformat hr media".split(" "),maxHeight:60,CustomConfig:{AnswerSelect:{AnswerType:"textbox"},oFileManager:{quickUploadDir:{img:img_quick_upload_dir,media:media_quick_upload_dir,
attachment:attachment_quick_upload_dir},browseDir:{img:img_browse_upload_dir,media:media_browse_upload_dir,attachment:attachment_browse_upload_dir}}}})).panelInstance(this.id)})}
function qsnQnaIsSubChange(b){var b=b?b:!1,c=$("input[name='has_sub_qsn']:checked").val();0==c?($("#qsn_qna_answer_div").show(),$("#qsn_qna_sub_answers_div").hide(),$("#qsn_qna_sub_answers_lab").hide()):($("#qsn_qna_answer_div").hide(),$("#qsn_qna_sub_answers_div").show(),$("#qsn_qna_sub_answers_lab").show());0==c&&!QSN_IS_LOADED_QNA_ANSWER&&((new oEditor({buttonList:"bold italic underline left center right justify ol ul fontSize fontFamily fontFormat image forecolor bgcolor table subscript superscript strikethrough removeformat hr media".split(" "),
maxHeight:60,CustomConfig:{AnswerSelect:{AnswerType:"textbox"},oFileManager:{quickUploadDir:{img:img_quick_upload_dir,media:media_quick_upload_dir,attachment:attachment_quick_upload_dir},browseDir:{img:img_browse_upload_dir,media:media_browse_upload_dir,attachment:attachment_browse_upload_dir}}}})).panelInstance("qsn_qna_answer"),QSN_IS_LOADED_QNA_ANSWER=!0);qsnResetDivHeight(b)}
function qsnQnaAddSubQsn(b){var b=b?b:!1,c=1,d=$("table[name='qsn_qna_sub_answer_div']").size();0<d&&(c=Number($($("table[name='qsn_qna_sub_answer_div']").get(d-1)).attr("value"))+1);$("#qsn_qna_sub_answers_div").append('<table class="item_q_con" width="100%" border="0" cellspacing="0" cellpadding="0" id="qsn_qna_sub_answer_div_'+c+'" name="qsn_qna_sub_answer_div" value="'+c+'"><colgroup><col style="" /><col style="" /><col style="" /></colgroup><tr><td class="padding_right_15px"><div class="toolbar_top"><div class="left ~none">\u95ee\u9898\uff1a&nbsp;&nbsp;\u5206\u6570\uff1a<input type="text" value="0" id="qsn_qna_point_'+
c+'" class="input_num ~auto_width" />&nbsp;&nbsp;<span name="qsn_qna_func_span"></span></div></div><table class="editor_exam" width="100%" border="0" cellspacing="0" cellpadding="0"><colgroup><col span="" style="" /><col span="" style="" /></colgroup><tr><td class="item_left"><h1 class="" name="qsn_qna_sub_num_h">'+c+'</h1></td><td class="item_right"><div class="editor_item"><div class="editor_item_inner"><textarea id="qsn_qna_content_'+c+'" style="width:'+(b?"360":"500")+'px;height:63px;"></textarea></div></div></td></tr></table></td><td><div class="toolbar_top"><div class="left ~none">\u7b54\u6848\uff1a&nbsp;&nbsp;</div></div><table class="editor_exam" width="100%" border="0" cellspacing="0" cellpadding="0"><colgroup><col span="" style="" /><col span="" style="" /></colgroup><tr><td class="item_left_a"><h1 class=""></h1></td><td class="item_right"><div class="editor_item"><div class="editor_item_inner"><textarea id="qsn_qna_answer_'+
c+'" style="width:'+(b?"290":"400")+'px;height:63px;"></textarea></div></div></td></tr></table><div class="toolbar_bottom"></div></td></tr></table>');(new oEditor({buttonList:"bold italic underline left center right justify ol ul fontSize fontFamily fontFormat image forecolor bgcolor table subscript superscript strikethrough removeformat hr media".split(" "),maxHeight:60,maxWidth:500,CustomConfig:{AnswerSelect:{AnswerType:"textbox"},oFileManager:{quickUploadDir:{img:img_quick_upload_dir,media:media_quick_upload_dir,
attachment:attachment_quick_upload_dir},browseDir:{img:img_browse_upload_dir,media:media_browse_upload_dir,attachment:attachment_browse_upload_dir}}}})).panelInstance("qsn_qna_content_"+c);(new oEditor({buttonList:"bold italic underline left center right justify ol ul fontSize fontFamily fontFormat image forecolor bgcolor table subscript superscript strikethrough removeformat hr media".split(" "),maxHeight:60,maxWidth:500,CustomConfig:{AnswerSelect:{AnswerType:"textbox"},oFileManager:{quickUploadDir:{img:img_quick_upload_dir,
media:media_quick_upload_dir,attachment:attachment_quick_upload_dir},browseDir:{img:img_browse_upload_dir,media:media_browse_upload_dir,attachment:attachment_browse_upload_dir}}}})).panelInstance("qsn_qna_answer_"+c);orderResetBtnArea("qsn_qna_div");qsnResetDivHeight(b)}function qsnCleanQnaSubQsn(b){$("#qsn_qna_sub_answer_div_"+b).remove()}
function qsnAddOrUpdateSubQsn(b){b=b?b:"";if(""==b){var c=window.L._adminUrl+"/question/questionCtl.php?";QSN_SUB_DIV_MARK=oDialogDiv(window.L.getText("\u6dfb\u52a0\u5b50\u8bd5\u9898"),"iframe:"+c+'{"get":{"a":"addQsnSub"},"post":{"is_alert_qsn":"'+$("#is_alert_qsn").val()+'"}}',"800px","600px",[1],10,!0)}else c=window.L._adminUrl+"/question/questionCtl.php?",QSN_SUB_DIV_MARK=oDialogDiv(window.L.getText("\u4fee\u6539\u5b50\u8bd5\u9898"),"iframe:"+c+'{"get":{"a":"updateQsnSub"}, "post" : {"qsn_info":"'+
$("#qsn_sub_info_"+b).val()+'","qsn_sub_num":"'+b+'","is_alert_qsn":"'+$("#is_alert_qsn").val()+'"}}',"800px","600px",[1],10,!0)}
function qsnModifySubQsn(){var b=qsnValidateQsnInfo(!0);"success"==b.res?(b=qsnFormatQsnInfo(!0),"true"==$("#is_alert_qsn").val()?(window.parent.frames["oDialogDiv_iframe_"+window.parent.QSN_SUB_DIV_MARK].qsnAddOrUpdateSubQsnInfo(b,$("#qsn_sub_qsn_num").val()),window.parent.qsnCloseSubQsn(!0)):(window.parent.qsnAddOrUpdateSubQsnInfo(b,$("#qsn_sub_qsn_num").val()),window.parent.qsnCloseSubQsn())):oDialogDivInfo(b.info)}
function qsnAddOrUpdateSubQsnInfo(b,c){var d=!1;if(""==c){var d=!0,c=1,f=$("#qsn_integrate_div tbody > tr").size();0<f&&(c=Number($($("#qsn_integrate_div tbody > tr").get(f-1)).attr("id"))+1)}f=encodeURIComponent(L.JSON.stringify(b));f='<tr id="'+c+'"><td class="align_center"><input type="hidden" name="qsn_sub_info" id="qsn_sub_info_'+c+'" value="'+f+'"/><input name="qsn_sub_num" type="checkbox" class="checkbox" value="'+c+'"/></td><td class="align_center">'+c+"</td><td></td><td>"+decodeURIComponent(b.qsn_content_edit)+
"</td><td>"+QSN_TYPE[b.qsn_type]+"</td><td>"+b.qsn_point+'</td><td class="action">&nbsp;<div class="action_toolbar" ><div class="inner"><div class="right"></div><div class="inner_box"><div class="action_link"><a class="iframe" href="javascript:void(0)" onclick="qsnAddOrUpdateSubQsn('+c+')" title="\u7f16\u8f91">\u7f16\u8f91</a></div></div></div></div></td></tr>';d?$("#qsn_integrate_div tbody").append(f):$("#qsn_integrate_div tbody #"+c).replaceWith(f);orderResetBtnArea("qsn_integrate_tbody");qsnResetDivHeight();
loadFunctionBar()}
function qsnMatInitLoadSubQsnEditer(){$("textarea[name='qsn_mat_content']").each(function(){(new oEditor({buttonList:"bold italic underline left center right justify ol ul fontSize fontFamily fontFormat image forecolor bgcolor table subscript superscript strikethrough removeformat hr media".split(" "),maxHeight:60,CustomConfig:{AnswerSelect:{AnswerType:"textbox"},oFileManager:{quickUploadDir:{img:img_quick_upload_dir,media:media_quick_upload_dir,attachment:attachment_quick_upload_dir},browseDir:{img:img_browse_upload_dir,
media:media_browse_upload_dir,attachment:attachment_browse_upload_dir}}}})).panelInstance(this.id)})}function qsnMatReplaceSubQsn(){var b=$("#qsn_option_count").val();$("#qsn_mat_sub_answers_div table[name='qsn_mat_sub_answer_div']").each(function(c){$("ul#qsn_mat_item_"+(c+1)+" li[name=qsn_option_item_div_"+(c+1)+"]").each(function(c){c<b?$(this).show():$(this).hide()})})}
function qsnMatAddSubQsn(b){var b=b?b:!1,c=$("#qsn_option_count").val(),d=1,f=$("table[name='qsn_mat_sub_answer_div']").size();0<f&&(d=Number($($("table[name='qsn_mat_sub_answer_div']").get(f-1)).attr("value"))+1);var e='<ul id="qsn_mat_item_'+d+'">';$("ul.item_q li").find("input[type=radio]").each(function(b){e=b<c?e+('<li name="qsn_option_item_div_'+d+'" style="float:left;margin-left:10px;">'):e+('<li name="qsn_option_item_div_'+d+'" style="float:left;margin-left:10px;display:none;">');e+='<input type="radio" value="'+
$(this).val()+'" name="qsn_single_option_'+d+'" qsn_item_id="'+(b+1)+'" />';e+=$(this).val();e+='<textarea style="display:none;" name="qsn_mat_option_content" id="qsn_mat_option_content_'+(b+1)+'">'+$("#qsn_option_content_"+(b+1)).val()+"</textarea>";e+="</li>"});e+="</ul>";$("#qsn_mat_sub_answers_div").append('<table class="item_q_con" width="100%" border="0" cellspacing="0" cellpadding="0" id="qsn_mat_sub_answer_div_'+d+'" name="qsn_mat_sub_answer_div" value="'+d+'"><colgroup><col style="" /><col style="" /><col style="" /></colgroup><tr><td class="padding_right_15px"><div class="toolbar_top"><div class="left ~none">\u95ee\u9898\uff1a&nbsp;&nbsp;\u5206\u6570\uff1a<input type="text" value="0" id="qsn_mat_point_'+
d+'" class="input_num ~auto_width" />&nbsp;&nbsp;<span name="qsn_mat_func_span"></span></div></div><table class="editor_exam" width="100%" border="0" cellspacing="0" cellpadding="0"><colgroup><col span="" style="" /><col span="" style="" /></colgroup><tr><td class="item_left"><h1 class="" name="qsn_mat_sub_num_h">'+d+'</h1></td><td class="item_right"><div class="editor_item"><div class="editor_item_inner"><textarea id="qsn_mat_content_'+d+'" style="width:'+(b?"360":"500")+'px;height:63px;"></textarea></div></div></td></tr></table></td><td width="40%"><div class="toolbar_top"><div class="left ~none">\u7b54\u6848\uff1a&nbsp;&nbsp;</div></div><table class="editor_exam" width="100%" border="0" cellspacing="0" cellpadding="0"><colgroup><col span="" style="" /><col span="" style="" /></colgroup><tr><td class=""><h1 class=""></h1></td><td>'+
e+"</td></tr></table>");(new oEditor({buttonList:"bold italic underline left center right justify ol ul fontSize fontFamily fontFormat image forecolor bgcolor table subscript superscript strikethrough removeformat hr media".split(" "),maxHeight:60,maxWidth:500,CustomConfig:{AnswerSelect:{AnswerType:"textbox"},oFileManager:{quickUploadDir:{img:img_quick_upload_dir,media:media_quick_upload_dir,attachment:attachment_quick_upload_dir},browseDir:{img:img_browse_upload_dir,media:media_browse_upload_dir,
attachment:attachment_browse_upload_dir}}}})).panelInstance("qsn_mat_content_"+d);orderResetBtnArea("qsn_mat_div");qsnResetDivHeight(b)}function qsnCleanMatSubQsn(b){$("#qsn_mat_sub_answer_div_"+b).remove()}
function qsnFormatQsnInfo(b){var b=b?b:!1,c={qsn_id:$.trim($("#qsn_id").val()),qsn_sub_id:$.trim($("#qsn_sub_id").val()),qsn_point:$.trim($("#qsn_point").val()),qsn_type:$("#qsn_type").val(),qsn_source:"",qsn_category:"",qsn_status:"",qsn_level:"",qsn_limit_tm:"00:00:00",qsn_content:"",qsn_content_edit:"",qsn_answer:{},qsn_option:{},qsn_option_count:$.trim($("#qsn_option_count").val()),qsn_sub_position:0,sub_questions:{},qsn_guide:encodeURIComponent($("#qsn_guide").html()),qsn_fewHalf:$("#fewHalf").prop("checked")?
"1":"0"};b||(c.qsn_source=$("#qsn_source").val(),c.qsn_category=$("#qsn_category").val(),c.qsn_status=$("#qsn_status").val(),c.qsn_level=$("#qsn_level").val(),c.qsn_limit_tm=formatTnToHis($("#qsn_limit_tm").val(),$("#time_unit").val()));switch(c.qsn_type){case "010101":c.qsn_content=encodeURIComponent($("#qsn_normal_content").html());c.qsn_content_edit=encodeURIComponent($("#qsn_normal_content_Editer").html());c.qsn_answer[0]={qsn_answer:$("input[name='qsn_single_option']:checked").val(),qsn_item_id:$("input[name='qsn_single_option']:checked").attr("qsn_item_id")};
for(i=1;i<=c.qsn_option_count;i++)c.qsn_option[i+"_0"]={qsn_item_id:i,qsn_item_sub_id:0,qsn_item_tag:QSN_OPTION_TAG[i-1],qsn_type:$("#qsn_type").val(),option_content:encodeURIComponent($("#qsn_option_content_"+i).html()),option_content_edit:encodeURIComponent($("#qsn_option_content_"+i+"_Editer").html())};break;case "010102":c.qsn_content=encodeURIComponent($("#qsn_normal_content").html());c.qsn_content_edit=encodeURIComponent($("#qsn_normal_content_Editer").html());$("input[name='qsn_multi_option']:checked").each(function(b){c.qsn_answer[b]=
{qsn_answer:$(this).val(),qsn_item_id:$(this).attr("qsn_item_id")}});for(i=1;i<=c.qsn_option_count;i++)c.qsn_option[i+"_0"]={qsn_item_id:i,qsn_item_sub_id:0,qsn_item_tag:QSN_OPTION_TAG[i-1],qsn_type:$("#qsn_type").val(),option_content:encodeURIComponent($("#qsn_option_content_"+i).html()),option_content_edit:encodeURIComponent($("#qsn_option_content_"+i+"_Editer").html())};break;case "010103":c.qsn_content=encodeURIComponent($("#qsn_normal_content").html());c.qsn_content_edit=encodeURIComponent($("#qsn_normal_content_Editer").html());
c.qsn_answer[0]={qsn_answer:$("input[name='qsn_judge_option']:checked").val(),qsn_item_id:1};break;case "010104":c.qsn_option_count="checked"==$("#qsn_blank_order_flg").attr("checked")&&"checked"==$("#qsn_blank_upper_flg").attr("checked")?"99":"checked"==$("#qsn_blank_order_flg").attr("checked")?"98":"checked"==$("#qsn_blank_upper_flg").attr("checked")?"97":"0";c.qsn_content=encodeURIComponent($("#qsn_blank_content").html());c.qsn_content_edit=encodeURIComponent($("#qsn_blank_content_Editer").html());
$("input[name='qsn_blank_answer']").each(function(b){c.qsn_answer[b]={qsn_answer:encodeURIComponent($(this).val()),qsn_item_id:$(this).attr("qsn_item_id")}});break;case "010105":case "010106":var d="";c.qsn_content=encodeURIComponent($("#qsn_normal_content").html());c.qsn_content_edit=encodeURIComponent($("#qsn_normal_content_Editer").html());"0"==$("input[name='has_sub_qsn']:checked").val()?c.qsn_answer[0]={qsn_answer:encodeURIComponent($("#qsn_qna_answer").html()),qsn_item_id:1}:(c.qsn_point=0,
$("table[name='qsn_qna_sub_answer_div']").each(function(b){d=$(this).attr("value");c.sub_questions[b]={qsn_id:$.trim($("#qsn_qna_id_"+d).val()),qsn_sub_id:$.trim($("#qsn_qna_sub_id_"+d).val()),qsn_point:$.trim($("#qsn_qna_point_"+d).val()),qsn_type:$("#qsn_type").val(),qsn_limit_tm:"00:00:00",qsn_content:encodeURIComponent($("#qsn_qna_content_"+d).html()),qsn_content_edit:encodeURIComponent($("#qsn_qna_content_"+d+"_Editer").html()),qsn_answer:{"0":{qsn_answer:encodeURIComponent($("#qsn_qna_answer_"+
d).html()),qsn_item_id:1}},qsn_option:{},qsn_option_count:$.trim($("#qsn_option_count").val()),qsn_sub_position:b+1,sub_questions:{},qsn_guide:""};c.qsn_point=c.qsn_point+parseInt($("#qsn_qna_point_"+d).val())}));break;case "010107":c.qsn_content=encodeURIComponent($("#qsn_normal_content").html());c.qsn_content_edit=encodeURIComponent($("#qsn_normal_content_Editer").html());c.qsn_point=0;$("input[name='qsn_sub_info']").each(function(b){var d=L.JSON.parse(decodeURIComponent($(this).val()));c.qsn_point=
c.qsn_point+parseInt(d.qsn_point);d.qsn_sub_position=b+1;c.sub_questions[b]=d});break;case "010108":d="";c.qsn_content=encodeURIComponent($("#qsn_cloze_content").html());c.qsn_content_edit=encodeURIComponent($("#qsn_cloze_content_Editer").html());var f=0;$("tr[name='qsn_cloze_answer_tr']").each(function(b){d=$(this).attr("qsn_item_id");c.qsn_answer[b]={qsn_answer:$("input[name='qsn_cloze_value_"+d+"']:checked").val(),qsn_item_id:d};for(a=1;a<=$("#qsn_cloze_option_count_"+d).val();a++){c.qsn_option[f]=
{qsn_item_id:d,qsn_item_sub_id:a,qsn_item_tag:QSN_OPTION_TAG[a-1],qsn_type:$("#qsn_type").val(),option_content:encodeURIComponent($("#qsn_cloze_option_item_"+d+"_"+(a-1)).val()),option_content_edit:encodeURIComponent($("#qsn_cloze_option_item_"+d+"_"+(a-1)).val())};f++}});break;case "010109":d="";c.qsn_content=encodeURIComponent($("#qsn_normal_content").html());c.qsn_content_edit=encodeURIComponent($("#qsn_normal_content_Editer").html());var e={};for(i=1;i<=c.qsn_option_count;i++)c.qsn_option[i+"_0"]=
{qsn_item_id:i,qsn_item_sub_id:0,qsn_item_tag:QSN_OPTION_TAG[i-1],qsn_type:$("#qsn_type").val(),option_content:encodeURIComponent($("#qsn_option_content_"+i).html()),option_content_edit:encodeURIComponent($("#qsn_option_content_"+i+"_Editer").html())},e[i+"_0"]={qsn_item_id:i,qsn_item_sub_id:0,qsn_item_tag:QSN_OPTION_TAG[i-1],qsn_type:"010101",option_content:encodeURIComponent($("#qsn_mat_option_content_"+i).html()),option_content_edit:encodeURIComponent($("#qsn_mat_option_content_"+i).html())};c.qsn_point=
0;$("table[name='qsn_mat_sub_answer_div']").each(function(b){d=$(this).attr("value");c.sub_questions[b]={qsn_id:$.trim($("#qsn_mat_id_"+d).val()),qsn_sub_id:$.trim($("#qsn_mat_sub_id_"+d).val()),qsn_point:$.trim($("#qsn_mat_point_"+d).val()),qsn_type:"010101",qsn_limit_tm:"00:00:00",qsn_content:encodeURIComponent($("#qsn_mat_content_"+d).html()),qsn_content_edit:encodeURIComponent($("#qsn_mat_content_"+d+"_Editer").html()),qsn_answer:{"0":{qsn_answer:$("input[name='qsn_single_option_"+d+"']:checked").val(),
qsn_item_id:$("input[name='qsn_single_option_"+d+"']:checked").attr("qsn_item_id")}},qsn_option:e,qsn_option_count:$.trim($("#qsn_option_count").val()),qsn_sub_position:b+1,sub_questions:{},qsn_guide:""};c.qsn_point=c.qsn_point+parseInt($("#qsn_mat_point_"+d).val())})}return c}
function qsnAddOrUpdateQsn(b){var c=b?b:!1;oDialogDivInfo(window.L.getText("\u64cd\u4f5c\u4e2d..."),3E5);disableBtn("qsn_save_btn");b=qsnValidateQsnInfo();if("success"==b.res){var d=qsnFormatQsnInfo(),b=window.L._adminUrl+"/question/questionCtl.php?a=modifyQsn",d="qsn_info="+encodeURIComponent(L.JSON.stringify(d));$.ajax({type:"POST",async:!0,url:b,data:d,dataType:"json",success:function(b){if("success"==b.res){var d={};$("input[name='qsn_tags']").each(function(b){d[b]=$(this).val()});tagAddTagObj({objId:b.info.qsn_id,
tagIds:d,addOrReplace:"replace"});""!=$("#qsn_id").val()?oDialogDivInfo(window.L.getText("\u4fee\u6539\u8bd5\u9898\u6210\u529f")):(oDialogDivInfo(window.L.getText("\u6dfb\u52a0\u8bd5\u9898\u6210\u529f")),qsnResetAreaParams())}else oDialogDivInfo(b.info);c&&qsnAlertReturnResult(b);enableBtn("qsn_save_btn")},error:function(){oDialogDivInfo(window.L.getText("\u7f51\u7edc\u8fde\u63a5\u51fa\u9519,\u8bf7\u7a0d\u540e\u518d\u8bd5"));enableBtn("qsn_save_btn")}})}else oDialogDivInfo(b.info),enableBtn("qsn_save_btn")}
function qsnResetAreaParams(){resetArea("qsn_params_div");QSN_OPTION_LOADED_COUNT=0;QSN_IS_LOADED_QNA_ANSWER=QSN_IS_LOADED_CLOZE_CONTENT=QSN_IS_LOADED_BLANK_CONTENT=QSN_IS_LOADED_NORMAL_CONTENT=!1;qsnInitEditPage()}function qsnModifyQsn(){}
function qsnValidateQsnInfo(b){var c={res:"success",info:""},b=b?b:!1,d=$("#qsn_type").val();if($.trim($("#qsn_category_name").text())==window.L.getText("\u8bf7\u9009\u62e9\u8bd5\u9898\u5206\u7c7b"))return c.res="failed",c.info=window.L.getText("\u8bf7\u9009\u62e9\u8bd5\u9898\u5206\u7c7b"),c;if(!validPositive($.trim($("#qsn_point").val())))return c.res="failed",c.info=window.L.getText("\u8bd5\u9898\u5206\u6570\u4e3a\u4e00\u4e2a\u975e\u8d1f\u6570"),c;if(!validPositive($.trim($("#qsn_limit_tm").val()))&&
!b)return c.res="failed",c.info=window.L.getText("\u7b54\u9898\u65f6\u9650\u4e3a\u4e00\u4e2a\u975e\u8d1f\u6570"),c;switch(d){case "010101":void 0==$("input[name='qsn_single_option']:checked").val()&&(c.res="failed",c.info=window.L.getText("\u8bf7\u9009\u62e9\u4e00\u4e2a\u7b54\u6848"));break;case "010102":void 0==$("input[name='qsn_multi_option']:checked").val()&&(c.res="failed",c.info=window.L.getText("\u8bf7\u9009\u62e9\u4e00\u4e2a\u7b54\u6848"));break;case "010103":void 0==$("input[name='qsn_judge_option']:checked").val()&&
(c.res="failed",c.info=window.L.getText("\u8bf7\u9009\u62e9\u4e00\u4e2a\u7b54\u6848"));break;case "010104":var f=0;$("input[name='qsn_blank_answer']").each(function(){f++;if(""==$.trim($(this).val()))return c.res="failed",c.info=window.L.getText("\u586b\u7a7a\u7b54\u6848\u4e0d\u80fd\u4e3a\u7a7a"),!1});0==f&&(c.res="failed",c.info=window.L.getText("\u8bf7\u6dfb\u52a0\u4e00\u9053\u8bd5\u9898"));break;case "010105":case "010106":if("1"==$("input[name='has_sub_qsn']:checked").val()&&void 0==$("table[name='qsn_qna_sub_answer_div']").attr("value")){c.res=
"failed";c.info=window.L.getText("\u8bf7\u6dfb\u52a0\u5b50\u8bd5\u9898");break}$("table[name='qsn_qna_sub_answer_div']").each(function(){e=$(this).attr("value");if(!validPositive($("#qsn_qna_point_"+e).val()))return c.res="failed",c.info=window.L.getText("\u8bd5\u9898\u5206\u6570\u4e3a\u975e\u8d1f\u6570"),!1});break;case "010107":if(void 0==$("input[name='qsn_sub_info']").val()){c.res="failed";c.info=window.L.getText("\u8bf7\u6dfb\u52a0\u5b50\u8bd5\u9898");break}break;case "010108":var e="";$("tr[name='qsn_cloze_answer_tr']").each(function(){e=
$(this).attr("qsn_item_id");if(void 0==$("input[name='qsn_cloze_value_"+e+"']:checked").val())return c.res="failed",c.info=window.L.getText("\u5b8c\u578b\u586b\u7a7a\u7b54\u6848\u4e0d\u80fd\u4e3a\u7a7a"),!1});""===e&&(c.res="failed",c.info=window.L.getText("\u8bf7\u6dfb\u52a0\u4e00\u9053\u8bd5\u9898"));break;case "010109":if(void 0==$("table[name='qsn_mat_sub_answer_div']").attr("value")){c.res="failed";c.info=window.L.getText("\u8bf7\u6dfb\u52a0\u5b50\u8bd5\u9898");break}$("table[name='qsn_mat_sub_answer_div']").each(function(){e=
$(this).attr("value");if(!validPositive($("#qsn_mat_point_"+e).val()))return c.res="failed",c.info=window.L.getText("\u8bd5\u9898\u5206\u6570\u4e3a\u975e\u8d1f\u6570"),!1})}return c}function qsnCloseSubQsn(b){b&&b?oDialogDiv.dialogClose(window.frames["oDialogDiv_iframe_"+QSN_SUB_DIV_MARK].QSN_SUB_DIV_MARK):oDialogDiv.dialogClose(QSN_SUB_DIV_MARK)}
function qsnAlertAddQsn(b){b=L.JSON.stringify($.extend({},{qsn_type:"010101",insert_success:"functionName"},b));if(window.L.openCom("oDialogDiv")){var c=window.L._adminUrl+"/question/questionCtl.php?";QSN_SUB_DIV_MARK=oDialogDiv(window.L.getText("\u6dfb\u52a0\u8bd5\u9898"),"iframe:"+c+"{'get':{'a':'alertAddQsn'}, 'post' : {'alert_option':'"+b+"'}}","1100px","600px",[1],10,!0)}}
function qsnAlertQsnList(b){var b=$.extend({},{qsn_type:"010101",click_yes:"functionName",exclude_ids:null,include_ids:null},b),c={qsn_type:b.qsn_type,exclude_ids:b.exclude_ids,include_ids:b.include_ids},b=L.JSON.stringify(b);if(window.L.openCom("oDialogDiv")){var d=window.L._adminUrl+"/question/questionCtl.php?";QSN_SUB_DIV_MARK=oDialogDiv(window.L.getText("\u9009\u62e9\u8bd5\u9898"),"iframe:"+d+"{'get':{'a':'alertQsnList'}, 'post' : {'alert_option':'"+b+"','_pageTableParams':'"+L.JSON.stringify(c)+
"'}}","1100px","600px",[1],10,!0)}}
function qsnAlertSearchQsnList(){var b={qsn_id:$.trim($("#qsn_id").val()),qsn_category:$("#qsn_category").val(),qsn_source:$("#qsn_source").val(),qsn_status:$("#qsn_status").val(),qsn_level:$("#qsn_level").val(),qsn_point:$.trim($("#qsn_point").val()),qsn_type:$("#qsn_type").val(),create_user_name:$.trim($("#create_user_name").val()),create_tm_start:$("#create_tm_start").val(),create_tm_end:$("#create_tm_end").val(),exclude_ids:L.JSON.parse(decodeURIComponent($("#exclude_ids").val())),tag_names:$("#tag_names").val(),
qsn_content:escape($.trim($("#qsn_content").val()))},c=$('table[_pagetabledataset="admin_question_questionCtl::displayAlertQsnList"]');window.L.extension.pageTable.classObj.params(c.get(0),b,!0)}function qsnCategoryTreeShow(b,c,d,f){getTree({targetNameId:b,targetValueId:c,dataType:"qsn_category",showRoot:d?d:!1,treeMark:f?f:""})}function qsnSourceTreeShow(b,c,d,f){getTree({targetNameId:b,targetValueId:c,dataType:"qsn_source",showRoot:d?d:!1,treeMark:f?f:""})}
function qsnResetDivHeight(b){b=b?b:!1;"true"==$("#is_alert_qsn").val()?b?window.parent.oDialogDiv.skinLayout(window.parent.frames["oDialogDiv_iframe_"+window.parent.QSN_SUB_DIV_MARK].QSN_SUB_DIV_MARK,"800px","600px"):window.parent.oDialogDiv.skinLayout(window.parent.QSN_SUB_DIV_MARK,"1100px","600px"):b&&window.parent.oDialogDiv.skinLayout(window.parent.QSN_SUB_DIV_MARK,"800px","600px")}
function formatQsnLimitTm(b,c){var d=$("#"+b).val();switch(c){case "m":$("#"+b).val(Math.round(60*d));break;case "h":$("#"+b).val(Math.round(100*(d/60))/100)}}function qsnDisplayTag(){tagDisplayTag({tagType:"1",callbackFn:"qsnAddTag",targetId:"qsn_add_tag_a"})}
function qsnAddTag(b,c){void 0==$("#qsn_tag_"+b).val()&&$("#qsn_tag_td").append('<span class="icon_link" id="qsn_tag_span_'+b+'"><input type="hidden" name="qsn_tags" id="qsn_tag_'+b+'" value="'+b+'"><a href="javascript:void(0)" >'+c+'</a><a class="icon_del" title="\u5220\u9664" href="javascript:void(0)" onclick="qsnDelTag(\''+b+"')\"></a></span>")}function qsnDelTag(b){$("#qsn_tag_span_"+b).remove()}function qsnDelAllTag(){$("#qsn_tag_td").html("")}
function qsnOptionRemarkHide(b){b?$("#qsn_options_div .title span:last").hide():$("#qsn_options_div .title span:last").show()};
