(function(l){var p,q,r,o={event:{CHECK:"ztree_check"},id:{CHECK:"_check"},checkbox:{STYLE:"checkbox",DEFAULT:"chk",DISABLED:"disable",FALSE:"false",TRUE:"true",FULL:"full",PART:"part",FOCUS:"focus"},radio:{STYLE:"radio",TYPE_ALL:"all",TYPE_LEVEL:"level"}},u={check:{enable:!1,autoCheckTrigger:!1,chkStyle:o.checkbox.STYLE,nocheckInherit:!1,radioType:o.radio.TYPE_LEVEL,chkboxType:{Y:"ps",N:"ps"}},data:{key:{checked:"checked"}},callback:{beforeCheck:null,onCheck:null}};p=function(c,a){if(!0===a.chkDisabled)return!1;
var b=g.getSetting(c.data.treeId),d=b.data.key.checked;if(!1==n.apply(b.callback.beforeCheck,[b.treeId,a],!0))return!0;a[d]=!a[d];e.checkNodeRelation(b,a);d=l("#"+a.tId+i.id.CHECK);e.setChkClass(b,d,a);e.repairParentChkClassWithSelf(b,a);b.treeObj.trigger(i.event.CHECK,[b.treeId,a]);return!0};q=function(c,a){if(!0===a.chkDisabled)return!1;var b=g.getSetting(c.data.treeId),d=l("#"+a.tId+i.id.CHECK);a.check_Focus=!0;e.setChkClass(b,d,a);return!0};r=function(c,a){if(!0===a.chkDisabled)return!1;var b=
g.getSetting(c.data.treeId),d=l("#"+a.tId+i.id.CHECK);a.check_Focus=!1;e.setChkClass(b,d,a);return!0};l.extend(!0,l.fn.zTree.consts,o);l.extend(!0,l.fn.zTree._z,{tools:{},view:{checkNodeRelation:function(c,a){var b,d,f,j=c.data.key.children,k=c.data.key.checked;b=i.radio;if(c.check.chkStyle==b.STYLE){var h=g.getRadioCheckedList(c);if(a[k])if(c.check.radioType==b.TYPE_ALL){for(d=h.length-1;d>=0;d--){b=h[d];b[k]=false;h.splice(d,1);e.setChkClass(c,l("#"+b.tId+i.id.CHECK),b);b.parentTId!=a.parentTId&&
e.repairParentChkClassWithSelf(c,b)}h.push(a)}else{h=a.parentTId?a.getParentNode():g.getRoot(c);d=0;for(f=h[j].length;d<f;d++){b=h[j][d];b[k]&&b!=a&&(b[k]=false,e.setChkClass(c,l("#"+b.tId+i.id.CHECK),b))}}else if(c.check.radioType==b.TYPE_ALL){d=0;for(f=h.length;d<f;d++)if(a==h[d]){h.splice(d,1);break}}}else{a[k]&&(!a[j]||a[j].length==0||c.check.chkboxType.Y.indexOf("s")>-1)&&e.setSonNodeCheckBox(c,a,true);!a[k]&&(!a[j]||a[j].length==0||c.check.chkboxType.N.indexOf("s")>-1)&&e.setSonNodeCheckBox(c,
a,false);a[k]&&c.check.chkboxType.Y.indexOf("p")>-1&&e.setParentNodeCheckBox(c,a,true);!a[k]&&c.check.chkboxType.N.indexOf("p")>-1&&e.setParentNodeCheckBox(c,a,false)}},makeChkClass:function(c,a){var b=c.data.key.checked,d=i.checkbox,f=i.radio,j="",j=a.chkDisabled===true?d.DISABLED:a.halfCheck?d.PART:c.check.chkStyle==f.STYLE?a.check_Child_State<1?d.FULL:d.PART:a[b]?a.check_Child_State===2||a.check_Child_State===-1?d.FULL:d.PART:a.check_Child_State<1?d.FULL:d.PART,b=c.check.chkStyle+"_"+(a[b]?d.TRUE:
d.FALSE)+"_"+j,b=a.check_Focus&&a.chkDisabled!==true?b+"_"+d.FOCUS:b;return"button "+d.DEFAULT+" "+b},repairAllChk:function(c,a){if(c.check.enable&&c.check.chkStyle===i.checkbox.STYLE)for(var b=c.data.key.checked,d=c.data.key.children,f=g.getRoot(c),j=0,k=f[d].length;j<k;j++){var h=f[d][j];h.nocheck!==true&&(h[b]=a);e.setSonNodeCheckBox(c,h,a)}},repairChkClass:function(c,a){if(a){g.makeChkFlag(c,a);var b=l("#"+a.tId+i.id.CHECK);e.setChkClass(c,b,a)}},repairParentChkClass:function(c,a){if(a&&a.parentTId){var b=
a.getParentNode();e.repairChkClass(c,b);e.repairParentChkClass(c,b)}},repairParentChkClassWithSelf:function(c,a){if(a){var b=c.data.key.children;a[b]&&a[b].length>0?e.repairParentChkClass(c,a[b][0]):e.repairParentChkClass(c,a)}},repairSonChkDisabled:function(c,a,b){if(a){var d=c.data.key.children;if(a.chkDisabled!=b){a.chkDisabled=b;a.nocheck!==true&&e.repairChkClass(c,a)}if(a[d])for(var f=0,j=a[d].length;f<j;f++)e.repairSonChkDisabled(c,a[d][f],b)}},repairParentChkDisabled:function(c,a,b){if(a){if(a.chkDisabled!=
b){a.chkDisabled=b;a.nocheck!==true&&e.repairChkClass(c,a)}e.repairParentChkDisabled(c,a.getParentNode(),b)}},setChkClass:function(c,a,b){a&&(b.nocheck===true?a.hide():a.show(),a.removeClass(),a.addClass(e.makeChkClass(c,b)))},setParentNodeCheckBox:function(c,a,b,d){var f=c.data.key.children,j=c.data.key.checked,k=l("#"+a.tId+i.id.CHECK);d||(d=a);g.makeChkFlag(c,a);a.nocheck!==true&&a.chkDisabled!==true&&(a[j]=b,e.setChkClass(c,k,a),c.check.autoCheckTrigger&&a!=d&&a.nocheck!==true&&c.treeObj.trigger(i.event.CHECK,
[c.treeId,a]));if(a.parentTId){k=true;if(!b)for(var f=a.getParentNode()[f],h=0,m=f.length;h<m;h++)if(f[h].nocheck!==true&&f[h][j]||f[h].nocheck===true&&f[h].check_Child_State>0){k=false;break}k&&e.setParentNodeCheckBox(c,a.getParentNode(),b,d)}},setSonNodeCheckBox:function(c,a,b,d){if(a){var f=c.data.key.children,j=c.data.key.checked,k=l("#"+a.tId+i.id.CHECK);d||(d=a);var h=false;if(a[f])for(var m=0,n=a[f].length;m<n&&a.chkDisabled!==true;m++){var o=a[f][m];e.setSonNodeCheckBox(c,o,b,d);o.chkDisabled===
true&&(h=true)}if(a!=g.getRoot(c)&&a.chkDisabled!==true){h&&a.nocheck!==true&&g.makeChkFlag(c,a);if(a.nocheck!==true){if(a[j]=b,!h)a.check_Child_State=a[f]&&a[f].length>0?b?2:0:-1}else a.check_Child_State=-1;e.setChkClass(c,k,a);c.check.autoCheckTrigger&&a!=d&&a.nocheck!==true&&c.treeObj.trigger(i.event.CHECK,[c.treeId,a])}}}},event:{},data:{getRadioCheckedList:function(c){for(var a=g.getRoot(c).radioCheckedList,b=0,d=a.length;b<d;b++)g.getNodeCache(c,a[b].tId)||(a.splice(b,1),b--,d--);return a},
getCheckStatus:function(c,a){if(!c.check.enable||a.nocheck)return null;var b=c.data.key.checked;return{checked:a[b],half:a.halfCheck?a.halfCheck:c.check.chkStyle==i.radio.STYLE?a.check_Child_State===2:a[b]?a.check_Child_State>-1&&a.check_Child_State<2:a.check_Child_State>0}},getTreeCheckedNodes:function(c,a,b,d){if(!a)return[];for(var f=c.data.key.children,j=c.data.key.checked,d=!d?[]:d,e=0,h=a.length;e<h;e++){a[e].nocheck!==true&&a[e][j]==b&&d.push(a[e]);g.getTreeCheckedNodes(c,a[e][f],b,d)}return d},
getTreeChangeCheckedNodes:function(c,a,b){if(!a)return[];for(var d=c.data.key.children,f=c.data.key.checked,b=!b?[]:b,e=0,k=a.length;e<k;e++){a[e].nocheck!==true&&a[e][f]!=a[e].checkedOld&&b.push(a[e]);g.getTreeChangeCheckedNodes(c,a[e][d],b)}return b},makeChkFlag:function(c,a){if(a){var b=c.data.key.children,d=c.data.key.checked,f=-1;if(a[b])for(var e=false,g=0,h=a[b].length;g<h;g++){var m=a[b][g],l=-1;if(c.check.chkStyle==i.radio.STYLE)if(l=m.nocheck===true?m.check_Child_State:m.halfCheck===true?
2:m.nocheck!==true&&m[d]?2:m.check_Child_State>0?2:0,l==2){f=2;break}else l==0&&(f=0);else if(c.check.chkStyle==i.checkbox.STYLE){l=m.nocheck===true?m.check_Child_State:m.halfCheck===true?1:m.nocheck!==true&&m[d]?m.check_Child_State===-1||m.check_Child_State===2?2:1:m.check_Child_State>0?1:0;if(l===1){f=1;break}else if(l===2&&e&&l!==f){f=1;break}else if(f===2&&l>-1&&l<2){f=1;break}else l>-1&&(f=l);e||(e=m.nocheck!==true)}}a.check_Child_State=f}}}});var o=l.fn.zTree,n=o._z.tools,i=o.consts,e=o._z.view,
g=o._z.data;g.exSetting(u);g.addInitBind(function(c){var a=c.treeObj,b=i.event;a.unbind(b.CHECK);a.bind(b.CHECK,function(a,b,e){n.apply(c.callback.onCheck,[a,b,e])})});g.addInitCache(function(){});g.addInitNode(function(c,a,b,d,e,j){b&&(a=c.data.key.checked,"string"==typeof b[a]&&(b[a]=n.eqs(b[a],"true")),b[a]=!!b[a],b.checkedOld=b[a],b.nocheck=!!b.nocheck||c.check.nocheckInherit&&d&&!!d.nocheck,b.chkDisabled=!!b.chkDisabled||d&&!!d.chkDisabled,"string"==typeof b.halfCheck&&(b.halfCheck=n.eqs(b.halfCheck,
"true")),b.halfCheck=!!b.halfCheck,b.check_Child_State=-1,b.check_Focus=!1,b.getCheckStatus=function(){return g.getCheckStatus(c,b)},j&&g.makeChkFlag(c,d))});g.addInitProxy(function(c){var a=c.target,b=g.getSetting(c.data.treeId),d="",e=null,j="",k=null;n.eqs(c.type,"mouseover")?b.check.enable&&(n.eqs(a.tagName,"span")&&null!==a.getAttribute("treeNode"+i.id.CHECK))&&(d=a.parentNode.id,j="mouseoverCheck"):n.eqs(c.type,"mouseout")?b.check.enable&&(n.eqs(a.tagName,"span")&&null!==a.getAttribute("treeNode"+
i.id.CHECK))&&(d=a.parentNode.id,j="mouseoutCheck"):n.eqs(c.type,"click")&&(b.check.enable&&n.eqs(a.tagName,"span")&&null!==a.getAttribute("treeNode"+i.id.CHECK))&&(d=a.parentNode.id,j="checkNode");if(0<d.length)switch(e=g.getNodeCache(b,d),j){case "checkNode":k=p;break;case "mouseoverCheck":k=q;break;case "mouseoutCheck":k=r}return{stop:!1,node:e,nodeEventType:j,nodeEventCallback:k,treeEventType:"",treeEventCallback:null}});g.addInitRoot(function(c){g.getRoot(c).radioCheckedList=[]});g.addBeforeA(function(c,
a,b){var d=c.data.key.checked;c.check.enable&&(g.makeChkFlag(c,a),c.check.chkStyle==i.radio.STYLE&&c.check.radioType==i.radio.TYPE_ALL&&a[d]&&g.getRoot(c).radioCheckedList.push(a),b.push("<span ID='",a.tId,i.id.CHECK,"' class='",e.makeChkClass(c,a),"' treeNode",i.id.CHECK,!0===a.nocheck?" style='display:none;'":"","></span>"))});g.addZTreeTools(function(c,a){a.checkNode=function(a,b,g,k){var h=this.setting.data.key.checked;if(!0!==a.chkDisabled&&(!0!==b&&!1!==b&&(b=!a[h]),k=!!k,(a[h]!==b||g)&&!(k&&
!1==n.apply(this.setting.callback.beforeCheck,[this.setting.treeId,a],!0))&&n.uCanDo(this.setting)&&this.setting.check.enable&&!0!==a.nocheck))a[h]=b,b=l("#"+a.tId+i.id.CHECK),(g||this.setting.check.chkStyle===i.radio.STYLE)&&e.checkNodeRelation(this.setting,a),e.setChkClass(this.setting,b,a),e.repairParentChkClassWithSelf(this.setting,a),k&&c.treeObj.trigger(i.event.CHECK,[c.treeId,a])};a.checkAllNodes=function(a){e.repairAllChk(this.setting,!!a)};a.getCheckedNodes=function(a){var b=this.setting.data.key.children;
return g.getTreeCheckedNodes(this.setting,g.getRoot(c)[b],!1!==a)};a.getChangeCheckedNodes=function(){var a=this.setting.data.key.children;return g.getTreeChangeCheckedNodes(this.setting,g.getRoot(c)[a])};a.setChkDisabled=function(a,b){b=!!b;e.repairSonChkDisabled(this.setting,a,b);b||e.repairParentChkDisabled(this.setting,a,b)};var b=a.updateNode;a.updateNode=function(c,f){b&&b.apply(a,arguments);if(c&&this.setting.check.enable&&l("#"+c.tId).get(0)&&n.uCanDo(this.setting)){var g=l("#"+c.tId+i.id.CHECK);
(!0==f||this.setting.check.chkStyle===i.radio.STYLE)&&e.checkNodeRelation(this.setting,c);e.setChkClass(this.setting,g,c);e.repairParentChkClassWithSelf(this.setting,c)}}});var s=e.createNodes;e.createNodes=function(c,a,b,d){s&&s.apply(e,arguments);b&&e.repairParentChkClassWithSelf(c,d)};var t=e.removeNode;e.removeNode=function(c,a){var b=a.getParentNode();t&&t.apply(e,arguments);a&&b&&(e.repairChkClass(c,b),e.repairParentChkClass(c,b))}})(jQuery);
