"function"!==typeof window.L.strVar("L.extension.pageTable.init")&&window.L.strVar("L.extension.pageTable.callback.afterLoadList[]",window.L.strVar("L.extension.pageTable.callback.initLoadList[]",function(g){if(""!==g.getElementsByTagName("thead")[0].innerHTML){for(var b=g.getElementsByTagName("thead")[0].getElementsByTagName("font"),a=0,c=b.length;a<c;++a)null!==b[a].getAttribute("_pageTableSort")&&-1===b[a].className.indexOf("sortDefault")&&(b[a].className="sortDefault");g=g.getElementsByTagName("tbody")[0].childNodes;
b=a=0;for(c=g.length;a<c;++a)"TR"===g[a].tagName&&(g[a].className=++b%2?"odd_bg":"even_bg")}}));
(function(){var g={init:function(b){for(var a=document.getElementsByTagName("table"),c,d,e=0,k=a.length;e<k;++e)if("string"===typeof a[e].getAttribute("_pageTableDataset")&&null==a[e]._pageTableSortStatusList){c=a[e];c._pageTableConfig={};if(null===(d=c.getAttribute("_pageTableSort")))c._pageTableSortStatusList={};else{c._pageTableSortStatusList=(new Function("return "+d))();for(var i=c.getElementsByTagName("thead")[0].getElementsByTagName("font"),f=0,h=i.length;f<h;++f)if("thTitle"===i[f].getAttribute("name")&&
null!==(d=i[f].getAttribute("_pageTableSort"))){d=i[f]._pageTableSortList=(new Function("return "+d))();if(""===i[f].parentNode.getAttribute("_bottomTh")){var j=c._pageTableSortStatusList[d[0]].objList;j[j.length]=i[f]}window.L.onEvent.addEvent(i[f],"click",g.thTitleClickSortFn(c,i[f]))}}d=g.getChildNodesTag(c,"tfoot").getElementsByTagName("div");f=0;for(h=d.length;f<h;++f)if("page_nav"===d[f].id){f=d[f].getElementsByTagName("*");h=0;for(i=f.length;h<i;++h)if(1===f[h].nodeType)switch(f[h].id){case "page_first":window.L.onEvent.addEvent(f[h],
"click",g.pageClickFn(c,!0));break;case "page_last":0>c.getAttribute("_pageTableTotalItems")?f[h].style.display="none":(f[h].style.display="",window.L.onEvent.addEvent(f[h],"click",g.pageClickFn(c,!1)));break;case "page_prev":window.L.onEvent.addEvent(f[h],"click",g.pageClickFn(c,-1));break;case "page_next":window.L.onEvent.addEvent(f[h],"click",g.pageClickFn(c,1));break;case "page_submit":window.L.onEvent.addEvent(f[h],"click",g.pageClickFn(c,null,f[h]));break;case "toPage":d=parseInt(c.getAttribute("_pageTableCurPage"))+
1;f[h].value=d<=c.getAttribute("_pageTableTotalPages")||0>c.getAttribute("_pageTableTotalItems")?d:1;window.L.onEvent.addEvent(f[h],"keypress",g.toPageKeypressFn(c,f[h]));window.L.onEvent.addEvent(f[h],"mouseover",function(){this.focus();this.select()});c._pageTableConfig.toPageObj=f[h];break;case "pageSize":f[h].value=c.getAttribute("_pageTablePageSize");window.L.onEvent.addEvent(f[h],"keypress",g.toPageKeypressFn(c,f[h]));window.L.onEvent.addEvent(f[h],"mouseover",function(){this.focus();this.select()});
break;case "page_num":f[h].innerHTML=c.getAttribute("_pageTableCurPage")+" / "+c.getAttribute("_pageTableTotalPages");c._pageTableConfig.pageNumObj=f[h];break;case "totaLitems":f[h].innerHTML=c.getAttribute("_pagetabletotalitems")}break}g.initCustomNav(a[e]);!0!==b&&g.callbackLoadList(c,"init")}},load:function(b,a){if(!1===g.callbackLoadList(b,"before"))return!1;var c=b.getAttribute("_pageTableParams"),d=b.getAttribute("_pageTableStarterPrint");if(""===d||null===d)d=1;null!==c&&(c="&_pageTableParams="+
encodeURIComponent(unescape(c)).replace(/%20/g,"+"));if("object"!==typeof a||null==a)a={};g.loadLock(b,!0);window.L.AJAX({url:window.L._rootUrl+"/include/Of/Com/CommonPackage.php?a=pageTable",data:"_pageTableDataset="+b.getAttribute("_pageTableDataset")+"&_pageTableTotalItems="+b.getAttribute("_pageTableTotalItems")+"&_pageTablePageSize="+b.getAttribute("_pageTablePageSize")+"&_pageTableCurPage="+b.getAttribute("_pageTableCurPage")+"&_pageTableColspan="+b.getAttribute("_pageTableColspan")+"&_pageTableStarterPrint="+
d+(null===c?"":c)+(null!=b._pageTableConfig.sortStr&&""!==b._pageTableConfig.sortStr?"&_pageTableSort="+b._pageTableConfig.sortStr:""),context:this,pageTableObj:b,starterPrint:d,success:function(b,c){if(!c.pageTableObj.parentNode)return!1;if(1==c.starterPrint)c.pageTableObj._pageTableConfig.pageNumObj&&(c.pageTableObj._pageTableConfig.pageNumObj.innerHTML=c.pageTableObj.getAttribute("_pageTableCurPage")+" / "+c.pageTableObj.getAttribute("_pageTableTotalPages")),this.html(c.pageTableObj.getElementsByTagName("tbody")[0],
b),g.loadLock(c.pageTableObj,!1);else{var d=c.pageTableObj._pageTableSortStatusList,f=this.html(c.pageTableObj,b);this.init(!a.callbackInit);var h=[],j;for(j in f._pageTableSortStatusList)null!=d[j]&&null!=d[j].status&&(f._pageTableSortStatusList[j].status=d[j].status,h[h.length]="`"+j+"` "+d[j].status,this.sortStyle(f._pageTableSortStatusList[j]));f._pageTableConfig.sortStr=h.join(",");c.pageTableObj=f;try{f._pageTableConfig.toPageObj.focus()}catch(l){}}"string"===typeof a._pageTableStarterPrint&&
(c.pageTableObj.setAttribute("_pageTableStarterPrint",a._pageTableStarterPrint),c.pageTableObj.setAttribute("_pagetablestarterprint",a._pageTableStarterPrint));a.callbackInit||g.callbackLoadList(c.pageTableObj,"after")}})},html:function(b,a){var c=document.createElement("div");if("string"===typeof a){if("TBODY"===b.tagName)c.innerHTML="<table><tbody>"+a+"</tbody></table>",a=c.getElementsByTagName("tbody")[0].childNodes;else{c.innerHTML=a;var d=c.getElementsByTagName("table")[0];b.parentNode.replaceChild(d,
b);b=d;c.innerHTML=a;a=c.getElementsByTagName("table")[0].childNodes}for(;b.firstChild;)b.removeChild(b.firstChild);for(var d=0,e=a.length;d<e;++d)1===a[0].nodeType?this.html(b,a[0]):b.appendChild(a[0]);return b}if("SCRIPT"===a.tagName)(window.execScript||function(a){window.eval.call(window,a)})(a.text||a.textContent||a.innerHTML||"");else{for(var g=a.childNodes,e=g.length,d=0;d<e;++d)c.appendChild(g[0]);b.appendChild(a);g=c.childNodes;e=g.length;for(d=0;d<e;++d)1===g[0].nodeType?this.html(a,g[0]):
a.appendChild(g[0])}},initCustomNav:function(b){var a=0,c;if(null==b)arguments.callee.resize();else{c=g.getChildNodesTag(b,"tfoot").getElementsByTagName("td")[0].childNodes;for(var d=0,e=c.length;d<e;++d)if("page_nav"===c[d].className&&(a=c[d].offsetWidth),"custom_nav"===c[d].className){for(var k=c[d].parentNode.clientWidth-a-10,i=c[d].getElementsByTagName("div")[0].scrollWidth,e=c[d].childNodes,f=0,h=e.length;f<h;++f)if("LABEL"===e[f].tagName){e=e[f];break}0>=k&&(k=1);i<=k?(e.style.display="none",
c[d].style.width=i+"px",c[d].onmouseover=null,c[d].onmouseout=null):(e.style.display="inline",c[d].style.width=k+"px",c[d].onmouseover=function(){this.style.width=i+"px";this.style.backgroundColor="#FFFFFF"},c[d].onmouseout=function(){this.style.width=k+"px";this.style.backgroundColor="transparent"});a||(a=c[d].currentStyle?[c[d].parentNode.currentStyle,c[d].currentStyle]:[document.defaultView.getComputedStyle(c[d].parentNode,null),document.defaultView.getComputedStyle(c[d],null)],a[0]=parseInt("auto"!=
a[0].marginTop&&a[0].marginTop||0)+parseInt("auto"!=a[0].borderTop&&a[0].borderTop||0)+parseInt("auto"!=a[0].paddingTop&&a[0].paddingTop||0)+parseInt("auto"!=a[0].marginButtom&&a[0].marginButtom||0)+parseInt("auto"!=a[0].borderButtom&&a[0].borderButtom||0)+parseInt("auto"!=a[0].paddingButtom&&a[0].paddingButtom||0),a[1]=parseInt("auto"!=a[1].marginTop&&a[1].marginTop||0)+parseInt("auto"!=a[1].borderTop&&a[1].borderTop||0)+parseInt("auto"!=a[1].paddingTop&&a[1].paddingTop||0)+parseInt("auto"!=a[1].marginButtom&&
a[1].marginButtom||0)+parseInt("auto"!=a[1].borderButtom&&a[1].borderButtom||0)+parseInt("auto"!=a[1].paddingButtom&&a[1].paddingButtom||0),c[d].parentNode.parentNode.style.height=c[d].offsetHeight+a[0]+a[1]+"px");break}}},callbackLoadList:function(b,a){var c;if(c=window.L.strVar("L.extension.pageTable.callback."+a+"LoadList[]")){for(var d={},e=0,g=c.length;e<g;++e)if("function"===typeof c[e])if("undefined"===typeof d[c[e].toString()]){window.L.extension.pageTable.nowCallback={pageTableObj:b,pageTableClass:this,
index:e,type:a};if(!1===c[e](b,this,e,a)){delete window.L.extension.pageTable.nowCallback;return}c[e]&&(d[c[e].toString()]="")}else delete c[e];delete window.L.extension.pageTable.nowCallback}},eachTbody:function(b,a,c,d,e){var g=[],i=b.getElementsByTagName("tbody")[0].childNodes;"function"!==typeof d&&(d=function(){});null==a&&(a="*");null==c&&(c="*");if("object"!==typeof e||null==e)e=window.L.onEvent.getEventTarget(b);for(var f=0,h=0,j=i.length;f<j;++f)if("TR"===i[f].tagName){if("*"===a||a==h)for(var b=
i[f].childNodes,l=0,m=0,n=b.length;l<n;++l)if("TD"===b[l].tagName){if("*"===c||c==m)d.call(e,g[g.length]={y:h,x:m,tdObj:b[l]});++m}++h}return g},params:function(b,a,c){if("undefined"===typeof a)return b=unescape(b.getAttribute("_pageTableParams")),"[]"===b?{}:window.L.JSON.parse(b);null!==a&&(b.setAttribute("_pageTableParams",escape(window.L.JSON.stringify(a))),b.setAttribute("_pagetableparams",escape(window.L.JSON.stringify(a))));!0===c&&(a=b.getAttribute("_pageTableStarterPrint"),b.setAttribute("_pageTableStarterPrint",
0),b.setAttribute("_pageTableCurPage",1),b.setAttribute("_pagetablestarterprint",0),b.setAttribute("_pagetablecurpage",1),this.load(b,{_pageTableStarterPrint:a,callbackInit:!0}))},getChildNodesTag:function(b,a,c){for(var b=b.childNodes,d=[],e=0,g=b.length;e<g;++e)b[e].tagName===a.toUpperCase()&&(d[d.length]=b[e]);return"boolean"===typeof c?d:d[c||0]},sortStyle:function(b){for(var a=0,c=b.objList.length;a<c;++a)b.objList[a].className="DESC"===b.status?"sortDefault sortDesc":"ASC"===b.status?"sortDefault sortAsc":
"sortDefault"},loadLock:function(b,a){b._pageTableConfig.loadLockObj&&!0!==a&&(b._pageTableConfig.loadLockObj.parentNode.removeChild(b._pageTableConfig.loadLockObj),delete b._pageTableConfig.loadLockObj);if(!b._pageTableConfig.loadLockObj&&!0===a||!1!==a&&!0!==a){var c=b.getElementsByTagName("thead")[0],d=document.createElement("tr"),e=document.createElement("td");d.className="pageTableLoadLock";d.appendChild(e);e.colSpan=b.getAttribute("_pageTableColspan");e.innerHTML='<div class="pageTableLoadLock"></div><font style="position:absolute;"><img src="'+
window.L._rootUrl+'/images/components/pageTable/loadLock.gif" align="middle" style="margin-right:5px; vertical-align:middle;" />'+("string"===typeof a?a:"")+"</font>";e=e.childNodes;e[0].style.height=b.clientHeight+"px";e[0].style.width=b.clientWidth+"px";e[1].style.top=(b.clientHeight-e[1].offsetHeight>>1)+"px";e[1].style.left=(b.clientWidth-e[1].offsetWidth>>1)+"px";c.insertBefore(d,c.firstChild);b._pageTableConfig.loadLockObj=d}},thTitleClickSortFn:function(b,a){var c=this;return function(){var d,
e=[],g;for(g in b._pageTableSortStatusList){var i=!0;d=b._pageTableSortStatusList[g];for(var f=0,h=a._pageTableSortList.length;f<h;++f)g===a._pageTableSortList[f]&&(i=!1,"DESC"===d.status?(d.status="ASC",e[e.length]="`"+a._pageTableSortList[f]+"`"):(d.status="DESC",e[e.length]="`"+a._pageTableSortList[f]+"` DESC"));i&&delete d.status;c.sortStyle(d)}b._pageTableConfig.sortStr=e.join(",");c.load(b)}},pageClickFn:function(b,a,c){return function(){if(!0===a)b.setAttribute("_pageTableCurPage",1),b.setAttribute("_pagetablecurpage",
1);else if(!1===a)b.setAttribute("_pageTableCurPage",b.getAttribute("_pageTableTotalPages")),b.setAttribute("_pagetablecurpage",b.getAttribute("_pageTableTotalPages"));else if(null===a)for(var d=c.parentNode.getElementsByTagName("input"),e=0,k=d.length;e<k;++e)g.toPageKeypressFn(b,d[e])();else d=parseInt(b.getAttribute("_pageTableCurPage"))+a,1>d?d=1:d>b.getAttribute("_pageTableTotalPages")&&(d=b.getAttribute("_pageTableTotalPages")),b.setAttribute("_pageTableCurPage",d),b.setAttribute("_pagetablecurpage",
d);g.load(b)}},toPageKeypressFn:function(b,a){return function(c){if(void 0===c||"13"==c.keyCode){if("toPage"===a.id){var d=parseInt(a.value);if(isNaN(d)){a.value="";return}1>d?d=1:d>b.getAttribute("_pageTableTotalPages")&&(d=b.getAttribute("_pageTableTotalPages"));a.value=d+1<=b.getAttribute("_pageTableTotalPages")||0>b.getAttribute("_pageTableTotalItems")?d+1:1;b.setAttribute("_pageTableCurPage",d);b.setAttribute("_pagetablecurpage",d)}else if("pageSize"===a.id)if(d=parseInt(a.value),0<d){if(0<=
b.getAttribute("_pageTableTotalItems")){var e=Math.ceil(b.getAttribute("_pageTableTotalItems")/d);b.setAttribute("_pageTableTotalPages",e);b.setAttribute("_pagetabletotalpages",e);b.getAttribute("_pageTableCurPage")>e&&(b.setAttribute("_pageTableCurPage",e),b.setAttribute("_pagetablecurpage",e))}b.setAttribute("_pageTablePageSize",d);b.setAttribute("_pagetablepagesize",d)}else a.value="";void 0!==c&&g.load(b)}}}};null==window.L.extension.pageTable&&(window.L.extension.pageTable={});"function"!==typeof window.L.extension.pageTable.init&&
(window.L.extension.pageTable.classObj=g,window.L.extension.pageTable.init=g.init,g.init(),g.initCustomNav.resize=function(){window.clearTimeout(arguments.callee.timeout);arguments.callee.timeout=window.setTimeout(function(){for(var b=document.getElementsByTagName("table"),a=0,c=b.length;a<c;++a)typeof b[a].getAttribute("_pageTableDataset")==="string"&&g.initCustomNav(b[a])},150)},window.L.onEvent.addEvent(window,"resize",g.initCustomNav.resize))})();
