$(function(){$(".search").click(function(){var b=$("input[name=role_name]").val(),a=$("input[name=role_desc]").val();$.post("./roleCtl.php?a=roleManage",{roleName:b,roleDesc:a},function(a){$(".table_content table").remove();$(".table_content").append(a);window.L.extension.pageTable.init()})});$(".reset").click(function(){clsForm()})});
window.L.strVar("L.extension.pageTable.callback.afterLoadList[]",window.L.strVar("L.extension.pageTable.callback.initLoadList[]",function(b){if("admin_role_roleCtl::rolePageList"===$(b).attr("_pagetabledataset")){var a="",a=a+'&nbsp;<div class="action_toolbar">',a=a+'<div class="inner">',a=a+'<div class="right"></div>',a=a+'<div class="inner_box">',a=a+'<div class="action_link">',a=a+"</div>",a=a+"</div>",a=a+"</div>",a=a+"</div>";L.extension.pageTable.classObj.eachTbody(b,"*",7,function(b){$(b.tdObj).html(a).parent().hover(function(){var a=
$(this).find("td").eq(1).text(),b="<a href='#' onclick='openRoleEditDiv("+a+")' >"+window.L.getText("\u7f16\u8f91\u89d2\u8272")+"</a>",b=b+("<a href='#' onclick='delRole("+a+")' >"+window.L.getText("\u5220\u9664\u89d2\u8272")+"</a>");$(".action_link").html(b);$(".action_toolbar",this).show().animate({marginLeft:"8px"},{queue:!1,duration:200})},function(){$(".action_toolbar",this).hide().animate({marginLeft:"10px"},{queue:!1,duration:200})})})}}));
window.L.strVar("L.extension.pageTable.callback.initLoadList[]",function(b){"admin_role_roleCtl::rolePageList"===$(b).attr("_pagetabledataset")&&($(".del").click(function(){var a="";$("input[name=uid]:checked").each(function(){a+=$(this).val()+","});if(0==a.length)return oDialogDivInfo(window.L.getText("\u8bf7\u9009\u62e9\u89d2\u8272!")),!1;window.L.openCom("oDialogDiv")(window.L.getText("\u786e\u8ba4\u5220\u9664\uff1f"),"text:<div>"+window.L.getText("\u771f\u7684\u60f3\u5220\u9664\u8fd9\u4e9b\u4fe1\u606f\u5417?")+
"</div>","260","110",[2,function(b){b&&$.post("./roleCtl.php?a=roleOperating",{userId:a,sts:"del"},function(){oDialogDivInfo(window.L.getText("\u5220\u9664\u6210\u529f!"));$(".search").trigger("click")})}])}),$(".delAll").click(function(){var a="";$("input[name=uid]").each(function(){a+=$(this).val()+","});window.L.openCom("oDialogDiv")(window.L.getText("\u786e\u8ba4\u5220\u9664\uff1f"),"text:<div>"+window.L.getText("\u771f\u7684\u60f3\u5220\u9664\u8fd9\u4e9b\u4fe1\u606f\u5417?")+"</div>","260","110",
[2,function(b){b&&$.post("./roleCtl.php?a=roleOperating",{userId:a,sts:"del"},function(){oDialogDivInfo(window.L.getText("\u5220\u9664\u6210\u529f!"));$(".search").trigger("click")})}])}))});function clsForm(){$("input[name = role_name]").val("");$("input[name = role_desc]").val("")}
function openRoleEditDiv(b){window.L.openCom("oDialogDiv")(window.L.getText("\u89d2\u8272\u4fee\u6539"),"iframe:./roleCtl.php?a=dialogModfiyRole&rid="+b,"1100","640",[2,{mouseClickFun:function(a,b,d){if(a){var a=$(window.frames["oDialogDiv_iframe_"+d.handle].document),b=a.find("input[name=role_id]").val(),d=a.find("input[name=role_name]").val(),e=a.find("input[name=role_desc]").val(),c="";a.find("input:checkbox").each(function(){$(this).attr("checked")&&(c+=$(this).attr("id")+",")});$.post("./roleCtl.php?a=roleUpdate",
{val:b+"&"+c.substr(0,c.length-1)+"&"+d+"&"+e},function(a){$(".search").trigger("click");"1"==a&&oDialogDivInfo(window.L.getText("\u89d2\u8272\u4fee\u6539\u6210\u529f !"),2E3,-2)})}}}])}
function delRole(b){window.L.openCom("oDialogDiv")(window.L.getText("\u786e\u8ba4\u4fe1\u606f"),"text:<div>"+window.L.getText("\u771f\u7684\u8981\u5220\u9664\u8fd9\u4e9b\u4fe1\u606f\u5417?")+"</div>","260","110",[2,function(a){a&&$.post("./roleCtl.php?a=roleOperating",{userId:b+",",sts:"del"},function(){oDialogDivInfo(window.L.getText("\u5220\u9664\u6210\u529f!"));$(".search").trigger("click")})}])};
