var MANY_TREES_LIST={};
function getTree(a){window.L.openCom("zTree");a=$.extend({},{isCheckBox:!1,treeMark:"",dataType:"group",autoHide:!0,callbackFn:"",targetId:"",targetNameId:"",targetValueId:"",topId:"",isAsync:!1,showRoot:!0,showPosition:{left:"none",top:"none"},isKeepSelected:!0,isExpand:!1,allowCheckParent:!0,expandLevel:0,onCheck:null,isDiyOnCheck:!0,checkedId:null,chkboxType:{Y:"ps",N:"ps"},isFront:!1,enableCheck:!0,enableCheckedId:null,errorStr:null,allow_groups:null},a);""!=a.targetId&&null!==$("#"+a.targetId).offset()?
(a.showPosition.left="none"===a.showPosition.left?$("#"+a.targetId).offset().left:a.showPosition.left,a.showPosition.top="none"===a.showPosition.top?$("#"+a.targetId).offset().top+$("#"+a.targetId).outerHeight():a.showPosition.top):null!==$("#"+a.targetNameId).offset()?(a.showPosition.left="none"===a.showPosition.left?$("#"+a.targetNameId).offset().left:a.showPosition.left,a.showPosition.top="none"===a.showPosition.top?$("#"+a.targetNameId).offset().top+$("#"+a.targetNameId).outerHeight():a.showPosition.top):
(a.showPosition.left="none"===a.showPosition.left?0:a.showPosition.left,a.showPosition.top="none"===a.showPosition.top?0:a.showPosition.top);if(void 0===MANY_TREES_LIST["treeList"+a.dataType+a.isCheckBox+a.topId+a.treeMark]){var b="<iframe name='treeContentIframe' id='treeIframe"+a.dataType+a.isCheckBox+a.topId+a.treeMark+"' style='display:none; position: absolute;z-index:21474835646;'></iframe><div id='treeContent"+a.dataType+a.isCheckBox+a.topId+a.treeMark+"' name='treeContent' class='menuContent' style='display:none; position: absolute;z-index:21474835647;'><ul id='treeList"+
a.dataType+a.isCheckBox+a.topId+a.treeMark+"' class='ztree' style='border: 1px solid #617775;background: #f0f6e4;width:100%;*+width:300px;height:150px;overflow-y:scroll;overflow-x:auto;'><img style='position:absolute ;left:95px;top:60px;' id='treeLoadingImg' src='"+L._viewUrl+"/images/preload.gif'/></ul>";a.isCheckBox&&null==a.onCheck&&(b+='<a href="javascript:void(0)" onclick="treeCallBackFn(null,\'treeList'+a.dataType+a.isCheckBox+a.topId+a.treeMark+'\');return false;" id="treeListCbBtn" style="position:absolute;bottom:0px;right:20px;">'+
window.L.getText("\u786e\u5b9a")+"</a>");$("body").append(b+"</div>");$("#treeContent"+a.dataType+a.isCheckBox+a.topId+a.treeMark).css({left:a.showPosition.left+"px",top:a.showPosition.top+"px"}).show();$("#treeIframe"+a.dataType+a.isCheckBox+a.topId+a.treeMark).width($("#treeContent"+a.dataType+a.isCheckBox+a.topId+a.treeMark).width()-3);$("#treeIframe"+a.dataType+a.isCheckBox+a.topId+a.treeMark).height($("#treeContent"+a.dataType+a.isCheckBox+a.topId+a.treeMark).height()-3);$("#treeIframe"+a.dataType+
a.isCheckBox+a.topId+a.treeMark).css({left:a.showPosition.left+"px",top:a.showPosition.top+"px"}).show();$("body").bind("mousedown",treeOnBodyDown);var c=a.isFront?L._rootUrl+"/index.php?a=_manytrees":window.L._adminUrl+"/manytrees/manyTreesCtl.php?a=getTrees",b="tree_option="+encodeURIComponent(L.JSON.stringify(a));$.ajax({type:"POST",async:!0,url:c,data:b,dataType:"json",beforeSend:function(){},success:function(b){if(b.res=="success"){if(b.allow_groups!=void 0&&b.allow_groups!="allow")a.allow_groups=
b.allow_groups;async_tree_option=a;async_tree_option.showRoot=false;var e={tree_option:encodeURIComponent(L.JSON.stringify(async_tree_option))},e={view:{dblClickExpand:false,selectedMulti:false},check:{enable:a.isCheckBox,chkStyle:"checkbox",chkboxType:a.chkboxType},data:{simpleData:{enable:true}},async:{enable:a.isAsync,url:c,otherParam:e,dataFilter:treeAsyncDataFilter,dataType:"json",autoParam:["id=topId"]},callback:{onClick:a.isCheckBox?null:treeCallBackFn,beforeClick:treeBeforeClick,onCheck:a.isDiyOnCheck?
a.onCheck:treeOnCheck,beforeCheck:treeEnableCheck,onExpand:treeExpandCheck}},b=window.L.openCom("zTree",{expand:["excheck","exedit"]}).init($("#treeList"+a.dataType+a.isCheckBox+a.topId+a.treeMark),e,b.info);a.isExpand&&b.expandAll(true);if(a.expandLevel>0){e=b.getNodes();treeExpendNode(b,e,0,a.expandLevel)}MANY_TREES_LIST["treeList"+a.dataType+a.isCheckBox+a.topId+a.treeMark]=a;treeInitStyle(b,a)}else{window.L.openCom("tip")(b.info);$("#treeIframe"+a.dataType+a.isCheckBox+a.topId+a.treeMark).remove();
$("#treeContent"+a.dataType+a.isCheckBox+a.topId+a.treeMark).remove()}},error:function(){}})}else $("#treeContent"+a.dataType+a.isCheckBox+a.topId+a.treeMark).css({left:a.showPosition.left+"px",top:a.showPosition.top+"px"}).show(),$("#treeIframe"+a.dataType+a.isCheckBox+a.topId+a.treeMark).css({left:a.showPosition.left+"px",top:a.showPosition.top+"px"}).show(),$("body").bind("mousedown",treeOnBodyDown);void 0!==MANY_TREES_LIST["treeList"+a.dataType+a.isCheckBox+a.topId+a.treeMark]&&(MANY_TREES_LIST["treeList"+
a.dataType+a.isCheckBox+a.topId+a.treeMark]=a,b=$.fn.zTree.getZTreeObj("treeList"+a.dataType+a.isCheckBox+a.topId+a.treeMark),treeInitStyle(b,a))}function treeInitStyle(a,b){null!==a&&(b.isKeepSelected||(a.cancelSelectedNode(),a.checkAllNodes(!1)),null!=b.checkedId&&b.isCheckBox&&(a.cancelSelectedNode(),a.checkAllNodes(!1),$.each(b.checkedId,function(b,d){var e=a.getNodeByParam("id",d,null);e!=null&&a.checkNode(e,true,true)})),treeDisableCheckNode(a.getNodes(),b,a))}
function treeDisableCheckNode(a,b,c){var a=c.transformToArray(a),d=!0,e=!0;$.each(a,function(a,c){if(null!=b.enableCheckedId){d=!1;for(var h in b.enableCheckedId)if(b.enableCheckedId[h]==c.id){d=!0;break}}if(null!=b.allow_groups){e=!1;for(var i in b.allow_groups)if(b.allow_groups[i]==c.id){e=!0;break}}if(!d||!e)$("#"+c.tId+"_check").css({"background-position":"0 -56px"}),$("#"+c.tId+"_span").css({color:"#CCCCCC"})})}
function treeExpandCheck(a,b,c){a=MANY_TREES_LIST[b];b=$.fn.zTree.getZTreeObj(b);treeDisableCheckNode(c,a,b)}
function treeEnableCheck(a,b){var c=MANY_TREES_LIST[a],d=!0;null!=c.enableCheckedId&&(d=!1,$.each(c.enableCheckedId,function(a,c){b.id==c&&(d=!0)}));var e=!0;null!=c.allow_groups&&(e=!1,$.each(c.allow_groups,function(a,c){b.id==c&&(e=true)}));d=e&&d?!0:!1;if(!d){var f=window.L.openCom("tip"),g=window.L.getText("\u60a8\u65e0\u6743\u9650\u64cd\u4f5c\u6b64\u9879");null!=c.errorStr&&void 0!=c.errorStr.disableCheck&&(g=c.errorStr.disableCheck);f(g)}return d}
function treeExpendNode(a,b,c,d){c<d&&(c++,$.each(b,function(b,f){a.expandNode(f,!0,!1,!0);void 0!=f.children&&treeExpendNode(a,f.children,c,d)}))}
function treeBeforeClick(a,b){var c=MANY_TREES_LIST[a];$.fn.zTree.getZTreeObj(a);var d=!0;MANY_TREES_LIST[a].allowCheckParent||b.isParent&&(d=!1);null!=MANY_TREES_LIST[a].allow_groups&&(d=!1,$.each(MANY_TREES_LIST[a].allow_groups,function(a,c){b.id==c&&(d=!0)}));if(!d){var e=window.L.openCom("tip"),f=window.L.getText("\u60a8\u65e0\u6743\u9650\u64cd\u4f5c\u6b64\u9879");null!=c.errorStr&&void 0!=c.errorStr.disableCheck&&(f=c.errorStr.disableCheck);e(f)}return d}
function treeAsyncDataFilter(a,b,c){return"success"==c.res?c.info:null}function treeOnCheck(a,b,c){MANY_TREES_LIST[b].onCheck({treeMark:MANY_TREES_LIST[b].treeMark,id:c.id,name:c.name,checked:c.checked})}
function treeCallBackFn(a,b,c){if(MANY_TREES_LIST[b].isCheckBox){var a=$.fn.zTree.getZTreeObj(b).getCheckedNodes(),d={};$(a).each(function(a){d[a]={id:this.id,name:this.name,parent:this.isParent}});"function"==typeof MANY_TREES_LIST[b].callbackFn&&MANY_TREES_LIST[b].callbackFn(d)}else{if(void 0!==$("#"+MANY_TREES_LIST[b].targetNameId).get(0))switch($("#"+MANY_TREES_LIST[b].targetNameId).get(0).tagName){case "INPUT":$("#"+MANY_TREES_LIST[b].targetNameId).val(c.name);break;case "SELECT":$("#"+MANY_TREES_LIST[b].targetNameId).html('<option value="treeNode.id">'+
c.name+"</option>");break;default:$("#"+MANY_TREES_LIST[b].targetNameId).html(c.name)}if(void 0!==$("#"+MANY_TREES_LIST[b].targetValueId).get(0))switch($("#"+MANY_TREES_LIST[b].targetValueId).get(0).tagName){case "INPUT":$("#"+MANY_TREES_LIST[b].targetValueId).val(c.id);break;default:$("#"+MANY_TREES_LIST[b].targetValueId).html(c.id)}"function"==typeof MANY_TREES_LIST[b].callbackFn&&MANY_TREES_LIST[b].callbackFn(c.id,c.name)}MANY_TREES_LIST[b].autoHide&&treeHideTree();return!1}
function treeOnBodyDown(a){-1==a.target.id.indexOf("treeList")&&treeHideTree()}function treeHideTree(){$("[name='treeContent']").hide();$("[name='treeContentIframe']").hide();$("body").unbind("mousedown",treeOnBodyDown)};
