function examToggleSearchBox(){$("#searchExam").toggle()}function examSearchExamList(){var a={exam_name:$.trim($("#exam_name").val())},b=$('table[_pagetabledataset="exam_examCtl::getExamPageTable"]');window.L.extension.pageTable.classObj.params(b.get(0),a,!0)}function examSearchExerciseList(){var a={exam_name:$.trim($("#exam_name").val())},b=$('table[_pagetabledataset="exam_examCtl::getExercisePageTable"]');window.L.extension.pageTable.classObj.params(b.get(0),a,!0)}
function examInitExamList(){var a="",b=0,c=0,h=null,j=null,i=null,f=null,k="0",g='<a class="icon_link" onclick="return false;" href="#"><span class="icon_bm"></span><font>'+window.L.getText("\u60a8\u4e0d\u5728\u8003\u8bd5\u8303\u56f4\u5185")+"</font></a>",e="",d=!1;$("input[name='exam_list_id']").each(function(){d=!1;a=$(this).val();b=$("#exam_all_person_"+a).val();c=$("#exam_user_verify_flg_"+a).val();"0"==USER_IS_LOGIN?$("#exam_join_div_"+a).html(g):"1"==c&&"070102"!=USER_STATUS?$("#exam_join_div_"+
a).html(g):("1"!=b?(""!=$("#include_user_ids_"+a).val()&&(j=$("#include_user_ids_"+a).val().split(","),$.each(j,function(a,b){if(b==USER_ID)return d=!0,!1})),i=L.JSON.parse($("#include_group_json_"+a).val()),void 0!=i&&$.each(USER_GROUP,function(a,b){if(d)return false;$.each(i,function(h,c){if(a=="0"&&b==c.group_id||a!="0"&&b==c.group_id&&c.is_include_sub=="1"){d=true;return false}})})):d=!0,h=$("#exclude_user_ids_"+a).val().split(","),$.each(h,function(b,c){if(c==USER_ID){$("#exam_join_div_"+a).html(g);
return d=false}}),k=$("#exam_user_signup_flg_"+a).val(),"1"==k&&d)?(f=$("#exam_user_verify_"+a).val(),""==f?(e='<a href="javascript:void(0)" onclick="examDisplayUserSignUp(\''+a+'\')" class="btn">'+window.L.getText("\u7533\u8bf7\u62a5\u540d")+"</a>",$("#exam_join_div_"+a).html(e)):"070202"==f?(e='<a class="icon_link" onclick="return false;" href="#"><span class="icon_bm"></span><font>'+window.L.getText("\u672a\u901a\u8fc7\u5ba1\u6838")+"</font></a>",$("#exam_join_div_"+a).html(e)):"070203"==f&&(e=
'<a class="icon_link" onclick="return false;" href="#"><span class="icon_bm"></span><font>'+window.L.getText("\u6b63\u5728\u5ba1\u6838")+"</font></a>",$("#exam_join_div_"+a).html(e))):d||$("#exam_join_div_"+a).html(g)})}
function examDisplayUserSignUp(a){window.L.openCom("oDialogDiv");oDialogDiv("\u63d0\u4ea4\u7533\u8bf7",'text:<div style="width:200px; height:50px;">'+window.L.getText("\u7533\u8bf7\u4fe1\u606f")+'<br><input type="text" id="app_content" name="app_content" /></div>',"auto","auto",[2,function(b){if(b){var b=L._rootUrl+"/exam/examCtl.php?a=userVerify",c="exam_id="+a+"&app_content="+$("#app_content").val();$.ajax({type:"POST",async:!1,url:b,data:c,dataType:"json",success:function(a){"success"==a.res?(a=
void 0==$('table[_pagetabledataset="exam_examCtl::getExamPageTable"]').get(0)?$('table[_pagetabledataset="exam_exerciseCtl::getExercisePageTable"]'):$('table[_pagetabledataset="exam_examCtl::getExamPageTable"]'),window.L.extension.pageTable.classObj.pageClickFn(a.get(0),0)(),oDialogDivInfo(window.L.getText("\u7533\u8bf7\u5df2\u63d0\u4ea4"))):oDialogDivInfo(a.info)},error:function(){}})}}])}
function examIsIeOnly(a){if(a){if(-1!=navigator.appName.indexOf("Microsoft")){try{ie.IsOk()}catch(b){return window.L.openCom("oDialogDiv"),oDialogDiv(window.L.getText("\u6d88\u606f"),"text:<div>"+window.L.getText("\u672a\u542f\u7528\u6216\u5b89\u88c5\u5168\u5c4f\u63d2\u4ef6,\u70b9\u51fb\u786e\u5b9a\u4e0b\u8f7d\u5168\u5c4f\u63d2\u4ef6")+"</div>","270px","150px",[2,function(a){a&&examDownLoadFullScreenPlugin();return!0}]),!1}return!0}window.L.openCom("oDialogDiv");oDialogDiv(window.L.getText("\u6d88\u606f"),
"text:<div>"+window.L.getText("\u672c\u6b21\u8003\u8bd5\u53ea\u80fd\u7528IE\u6d4f\u89c8\u5668\u6253\u5f00")+"</div>","270px","150px",[1,function(){}]);return!1}return!0}function examDownLoadFullScreenPlugin(){window.location.href=window._ROOT_URL+"/exam/examCtl.php?a=downloadFullScreenPlugin"};
