var TAG_LIST={},TAG_UNSHOW_LIST={};
function tagDisplayTag(a){a=$.extend({},{tagType:"1",callbackFn:"",targetId:"",showPosition:{left:"none",top:"none"}},a);""!=a.targetId&&null!==$("#"+a.targetId).offset()&&(a.showPosition.left="none"===a.showPosition.left?$("#"+a.targetId).offset().left:a.showPosition.left,a.showPosition.top="none"===a.showPosition.top?$("#"+a.targetId).offset().top+$("#"+a.targetId).outerHeight():a.showPosition.top);if(void 0===TAG_LIST[a.tagType]){var c=window.L._adminUrl+"/tag/tagCtl.php?a=getTags",b="tag_option="+
encodeURIComponent(L.JSON.stringify(a));$.ajax({type:"POST",async:!0,url:c,data:b,dataType:"json",success:function(b){var c="<div name='tagContent' id='tagContent"+a.tagType+"' class='menuContent' style='display:none; position: absolute;z-index:21474835647;background-color:#FFFFCC;' ><label id='tagContentLab"+a.tagType+"'>";if(b.res=="success"){var f=0;TAG_UNSHOW_LIST[a.tagType]="";for(var d in b.info){f++;b.info[d].tag_id!=null&&f<=5?c=c+("<a id='tagContentA"+b.info[d].tag_id+"' href=\"javascript:"+
a.callbackFn+"('"+b.info[d].tag_id+"','"+b.info[d].tag_name+"')\">"+b.info[d].tag_name+"</a> "):TAG_UNSHOW_LIST[a.tagType]=TAG_UNSHOW_LIST[a.tagType]+("<a id='tagContentA"+b.info[d].tag_id+"' href=\"javascript:"+a.callbackFn+"('"+b.info[d].tag_id+"','"+b.info[d].tag_name+"')\">"+b.info[d].tag_name+"</a> ")}}c=c+"</label>";TAG_UNSHOW_LIST[a.tagType]!=""&&(c=c+('<a href="javascript:void(0)" id="tagContentShowAllTagButton'+a.tagType+'" onclick="tagShowAllTags(\''+a.tagType+"')\">["+window.L.getText("\u663e\u793a\u5168\u90e8")+
"]</a>"));c=c+("<input type='text' value='' id='tagContentNewTagName"+a.tagType+"' /><a id='tagContentNewTagA"+a.tagType+"' href=\"javascript:tagAddNewTag('"+a.tagType+"','"+a.callbackFn+"')\">"+window.L.getText("\u6dfb\u52a0\u6807\u7b7e")+"</a></div>");$("body").append(c);TAG_LIST[a.tagType]="1";$("#tagContent"+a.tagType).css({left:a.showPosition.left+"px",top:a.showPosition.top+"px"}).show();$("body").bind("mousedown",tagOnBodyDown)}})}else $("#tagContent"+a.tagType).css({left:a.showPosition.left+
"px",top:a.showPosition.top+"px"}).show(),$("body").bind("mousedown",tagOnBodyDown)}function tagAddNewTag(a,c){var b=$("#tagContentNewTagName"+a).val(),b=tagAddTag(a,b);if("success"==b.res){var e="<a id='tagContentA"+b.info.tag_id+"' href=\"javascript:"+c+"('"+b.info.tag_id+"','"+b.info.tag_name+"')\">"+b.info.tag_name+"</a> ";$("#tagContentLab"+a).append(e);$("#tagContentNewTagName"+a).val("");eval(c+"('"+b.info.tag_id+"','"+b.info.tag_name+"')")}else window.L.openCom("tip")(b.info)}
function tagShowAllTags(a){$("#tagContentLab"+a).append(TAG_UNSHOW_LIST[a]);$("#tagContentShowAllTagButton"+a).hide()}
function tagAddTag(a,c){var b={res:"success",info:""},c=$.trim(c);""==c&&(b.res="failed",b.info=window.L.getText("\u6807\u7b7e\u540d\u4e0d\u80fd\u4e3a\u7a7a"));200<c.length&&(b.res="failed",b.info=window.L.getText("\u6807\u7b7e\u540d\u957f\u5ea6\u4e0d\u80fd\u8d85\u8fc7200"));if("success"==b.res){var e=window.L._adminUrl+"/tag/tagCtl.php?a=addTag",g="tagname="+escape(c)+"&tagtype="+a;$.ajax({type:"POST",async:!1,url:e,data:g,dataType:"json",success:function(a){b=a}})}return b}
function tagAddTagObj(a){var a=$.extend({},{objId:"1",tagIds:{},addOrReplace:"add"},a),c={res:"success",info:""},b=window.L._adminUrl+"/tag/tagCtl.php?a=addTagObj",a="tag_option="+encodeURIComponent(L.JSON.stringify(a));$.ajax({type:"POST",async:!0,url:b,data:a,dataType:"json",success:function(a){c=a}});return c}function tagOnBodyDown(a){-1==a.target.id.indexOf("tagContent")&&tagHideTag()}function tagHideTag(){$("[name='tagContent']").hide();$("body").unbind("mousedown",tagOnBodyDown)};
