function verifyInitStudyPlan(){window.L.openCom("oDialogDiv");initResetArea({selection:"#verify_search_param_div",id:"verify_search_param_div"});window.L.openCom("wDate",{obj:$("#app_begin_tm").get(0),params:{readOnly:!0}});window.L.openCom("wDate",{obj:$("#app_end_tm").get(0),params:{readOnly:!0}})}function verifyPCategoryTreeShow(c,b,a){getTree({targetNameId:c,targetValueId:b,dataType:"study_plan_source",showRoot:a?a:!1})}
function verifyCCategoryTreeShow(c,b,a){getTree({targetNameId:c,targetValueId:b,dataType:"course_category",showRoot:a?a:!1})}function showUserGroup(c){getTree({targetId:"group_name",callbackFn:function(b){window.L.each(b,function(a,b){idList[a]=b[a].id;nameList[a]=b[a].name},idList=[],nameList=[]);$(c).attr("key",idList.join(",")).val(nameList.join(","))},dataType:"group",isExpand:!1,showRoot:!1,isCheckBox:!0,chkboxType:{Y:"s",N:"ps"}})}
function verifyExamCategoryTreeShow(c,b,a){getTree({targetNameId:c,targetValueId:b,dataType:"exam_category",showRoot:a?a:!1})}function verifyResetSearchParams(){resetArea("verify_search_param_div");verifyInitStudyPlan()}
function verifyModifyOpinion(c,b,a,d){var e={obj_id:{},target_status:a,verify_type:d,veri_content:""},a="success",f="";if("selected"==c){var g=!1;$(":checkbox[name='verify_cb']:checked").each(function(a){e.obj_id[a]={obj_id:$(this).val(),user_id:$(this).attr("user_id")};g=!0});g||(a="failed",f=window.L.getText("\u8bf7\u81f3\u5c11\u9009\u4e00\u6761\u6570\u636e"))}else e.obj_id[0]={obj_id:c,user_id:b};"success"==a?oDialogDiv(window.L.getText("\u5ba1\u6838"),'text:<div style="width:200px; height:50px;">'+
window.L.getText("\u5ba1\u6838\u4fe1\u606f")+'<br><input type="text" id="veri_content" name="veri_content" /></div>',"auto","auto",[2,function(a){if(a){e.veri_content=$("#veri_content").val();var a=window.L._adminUrl+"/verify/verifyCtl.php?a=modifyOpinion",b="modify_info="+encodeURIComponent(L.JSON.stringify(e));$.ajax({type:"POST",async:!1,url:a,data:b,dataType:"json",success:function(a){if("success"==a.res){a=null;switch(d){case "study_plan":a=$('table[_pagetabledataset="admin_verify_verifyCtl::displayStudyPlanVerifyList"]');
break;case "course":a=$('table[_pagetabledataset="admin_verify_verifyCtl::displayCourseVerifyList"]');break;case "exam":a=$('table[_pagetabledataset="admin_verify_verifyCtl::displayExamVerifyList"]')}window.L.extension.pageTable.classObj.pageClickFn(a.get(0),0)()}else oDialogDivInfo(a.info)},error:function(){}})}}]):oDialogDivInfo(f)}
function verifySearchVerifyList(c){var b=verifyGetSearchCondition(c),a=null;switch(c){case "study_plan":a=$('table[_pagetabledataset="admin_verify_verifyCtl::displayStudyPlanVerifyList"]');break;case "course":a=$('table[_pagetabledataset="admin_verify_verifyCtl::displayCourseVerifyList"]');break;case "exam":a=$('table[_pagetabledataset="admin_verify_verifyCtl::displayExamVerifyList"]')}window.L.extension.pageTable.classObj.params(a.get(0),b,!0)}
function verifyGetSearchCondition(c){var b=null;switch(c){case "study_plan":b={p_name:escape($.trim($("#p_name").val())),p_category:$("#p_category").val(),app_begin_tm:$("#app_begin_tm").val(),app_end_tm:$("#app_end_tm").val(),opinion:$("#opinion").val(),real_name:escape($("#real_name").val()),group_id:$("#group_name").attr("key")};break;case "course":b={c_name:escape($.trim($("#c_name").val())),c_category:$("#c_category").val(),app_begin_tm:$("#app_begin_tm").val(),app_end_tm:$("#app_end_tm").val(),
opinion:$("#opinion").val(),real_name:escape($("#textfield").val()),group_id:$("#group_name").attr("key")};break;case "exam":b={exam_name:escape($.trim($("#exam_name").val())),exam_category:$("#exam_category").val(),app_begin_tm:$("#app_begin_tm").val(),app_end_tm:$("#app_end_tm").val(),opinion:$("#opinion").val(),real_name:escape($("#real_name").val()),group_id:$("#group_name").attr("key")}}return b}
function verifyExport(c,b){var a={data_item:c,data_ids:{},modify_target:{},select_conditions:""},d="success",e="";b&&void 0==$(":checkbox[name='verify_cb']:checked").val()&&(d="failed",e=window.L.getText("\u6700\u5c11\u9009\u4e2d\u4e00\u6761\u6570\u636e"));!b&&0==$("table.pageTable").attr("_pagetabletotalitems")&&(d="failed",e=window.L.getText("\u6ca1\u6709\u53ef\u4ee5\u5bfc\u51fa\u7684\u6570\u636e"));var f="";switch(c){case "plan":f="displayStudyPlanVerifyList";break;case "course":f="displayCourseVerifyList";
break;case "exam":f="displayExamVerifyList"}"success"==d?(b?$(":checkbox[name='verify_cb']:checked").each(function(b){a.data_ids[b]={obj_id:$(this).val(),user_id:$(this).attr("user_id")}}):(d=$('table[_pagetabledataset="admin_verify_verifyCtl::'+f+'"]').get(0),a.select_conditions=d.getAttribute("_pageTableParams")),d=window.L._adminUrl+"/verify/verifyCtl.php?a=exportVerify",encodeURIComponent(L.JSON.stringify(a)),$('<form method="post" action="'+d+'"><input type="hidden" name="modify_info" value="'+
encodeURIComponent(L.JSON.stringify(a))+'" /></form>').appendTo(document.body).submit().remove()):oDialogDivInfo(e)};
