document.body.style.backgroundImage="url()";
$(function(){window.L.openCom("wDate",{obj:$("#birthday").get(0),eventType:"click",params:{readOnly:!0}});window.L.openCom("wDate",{obj:$("#entryTime").get(0),eventType:"click",params:{readOnly:!0}});$("#save").click(function(){if("isfalse"!==$("#isfalse").attr("name"))return oDialogDivInfo(window.L.getText("\u51c6\u8003\u8bc1\u5df2\u5b58\u5728")),!1;var a=$("#pwd").val(),b=$("#adminGroup").val(),c=$("#role_id").val();if(a!=$("#repwd").val())oDialogDivInfo(window.L.getText("\u5bc6\u7801\u4e0e\u91cd\u590d\u5bc6\u7801\u4e0d\u4e00\u81f4\uff01")),$("#pwd").addClass("warning"),
$("#repwd").addClass("warning");else if(""==$("#group").val())oDialogDivInfo(window.L.getText("\u8bf7\u9009\u62e9\u7528\u6237\u5bf9\u5e94\u7684\u5206\u7ec4\uff01")),$("#group_name").addClass("warning");else if(""==$("#username").val())oDialogDivInfo(window.L.getText("\u7528\u6237\u540d\u4e0d\u80fd\u4e3a\u7a7a\uff01")),$("#username").addClass("warning");else{var d=$("#group").val(),e=$("#username").val(),f=$("#real_name").val(),g=$("#credit").val(),h=$("#point").val(),a=$("#pwd").val(),i=$(":input[name=gender][checked]").val(),
j=$(":input[name='status'][checked]").val(),k=$(":input[name='isadmin'][checked]").val(),l=$("#idcard").val(),m=$("#examcard").val(),n=$("#tel").val(),o=$("#mobiletel").val(),p=$("#email").val(),q=$("#birthday").val(),r=$("#position").val();$.post("./userCtl.php?a=userAddUser",{group:d,username:e,real_name:f,credit:g,point:h,pwd:a,gender:i,status:j,isadmin:k,idcard:l,examcard:m,tel:n,mobiletel:o,email:p,birthday:q,position:r,icon:"",adminGId:b.substr(1),roleId:c.substr(1),submitData:!0,entry_time:$("#entryTime").val()},
addUserOk)}return!1});$("#pwd").change(function(){$(this).removeClass("warning");$("#repwd").removeClass("warning")});$("#repwd").change(function(){$(this).removeClass("warning");$("#pwd").removeClass("warning")});$("#group_name").click(function(){$(this).removeClass("warning")});$("#username").change(function(){$(this).removeClass("warning")})});
function addUserOk(a,b){"success"==a&&"success"==b?(oDialogDivInfo(window.L.getText("\u7528\u6237\u6dfb\u52a0\u6210\u529f\uff01")),clsSubmitForm()):"existUser"==a?(oDialogDivInfo(window.L.getText("\u7528\u6237\u540d\u5df2\u5b58\u5728\uff01")),$("#username").addClass("warning")):"group_error"==a?oDialogDivInfo(window.L.getText("\u7ec4\u6dfb\u52a0\u5931\u8d25\uff01")):"admin_error"==a?oDialogDivInfo(window.L.getText("\u7ba1\u7406\u5458\u6dfb\u52a0\u5931\u8d25\uff01")):"maxRegNum"===a?oDialogDivInfo(window.L.getText("\u6ce8\u518c\u4eba\u6570\u5df2\u8fbe\u5230\u6700\u5927\u503c")):
oDialogDivInfo(a)}$(function(){$("#savenew").click(function(){})});$(function(){$(".btn_txt").click(function(){$("#bigPhoto").attr("src");$("#bigPhoto").attr("src",L._rootUrl+"/images/user_photo_big.jpg")})});
function clsSubmitForm(){$.ajax({async:!1,dataType:"html",url:window.L._rootUrl+"/js/admin/user/permissions/dataStratifiedHtml.js",success:function(a){a=";"===(a=$.trim(a)).substr(a.length-1)?a.substr(0,a.length-1):a;eval("("+a+')("", "", "", null, "user_group_td")')}});$("input[type=text]").val("");$("input[type=password]").val("");$("select").val("0");$("#adminView").html("");$("#adminGroup").val("");$("#role span").html("");$("#role_id").val("");$("input[type=checkbox]").attr("checked",!1);$("#adminPanel").css("display",
"none");$(":input[name=gender]:first").attr("checked",!0);$(":input[name=status]:first").attr("checked",!0);$(":input[name=isadmin]:first").attr("checked",!0);$("#role span").html("");hiddDiv()};
