var courseObj={addCourseCategoryClickFun:function(a){getTree({targetId:a.id,treeMark:a.id,callbackFn:function(b,c){a.value=c;a.setAttribute("key",b)},dataType:"course_category",isExpand:!1,showRoot:!1})},addCourseTeacherClickFun:function(){var a={"00":{name:""}};$("#c_teacher > span").each(function(){a[$(this).attr("key")]={name:$("font",this).html()}});a=window.L.JSON.stringify(a);window.L.openCom("oDialogDiv")(window.L.getText("\u8bf7\u9009\u62e9\u6559\u5e08"),"iframe:"+window.L._adminUrl+'/course/course.php?{"get" : {"a" : "getAssociatedCourseTeacherList"},"post" : {"associatedCourseTeacherList" : \''+
a+"'}}","auto","auto",[2,function(a,c,e){if(a&&"visible"===e.oDialogDivObj.find("iframe").css("visibility")){var a=e.oDialogDivObj.find("iframe").prop("contentWindow"),c=a.document.getElementById("getAssociatedCourseTeacherListPageTable"),a=a.L.extension.pageTable.classObj.params(c),c="",d;for(d in a.associatedCourseTeacherList)"00"!==d&&(c+='<span key="'+d+'"><font>'+a.associatedCourseTeacherList[d].name+'</font><a onclick="courseObj.delTeacher(this); return false;" href="#" class="icon_del"></a></span>');
$("#c_teacher").html(c)}}])},delTeacher:function(a){$(a.parentNode).remove()},allowIpRadioClickFun:function(a){"0"===a.value?$(document.getElementById("allowIp").parentNode).hide():$(document.getElementById("allowIp").parentNode).show()},inputIpBlurCheckFun:function(a){if(/^(?:(?:1?\d{1,2}|2[0-4]\d|25[0-5])\.){3}(?:1?\d{1,2}|2[0-4]\d|25[0-5])$/.test(a.value)||""===$.trim(a.value))return!0;window.L.openCom("tip")(window.L.getText("IP\u5730\u5740\u65e0\u6548,\u8bf7\u786e\u8ba4"));window.setTimeout(function(){a.focus();
a.select()},0);return!1},addIpClickFun:function(a){var b=!0;$("#allowIp > div").each(function(){if(""===$.trim($("input:eq(0)",this).val())&&""===$.trim($("input:eq(1)",this).val()))return $("input:eq(0)",this).focus(),b=!1});b&&$(a.parentNode).clone().appendTo(a.parentNode.parentNode).find("input").val("")},delIpClickFun:function(a){1<$("> div",a.parentNode.parentNode).length?$(a.parentNode).remove():($("input",a.parentNode).val(""),$("input[name=allowIpRadio][value=0]").click())},getTagList:function(){tagDisplayTag({tagType:"7",
callbackFn:"courseObj.addTagList",targetId:"getAddTagListButton"})},addTagList:function(a,b){0===$('#tagList > span[tagId="'+a+'"]').length&&$('<span tagId="'+a+'" class="icon_link"><a href="#">'+b+'</a><a class="icon_del" href="#" onclick="courseObj.delTag(this, \''+a+"'); return false;\"></a></span>").appendTo("#tagList")},delTag:function(a){$(a.parentNode).remove()},delAllTag:function(){$("#tagList").html("")},addAtt:function(a,b){$("#attList").append('<span attUrl="'+a.substr(window.attUploadUrlLen)+
'"><a title="'+window.L.getText("\u4fee\u6539\u9644\u4ef6\u540d")+'" href="#" onclick="courseObj.renameAttClickFun(this); return false;">'+b.fileObj.name+'</a><a class="icon_del" href="#" onclick="courseObj.delAtt(this); return false;"></a></span>')},delAtt:function(a){$(a.parentNode).remove()},renameAttClickFun:function(a){a.getElementsByTagName("input").length||(a.innerHTML='<input type="text" onblur="courseObj.renameAttInputBlurFun(this)" value="'+a.innerHTML+'" backupValue="'+a.innerHTML+'" />',
a=a.getElementsByTagName("input")[0],a.focus(),a.select())},renameAttInputBlurFun:function(a){""===(a.value=$.trim(a.value))||/\'|\"|\\|\//.test(a.value)?(window.L.openCom("tip")(window.L.getText("\u65e0\u6548\u9644\u4ef6\u540d")),a.parentNode.innerHTML=a.getAttribute("backupValue")):a.parentNode.innerHTML=a.value},delAllAtt:function(){$("#attList").html("")},tabSwitch:function(a){$(a).siblings().removeClass("current");a.className="current";$("div[id^=courseManagement_]").hide();$("#courseManagement_"+
a.id.split("_")[1]).show();window.L.extension.pageTable.classObj.initCustomNav()},delfrontCoverClick:function(a){a.getAttribute("fileUrl")&&window.L.openCom("oDialogDiv")(window.L.getText("\u786e\u5b9a\u8981\u5220\u9664\u5c01\u9762\u5417?"),"","auto","auto",[2,function(b){b&&(a.src=window.L._rootUrl+"/include/oFileManager/fileExtension.php?fileUrl=/images/icon/icon_thumb_default1.png",a.setAttribute("fileUrl",""))}])},addCoursewareClickFun:function(){var a=window.L.extension.pageTable.classObj,b=
document.getElementById("coursewareListPageTable"),c=window.L.JSON.stringify(a.params(b).associatedCoursewareList);window.L.openCom("oDialogDiv")(window.L.getText("\u8bf7\u9009\u62e9\u8bfe\u4ef6"),"iframe:"+window.L._adminUrl+'/course/courseware.php?{"get" : {"a" : "modfiyCourseware", "share" : 1},"post" : {"associatedCoursewareList" : \''+c+"'}}","auto","auto",[2,function(e,d,c){e&&"visible"===c.oDialogDivObj.find("iframe").css("visibility")&&(d=c.oDialogDivObj.find("iframe").prop("contentWindow"),
e=d.document.getElementById("coursewareListPageTable"),d=d.L.extension.pageTable.classObj,d.load(e),e=d.params(e),d=a.params(b),d.associatedCoursewareList=e.associatedCoursewareList,a.params(b,d,!0))}])},coursewareListSortKeypressFun:function(a,b){if("13"==a.keyCode){var c=window.L.extension.pageTable.classObj,e=document.getElementById("coursewareListPageTable"),d=c.params(e),h=b.getAttribute("key"),f=d.associatedCoursewareList[h],k=f,j=b.value,g=1;b.value<f&&(k=b.value,j=f,g=-1);1>b.value&&(b.value=
1);for(var i in d.associatedCoursewareList)"boolean"!==typeof d.associatedCoursewareList[i]&&(k<=d.associatedCoursewareList[i]&&d.associatedCoursewareList[i]<=j)&&(d.associatedCoursewareList[i]-=g);d.associatedCoursewareList[h]=b.value;c.params(e,d,!0)}},delCoursewareList:function(){var a=window.L.extension.pageTable.classObj,b=document.getElementById("coursewareListPageTable"),c=a.params(b);a.eachTbody(b,"*",0,function(a){a=$("input",a.tdObj);a.prop("checked")&&delete c.associatedCoursewareList[a.attr("key")]});
a.params(b,c,!0)},getCourseGroupListTreeClickFun:function(a,b){var c=window.L.extension.pageTable.classObj,e=document.getElementById("courseGroupListPageTable"),d=c.params(e),h={},f;for(f in d.associatedCourseGroupList)d.associatedCourseGroupList[f].type===b&&(h[f]=f);getTree({targetId:a.id,treeMark:a.id,callbackFn:function(a){for(var f in a)window.L.strVar(d,"associatedCourseGroupList."+a[f].id+".type",b),null==d.associatedCourseGroupList[a[f].id].isIncludeSub&&(d.associatedCourseGroupList[a[f].id].isIncludeSub=
!0,d.associatedCourseGroupList[a[f].id].entryTimeStart=0,d.associatedCourseGroupList[a[f].id].entryTimeEnd=0),delete h[a[f].id];for(f in h)"00"!==f&&delete d.associatedCourseGroupList[f];c.params(e,d,!0)},dataType:"group",isCheckBox:!0,isExpand:!1,showRoot:!1,expandLevel:2,checkedId:h,chkboxType:{Y:"",N:""}})},delCourseGroupList:function(){var a=window.L.extension.pageTable.classObj,b=document.getElementById("courseGroupListPageTable"),c=a.params(b);a.eachTbody(b,"*",0,function(a){(a=$("input:checked",
a.tdObj).attr("key"))&&delete c.associatedCourseGroupList[a]});a.params(b,c,!0)},changeCourseGroupListStateClickFun:function(a){var b=window.L.extension.pageTable.classObj,c=document.getElementById("courseGroupListPageTable"),e=b.params(c),d=a.getAttribute("key");a.innerHTML=window.L.getText((e.associatedCourseGroupList[d].type=!e.associatedCourseGroupList[d].type)?"\u5305\u542b":"\u6392\u9664");b.params(c,e)},changeCourseGroupListStatus:function(a){var b=window.L.extension.pageTable.classObj,c=document.getElementById("courseGroupListPageTable"),
e=b.params(c);b.eachTbody(c,"*",0,function(b){if(b=$("input:checked",b.tdObj).attr("key"))e.associatedCourseGroupList[b].type=a});b.params(c,e,!0)},changeCourseGroupListIncludeSubClickFun:function(a){var b=window.L.extension.pageTable.classObj,c=document.getElementById("courseGroupListPageTable"),e=b.params(c),a=a.getAttribute("key");e.associatedCourseGroupList[a].isIncludeSub=!e.associatedCourseGroupList[a].isIncludeSub;b.params(c,e)},getCourseUserListDialogDivClickFun:function(a,b){var c=window.L.extension.pageTable.classObj,
e=document.getElementById("courseUserListPageTable"),d=c.params(e),h={"00":{type:!1}},f;for(f in d.associatedCourseUserList)d.associatedCourseUserList[f].type===b&&(h[f]={type:!0});window.L.openCom("oDialogDiv")("\u8bf7\u9009\u62e9\u7528\u6237","iframe:"+window.L._adminUrl+'/course/course.php?{"get" : {"a" : "getAssociatedCourseUserList"}, "post" : {"associatedCourseUserList" : \''+window.L.JSON.stringify(h)+"'}}","auto","auto",[2,function(a,f,g){if(a&&"visible"===g.oDialogDivObj.find("iframe").css("visibility")){var a=
g.oDialogDivObj.find("iframe").prop("contentWindow"),f=a.document.getElementById("getAssociatedCourseUserListPageTable"),a=a.L.extension.pageTable.classObj.params(f),i;for(i in a.associatedCourseUserList)d.associatedCourseUserList[i]={type:b},delete h[i];for(i in h)"00"!==i&&delete d.associatedCourseUserList[i];c.params(e,d,!0)}}])},changeCourseUserListStateClickFun:function(a){var b=window.L.extension.pageTable.classObj,c=document.getElementById("courseUserListPageTable"),e=b.params(c),d=a.getAttribute("key");
a.innerHTML=window.L.getText((e.associatedCourseUserList[d].type=!e.associatedCourseUserList[d].type)?"\u5305\u542b":"\u6392\u9664");b.params(c,e)},delCourseUserList:function(){var a=window.L.extension.pageTable.classObj,b=document.getElementById("courseUserListPageTable"),c=a.params(b);a.eachTbody(b,"*",0,function(a){(a=$("input:checked",a.tdObj).attr("key"))&&delete c.associatedCourseUserList[a]});a.params(b,c,!0)},changeCourseUserListStatus:function(a){var b=window.L.extension.pageTable.classObj,
c=document.getElementById("courseUserListPageTable"),e=b.params(c);b.eachTbody(c,"*",0,function(b){if(b=$("input:checked",b.tdObj).attr("key"))e.associatedCourseUserList[b].type=a});b.params(c,e,!0)},entryTimeBlur:function(a,b){/^\d+$/.test(a.value)||(a.value=0);var c=window.L.extension.pageTable.classObj,e=$(a).parents("table").get(0),d=c.params(e);d.associatedCourseGroupList[$(a).attr("key")][b]=a.value;c.params(e,d)},getCourseExamListDialogDivClickFun:function(a){var b=window.L.extension.pageTable.classObj,
c=document.getElementById(a),e=b.params(c),d={"00":{}},h;for(h in e.associatedCourseExamList)d[h]={};window.L.openCom("oDialogDiv")(window.L.getText("courseExaminationListPageTable"===a?"\u8bf7\u9009\u62e9\u8003\u8bd5":"\u8bf7\u9009\u62e9\u7ec3\u4e60"),"iframe:"+window.L._adminUrl+'/course/course.php?{"get" : {"a" : "getAssociatedCourseExamList"}, "post" : {"associatedCourseExamList" : \''+window.L.JSON.stringify(d)+'\', "examType" : "'+e.examType+'"}}',"auto","auto",[2,function(a,h,j){if(a&&"visible"===
j.oDialogDivObj.find("iframe").css("visibility")){var a=j.oDialogDivObj.find("iframe").prop("contentWindow"),h=a.document.getElementById("getAssociatedCourseExamListPageTable"),a=a.L.extension.pageTable.classObj.params(h),g;for(g in a.associatedCourseExamList)e.associatedCourseExamList[g]={},delete d[g];for(g in d)"00"!==g&&delete e.associatedCourseExamList[g];b.params(c,e,!0)}}])},delCourseExamList:function(a){var b=window.L.extension.pageTable.classObj,a=document.getElementById(a),c=b.params(a);
b.eachTbody(a,"*",0,function(a){(a=$("input:checked",a.tdObj).attr("key"))&&delete c.associatedCourseExamList[a]});b.params(a,c,!0)},saveClickFun:function(){var a={c_id:$.trim($("#c_id").val()),c_name:$.trim($("#c_name").val()),c_start_time:$.trim($("#c_start_time").val()),c_end_time:$.trim($("#c_end_time").val()),c_status:$("input[name=c_status]:checked").val(),c_category:$("#c_category").attr("key"),c_elective:$("input[name=c_elective]:checked").val(),c_isModifyProgress:$("input[name=c_isModifyProgress]:checked").val(),
c_des:$.trim($("#c_des").val()),frontCoverImg:$.trim($("#frontCoverImg").attr("fileUrl")),c_teacher:{},c_pass_condition:"",c_tagList:{},c_attList:{},associatedCoursewareList:window.L.extension.pageTable.classObj.params(document.getElementById("coursewareListPageTable")).associatedCoursewareList,associatedCourseGroupList:window.L.extension.pageTable.classObj.params(document.getElementById("courseGroupListPageTable")).associatedCourseGroupList,associatedCourseUserList:window.L.extension.pageTable.classObj.params(document.getElementById("courseUserListPageTable")).associatedCourseUserList,
associatedCourseExamList:{}};""===a.c_id&&delete a.c_id;if(""===a.c_name)return window.L.openCom("tip")(window.L.getText("\u8bfe\u7a0b\u540d\u79f0\u4e0d\u80fd\u4e3a\u7a7a")),document.getElementById("c_name").focus(),!1;var b=[];$("#allowIp > div").each(function(){var a=$("input",this),d=$.trim(a.eq(0).val()),c=$.trim(a.eq(1).val());if(!(""===d&&""===c)){if(courseObj.inputIpBlurCheckFun(a.get(0))&&courseObj.inputIpBlurCheckFun(a.get(1))){""===d?d="0.0.0.0":""===c&&(c="255.255.255.255");for(var a=d.split("."),
e=c.split("."),g=0;4>g;++g)if(a[g]>e[g]){a=d;d=c;c=a;break}else if(a[g]<e[g])break}else return b=!1;b[b.length]=d+"-"+c}});if(b){a.allowIp=$("input[name=allowIpRadio][value=0]").prop("checked")?"":b.join(",");if(""===a.c_category)return window.L.openCom("tip")(window.L.getText("\u8bfe\u7a0b\u5206\u7c7b\u4e0d\u80fd\u4e3a\u7a7a")),document.getElementById("c_category").focus(),!1;$("#c_teacher > span").each(function(){a.c_teacher[$(this).attr("key")]=!0});$("input[name=c_pass_condition]:checked").each(function(){a.c_pass_condition+=
$(this).val()+";"});$("#tagList > span").each(function(){a.c_tagList[$(this).attr("tagid")]=!0});if(""===a.c_des)return window.L.openCom("tip")(window.L.getText("\u8bfe\u7a0b\u63cf\u8ff0\u4e0d\u80fd\u4e3a\u7a7a")),document.getElementById("c_des").focus(),!1;$("#attList > span").each(function(){a.c_attList[$(this).attr("atturl")]=$("a:eq(0)",this).html()});var c=window.L.extension.pageTable.classObj.params(document.getElementById("courseExerciseListPageTable")).associatedCourseExamList,e;for(e in c)a.associatedCourseExamList[e]=
!0;var c=window.L.extension.pageTable.classObj.params(document.getElementById("courseExaminationListPageTable")).associatedCourseExamList,d=!1;for(e in c)a.associatedCourseExamList[e]=!0,!d&&"00"!==e&&(d=!0);if("2;"===a.c_pass_condition&&!d)return window.L.openCom("tip")(window.L.getText("\u60a8\u9700\u8981\u9009\u62e9\u8003\u8bd5!")),!1;window.L.openCom("tip")(window.L.getText("\u6b63\u5728\u4fdd\u5b58,\u8bf7\u7a0d\u540e..."),!1,!1,!0);$.post("?a=saveCourse",a,function(b){"1"===b?(window.L.openCom("tip")(window.L.getText(a.c_id?
"\u64cd\u4f5c\u6210\u529f,\u5373\u5c06\u8df3\u8f6c\u5230\u5217\u8868\u9875":"\u64cd\u4f5c\u6210\u529f,\u5373\u5c06\u5237\u65b0\u9875\u9762"),null,!1,!0),courseObj.beforeUnloadTip.tipState=!1,window.setTimeout(function(){window.location.href=a.c_id?"?a=modfiyCourse":window.location.href},1500)):"0"===b?(window.L.openCom("tip")(window.L.getText("\u670d\u52a1\u7aef\u5224\u5b9a,\u60a8\u63d0\u4ea4\u7684\u6570\u636e\u65e0\u6548")),courseObj.beforeUnloadTip.tipState=!1):(window.L.openCom("tip")(),window.L.openCom("oDialogDiv")(window.L.getText("\u64cd\u4f5c\u5931\u8d25:"),
"text:"+b,"auto","auto",[1]))})}},beforeUnloadTip:function(a){if(arguments.callee.tipState)return a.originalEvent.returnValue=""}};
window.L.strVar("L.extension.pageTable.callback.initLoadList[]",window.L.strVar("L.extension.pageTable.callback.afterLoadList[]",function(a,b){if("coursewareListPageTable"===a.id){var c=parseInt(a.getAttribute("_pageTablePageSize"))*(parseInt(a.getAttribute("_pageTableCurPage"))-1)+1;b.params(a);b.eachTbody(a,"*",1,function(a){$("input",a.tdObj).val(parseInt(a.y)+c)});window.L.openCom("oDialogDiv").skinLayout()}else if("courseGroupListPageTable"===a.id){var e=b.params(a);b.eachTbody(a,"*",2,function(a){var b=
a.tdObj.innerHTML;a.tdObj.innerHTML='<a href="#" key="'+b+'" onclick="courseObj.changeCourseGroupListStateClickFun(this); return false;" title="'+window.L.getText("\u70b9\u51fb\u66f4\u6539")+'" >'+window.L.getText(e.associatedCourseGroupList[b].type?"\u5305\u542b":"\u6392\u9664")+"</a>"});b.eachTbody(a,"*",3,function(a){var b=a.tdObj.innerHTML;a.tdObj.innerHTML='<input key="'+b+'" type="checkbox" class="checkbox" '+(e.associatedCourseGroupList[b].isIncludeSub?'checked="checked"':"")+' onclick="courseObj.changeCourseGroupListIncludeSubClickFun(this)" />'});
b.eachTbody(a,"*",4,function(a){var b=a.tdObj.innerHTML;a.tdObj.innerHTML='<input class="input2" key="'+b+'" type="text" value="'+e.associatedCourseGroupList[b].entryTimeStart+'" onBlur="courseObj.entryTimeBlur(this, \'entryTimeStart\');" /> - <input class="input2" key="'+b+'" type="text" value="'+e.associatedCourseGroupList[b].entryTimeEnd+'" onBlur="courseObj.entryTimeBlur(this, \'entryTimeEnd\');" />'})}else"courseUserListPageTable"===a.id?(e=b.params(a),b.eachTbody(a,"*",2,function(a){var b=a.tdObj.innerHTML;
a.tdObj.innerHTML='<a href="#" key="'+b+'" onclick="courseObj.changeCourseUserListStateClickFun(this); return false;" title="'+window.L.getText("\u70b9\u51fb\u66f4\u6539")+'" >'+window.L.getText(e.associatedCourseUserList[b].type?"\u5305\u542b":"\u6392\u9664")+"</a>"})):("courseExerciseListPageTable"===a.id||"courseExaminationListPageTable"===a.id)&&b.eachTbody(a,"*",2,function(a){switch(a.tdObj.innerHTML){case "030301":a.tdObj.innerHTML=window.L.getText("\u53ef\u7528");break;case "030302":a.tdObj.innerHTML=
window.L.getText("\u7981\u7528");break;case "030303":a.tdObj.innerHTML=window.L.getText("\u7f16\u8f91");break;default:a.tdObj.innerHTML=window.L.getText("\u672a\u77e5")}})}));
$(function(){var a;a=$("#allowIp > div");1===a.length&&""===$.trim(a.find("input:eq(0)").val())&&""===$.trim(a.find("input:eq(1)").val())?$("input[name=allowIpRadio][value=0]").click():$("input[name=allowIpRadio][value=1]").click();window.L.openCom("upload")("frontCoverImgUpload",{onComplete:function(a){$("#frontCoverImg").attr({src:window.L._rootUrl+"/include/oFileManager/fileExtension.php?fileUrl="+a,fileUrl:a});document.getElementById("frontCoverImgProgress").childNodes[1].nodeValue=window.L.getText("\u4e0a\u4f20\u5c01\u9762\u56fe\u7247")},
onProgress:function(a){document.getElementById("frontCoverImgProgress").childNodes[1].nodeValue=a.percentage+"%"}},"gif;jpg;bmp;png"," ",65,18,{auto:!0,queueID:"  ",multi:!1,folder:"/frontCover"});window.L.openCom("upload")("uploadAtt",courseObj.addAtt,"rtf;txt;csv;doc;docx;ppt;pptx;xls;xlsx;pdf;chm;wmv;swf;flv;mp3;gif;jpg;bmp;png;rar;zip"," ",92,23,{auto:!0,queueID:"uploadAttProgress",multi:!0,folder:"/enclosure"});window.L.openCom("wDate",{obj:document.getElementById("c_start_time"),params:{readOnly:!0,
dateFmt:"yyyy-MM-dd HH:mm:ss"}});window.L.openCom("wDate",{obj:document.getElementById("c_end_time"),params:{readOnly:!0,dateFmt:"yyyy-MM-dd HH:mm:ss"}});$(document).keyup(function(){courseObj.beforeUnloadTip.tipState=!0});$(window).bind("beforeunload",courseObj.beforeUnloadTip)});
