var coursewareObj={beforeUnloadTip:function(b){if(arguments.callee.tipState)return b.originalEvent.returnValue=""}};
function updateImgPageTable(b){var d,a=L.extension.pageTable.classObj;d="coursewareImgAttPageTable"===b.id?$("#remoteUrl"):$("#lectureText");d.val($.trim(d.val()));if("img"===d.attr("coursewareType")&&""!==d.val()){var f=window.L.JSON.parse(d.val()),c;for(c in f)"string"===typeof f[c]&&(f[c]={src:f[c],disabled:!0});d.val(window.L.JSON.stringify(f));a.params(b,{id:b.id,strData:d.val()});a.load(b)}else a.params(b,{id:b.id},!0)}function maxImgPreview(){window.L.openCom("oDialogDiv").skinLayout()}
function qsnAddTag(b,d){"undefined"===typeof qsnAddTag.tagList[b]&&(qsnAddTag.tagList[b]=!0,$('<span id="tag_'+b+'"><a class="" href="#" onclick="return false;" >'+d+'</a><a class="icon_del" onclick="delQsnAddTag(\''+b+"')\"></a></span>").appendTo("#tagList"))}qsnAddTag.tagList={};$("#tagList > span").each(function(){qsnAddTag.tagList[this.id.split("_")[1]]=!0});function delQsnAddTag(b){$("#tag_"+b).remove();delete qsnAddTag.tagList[b]}
window.L.strVar("L.extension.pageTable.callback.initLoadList[]",window.L.strVar("L.extension.pageTable.callback.afterLoadList[]",function(b){var d=$("tfoot:first .content a",b),a=$("coursewareImgAttPageTable"===b.id?"#remoteUrl":"#lectureText"),f=function(f,b,c){var e=window.L.JSON.parse(a.val());e[b].disabled=c;f.childNodes[4].innerHTML=window.L.getText(c?"\u542f\u7528":"\u7981\u7528");a.val(window.L.JSON.stringify(e));return!1},c=function(f,b){var c=window.L.JSON.parse(a.val());c.splice(b,1);a.val(window.L.JSON.stringify(c));
return!1},i=function(f,b,c){var e=window.L.JSON.parse(a.val());!isNaN(b)&&0<=b?(b>=e.length&&(b=e.length-1),e.splice(b,0,e.splice(c,1)[0]),a.val(window.L.JSON.stringify(e)),updateImgPageTable(f)):window.L.openCom("tip")(window.L.getText("\u6392\u5e8f\u4f4d\u7f6e\u4e0d\u660e\u786e"))};d.eq(0).click(function(){$("tbody input:checkbox:checked",b).each(function(a){c(b,parseInt(this.getAttribute("key"),10)-a)});updateImgPageTable(b);return!1});d.eq(1).click(function(){$("tbody input:checkbox:checked",
b).each(function(){f(this.parentNode.parentNode,this.getAttribute("key"),!0)});return!1});d.eq(2).click(function(){$("tbody input:checkbox:checked",b).each(function(){f(this.parentNode.parentNode,this.getAttribute("key"),!1)});return!1});$('tbody input[class="input_sort"]',b).keypress(function(a){"13"==a.keyCode&&(a=parseInt(this.value,10)-1,i(b,a,this.getAttribute("key")))});var g=$('<div style="position: relative;"><div class="action_toolbar"><div class="inner_box"><div class="action_link"><a href="#">'+
window.L.getText("\u5220\u9664")+'</a><a href="#">'+window.L.getText("\u7981\u7528")+'</a><a href="#">'+window.L.getText("\u4e0a\u79fb")+'</a><a href="#">'+window.L.getText("\u4e0b\u79fb")+'</a></div></div><div class="action_toolbar_right"></div></div></div>'),e=g.get(0),h=g.find("a");h.eq(0).click(function(){c(b,$(this).parentsUntil("tbody").eq(-1).find("td:eq(0) input").attr("key"));updateImgPageTable(b);return!1});h.eq(1).click(function(){var b=window.L.JSON.parse(a.val()),c=$(this).parentsUntil("tbody").eq(-1),
e=c.find("td:eq(0) input").attr("key"),b=b[e].disabled;$(this).html(window.L.getText(b?"\u542f\u7528":"\u7981\u7528"));f(c.get(0),e,!b);return!1});h.eq(2).click(function(){var a=parseInt($(this).parentsUntil("tbody").eq(-1).find("td:eq(0) input").attr("key"),10);i(b,a-1,a);return!1});h.eq(3).click(function(){var a=parseInt($(this).parentsUntil("tbody").eq(-1).find("td:eq(0) input").attr("key"),10);i(b,a+1,a);return!1});$("tbody tr",b).hover(function(){if($(".action",this).length)try{var b=window.L.JSON.parse(a.val());
h.eq(1).html(window.L.getText(b[$(this).find("td:eq(0) input").attr("key")].disabled?"\u7981\u7528":"\u542f\u7528"));g.appendTo($(".action",this))}catch(f){}},function(){if($(".action",this).length)try{e.parentNode.removeChild(e)}catch(a){}});var j=function(a){var b,f=a[2];b="coursewareImgAttPageTable"===a[1]?$("#remoteUrl"):$("#lectureText");return function(c){var e=window.L.JSON.parse(b.val());e[f].src=c.substr((window.browseHome+window.coursewareAttFolder).length);b.val(window.L.JSON.stringify(e));
updateImgPageTable(document.getElementById(a[1]))}};$(b).find("input[type=file]").each(function(){window.L.openCom("upload")(this.id,j(this.id.split("_")),"jpg;gif;png",'<font color="#1A5F9B" size="13" >'+window.L.getText("\u66f4\u6362\u56fe\u7247")+"</font>",60,15,{auto:!0,queueID:!0,multi:!1,folder:window.coursewareAttFolder})});$(b).find("img").click(function(){window.L.openCom("oDialogDiv")("",'text:<img src="'+$(this).attr("bigImg")+'" onload="maxImgPreview()" />')})}));
$(function(){var b={onSelectOnce:function(a){var b=document.getElementById("remoteUrl");!1!==a&&($("input[name=coursewareType]").prop("disabled",!0),window.L.openCom("tip")(window.L.getText("\u6b63\u5728\u4e0a\u4f20\u8bf7\u7a0d\u540e"),!1));"img"===$("input[name=coursewareType]:checked").val()?(b.tempUrlList=window.L.JSON.parse(b.value),$.isArray(b.tempUrlList)||(b.tempUrlList=[])):b.tempUrlList=[]}};b.onComplete=b.onCancel=function(a,b){var c=$("input[name=coursewareType]:checked").val();"string"===
typeof a&&document.getElementById("remoteUrl").tempUrlList.push(("img"===c?a:unescape(a)).substr((window.browseHome+window.coursewareAttFolder).length));if(!0!==b&&0==$("#coursewareUpload").attr("fileCount")){var d="",d="img"===c?window.L.JSON.stringify(document.getElementById("remoteUrl").tempUrlList):document.getElementById("remoteUrl").tempUrlList.join(",");""!==$.trim(d)&&($("#remoteUrl").val(d).attr("coursewareType",c),$("input[name=coursewareType]:checked").parent().siblings().css("fontWeight",
"normal").end().css("fontWeight","bold"),updateImgPageTable(document.getElementById("coursewareImgAttPageTable")));$("input[name=coursewareType]").prop("disabled",!1);window.L.openCom("tip")()}};window.L.openCom("upload")("coursewareUpload",b,"",'<font color="#444444" size="13" >'+window.L.getText("\u70b9\u51fb\u4e0a\u4f20")+"</font>",60,15,{auto:!0,queueID:"coursewareUploadProgress",multi:!1,folder:window.coursewareAttFolder});$("#selectMediaFile").click(function(){b.onSelectOnce(!1);window.L.openCom("oFM")(function(a){b.onComplete(a.url,
!0);window.L.openCom("tip")(window.L.getText("\u6dfb\u52a0\u6210\u529f"),null,!1)},{closeCallBackFun:b.onComplete},"img"!==$("input[name=coursewareType]:checked").val(),{fileExt:this.getAttribute("fileext"),selectExt:this.getAttribute("fileext"),browseDir:window.coursewareAttFolder});return!1});$("#remoteUrl").focus(function(){window.L.openCom("tip")(window.L.getText("\u60a8\u6240\u586b\u5199\u7684\u975e\u7a7a\u8def\u5f84\u5c06\u66ff\u6362\u539f\u6765\u7684\u8bfe\u4ef6\u5730\u5740"),!1);$(this).attr("coursewareUrlText",
$.trim(this.value))}).blur(function(){window.L.openCom("tip")();this.value=$.trim(this.value);""!==this.value&&$(this).attr("coursewareUrlText")!==this.value&&($(this).attr("coursewareType",$("input[name=coursewareType]:checked").val()),$("input[name=coursewareType]:checked").parent().siblings().css("fontWeight","normal").end().css("fontWeight","bold"));$(this).removeAttr("coursewareUrlText")});$("input[name=localOrRemote]").click(function(){var a=$("#selectMediaFile"),b=$("#remoteUrl");"local"===
this.value?($("#coursewareUploadUploader").css("visibility","visible"),a.show(),b.hide()):(a.hide(),b.show(),window.setTimeout(function(){var a=document.getElementById("coursewareUploadUploader");a.style.visibility="hidden";a.updateSettings||window.setTimeout(arguments.callee,100)},0))});$("#delCoursewareAtt").click(function(){window.L.openCom("oDialogDiv")(window.L.getText("\u786e\u5b9a\u5220\u9664\u8bfe\u4ef6?"),"","auto","auto",[[window.L.getText("\u786e\u5b9a"),window.L.getText("\u53d6\u6d88")],
function(a){0===a&&($("input[name=coursewareType]:checked").parent().siblings().css("fontWeight","normal"),$("#remoteUrl").attr("coursewareType","none").val(""),updateImgPageTable(document.getElementById("coursewareImgAttPageTable")),$("input[name=coursewareType][value=none]").click().parent().siblings().css("fontWeight","normal").end().css("fontWeight","bold"))}]);return!1});$("input[name=coursewareType]").click(function(){var a=$("#selectMediaFile"),b=$("#coursewareTypeUploadBlock"),c=b.find(".thumb_default_upload:eq(0)"),
d=b.find(".right > div:eq(0)"),g=b.find("table:eq(0)"),e=function(a,b){window.L.openCom("upload").updateSettings("coursewareUpload",a,b)};if("none"===this.value){if("none"!==$("#remoteUrl").attr("coursewareType"))return $("#delCoursewareAtt").click(),!1;b.hide()}else b.show(),g.parent().hide(),$("input[name=localOrRemote]").parent().show(),e("multi",!1),"img"===this.value?(g.parent().show(),$("input[name=localOrRemote]").eq(1).parent().hide().end().end().eq(0).click(),e("multi",!0)):"youku"===this.value&&
$("input[name=localOrRemote]").eq(0).parent().hide().end().end().eq(1).click();switch(this.value){case "flv":d.html(window.L.getText("\u4e0a\u4f20FLV\u683c\u5f0f\u89c6\u9891(\u6700\u4f73\u5c3a\u5bf8\uff1a969 x 528 \u50cf\u7d20)\uff1a"));c.prop("className","thumb_default_upload");a.attr("fileExt","flv");e("fileExt","*.flv;");e("fileDesc",window.L.getText("\u73b0\u5728\u8bf7\u9009\u62e9\u4e00\u4e2a.flv\u6587\u4ef6"));break;case "swf":d.html(window.L.getText("\u4e0a\u4f20SWF\u683c\u5f0f\u89c6\u9891(\u6700\u4f73\u5c3a\u5bf8\uff1a969 x 528 \u50cf\u7d20)\uff1a"));
c.prop("className","thumb_default_upload thumb_swf");a.attr("fileExt","swf");e("fileExt","*.swf;");e("fileDesc",window.L.getText("\u73b0\u5728\u8bf7\u9009\u62e9\u4e00\u4e2a.swf\u6587\u4ef6"));break;case "mp3":d.html(window.L.getText("\u4e0a\u4f20MP3\u683c\u5f0f\u97f3\u9891\u6587\u4ef6\uff1a"));c.prop("className","thumb_default_upload thumb_music");a.attr("fileExt","mp3");e("fileExt","*.mp3;");e("fileDesc",window.L.getText("\u73b0\u5728\u8bf7\u9009\u62e9\u4e00\u4e2a.mp3\u6587\u4ef6"));break;case "youku":d.html(window.L.getText("\u586b\u5199\u4f18\u9177\u8fde\u63a5\u5730\u5740"));
c.prop("className","thumb_default_upload");a.attr("fileExt",".");e("fileExt","*.;");break;case "img":d.html(window.L.getText("\u4e0a\u4f20\u56fe\u7247\u683c\u5f0f\u7684\u6587\u6863\uff1a"));c.prop("className","thumb_default_upload thumb_default_doc");a.attr("fileExt","jpg;png;gif");e("fileExt","*.jpg;*.png;*.gif;");e("fileDesc",window.L.getText("\u8bf7\u60a8\u9009\u62e9.jpg\u3001png\u6216.gif\u6587\u4ef6"));L.extension.pageTable.classObj.initCustomNav(document.getElementById("coursewareImgAttPageTable"));
break;case "pdf":d.html(window.L.getText("\u4e0a\u4f20PDF\u683c\u5f0f\u7684\u6587\u4ef6\uff1a")),c.prop("className","thumb_default_upload thumb_default_doc"),a.attr("fileExt","pdf"),e("fileExt","*.pdf;"),e("fileDesc",window.L.getText("\u73b0\u5728\u8bf7\u9009\u62e9\u4e00\u4e2a.pdf\u6587\u4ef6"))}});$("input[name=coursewareType][value="+$("#remoteUrl").attr("coursewareType")+"]").click().parent().siblings().css("fontWeight","normal").end().css("fontWeight","bold");/\w+:\/\/.*/.test($("#remoteUrl").val())&&
$("input[name=localOrRemote]:eq(1)").click();$("#calculationHours").click(function(){var a=$("#remoteUrl").val(),b=$("#remoteUrl").attr("coursewareType");if("mp3"===b||"flv"===b||"youku"===b){window.L.openCom("tip")(window.L.getText("\u6b63\u5728\u8ba1\u7b97\u8bf7\u7a0d\u7b49..."),!1);if("youku"===b){if($.ajax({async:!1,url:"?a=getYoukuMediaId",type:"post",data:{url:a},success:function(b){a=b}}),""===a){window.L.openCom("tip")(window.L.getText("\u60a8\u6240\u9009\u62e9\u7684\u8bfe\u4ef6\u65e0\u6cd5\u8ba1\u7b97\u5b66\u65f6"));
return}}else a=/^\w+:\/\/.+$/.test(a)?a:window.L._rootUrl+window.browseHome+window.coursewareAttFolder+a;this.disabled=!0;var c=new ofPlayerClass({url:window.L._rootUrl+"/include/oFileManager/include/player/ofplayer.swf",vars:"Ctn=false&SkinURL=skin/defaultSE.zip&Decoders=getYoukuVideo.swf&JSenable=true",obj:document.getElementById("ofPlayerHours"),width:1,height:1});c.$(function(){c.jsOfPlayerFn("mute");c.jsOfPlayerFn("reload","type:"+b+";url:"+a)});c.insterIntervalFn(function(a){var b=this.jsOfPlayerFn("getinfo",
"playback");0<b.positionRemainS&&($("#coursewareHours").val(Math.round(100*((b.positionS+b.positionRemainS)/60))/100),this.removeOfPlayer(),a.disabled=!1,window.L.openCom("tip")())},[this],-1)}else if("img"===b){var d=0,a=window.L.JSON.parse(a),g;for(g in a)a[g].disabled&&++d;$("#coursewareHours").val(d)}else"none"===b?$("#coursewareHours").val(0):"pdf"===b?(window.L.openCom("tip")(window.L.getText("\u6b63\u5728\u8ba1\u7b97\u8bf7\u7a0d\u7b49..."),!1),window.onDocumentLoaded=function(a){$("#coursewareHours").val(a);
window.L.openCom("tip")()},$("#ofPlayerHours").html('<object width="100%" height="100%" data="'+window.L._rootUrl+'/common/officeToSwf/FlexPaperViewer.swf" type="application/x-shockwave-flash" '+($.browser.msie&&'classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"')+'><param name="movie" value="'+window.L._rootUrl+'/common/officeToSwf/FlexPaperViewer.swf"><param name="allowfullscreen" value="true"><param name="allowscriptaccess" value="always"><param name="quality" value="high"><param name="allowFullScreenInteractive" value="true"><param name="wmode" value="Opaque"><param name="flashvars" value="SwfFile='+
window.L._adminUrl+"/course/courseware.php?a=getTransUrl%26mediaUrl="+a.replace(/%/g,"=")+'&amp;localeChain=zh_CN"></object>')):window.L.openCom("tip")(window.L.getText("\u60a8\u6240\u9009\u62e9\u7684\u8bfe\u4ef6\u7c7b\u578b\u65e0\u6cd5\u8ba1\u7b97\u5b66\u65f6"))});$("input[name=lectureDiv]").click(function(){var a=$(this).parentsUntil(".tab_title").eq(-1);a.siblings("a").removeClass("current");a.addClass("current");$("#lectureTwoDiv").hide();$("#lectureOneDiv").hide();$("#"+this.value).show();L.extension.pageTable.classObj.initCustomNav(document.getElementById("lectureImgAttPageTable"))});
window.L.openCom("oEditor")&&(new oEditor({buttonList:"bold italic underline left center right justify ol ul fontSize fontFamily fontFormat indent outdent image upload link unlink forecolor bgcolor table subscript superscript strikethrough removeformat hr xhtml".split(" "),CustomConfig:{oFileManager:{quickUploadDir:{img:"/pictures/..quickUpload",media:"/media/..quickUpload",attachment:"/attachment/..quickUpload"},browseDir:{img:"/pictures",media:"/media",attachment:"/attachment"}}}})).panelInstance("lectureText");
var d={onSelectOnce:function(){var a=document.getElementById("lectureText");$("input[name=lectureDiv]").prop("disabled",!0);window.L.openCom("tip")(window.L.getText("\u6b63\u5728\u4e0a\u4f20\u8bf7\u7a0d\u540e"),!1);a.tempUrlList="img"===$(a).attr("coursewareType")?window.L.JSON.parse($(a).val()):[]}};d.onComplete=d.onCancel=function(a){"string"===typeof a&&document.getElementById("lectureText").tempUrlList.push(a.substr((window.browseHome+window.coursewareAttFolder).length));0==$("#lectureImgAttUpload").attr("fileCount")&&
(a=window.L.JSON.stringify(document.getElementById("lectureText").tempUrlList),$("#lectureText").attr("coursewareType","img").val(a),$("input[name=lectureDiv]:checked").parent().parent().siblings().css("fontWeight","normal").end().css("fontWeight","bold"),updateImgPageTable(document.getElementById("lectureImgAttPageTable")),$("input[name=lectureDiv]").prop("disabled",!1),window.L.openCom("tip")())};window.L.openCom("upload")("lectureImgAttUpload",d,"jpg;gif;png",'<font color="#1A5F9B" size="13" >'+
window.L.getText("\u4e0a\u4f20\u56fe\u7247")+"</font>",60,15,{auto:!0,queueID:"lectureUploadProgress",multi:!0,folder:window.coursewareAttFolder});$("#lectureText_Editer").focus(function(){window.temp=this.innerHTML}).blur(function(){this.innerHTML!==window.temp&&($("#lectureText").attr("coursewareType","text"),$("input[name=lectureDiv]:checked").parent().parent().siblings().css("fontWeight","normal").end().css("fontWeight","bold"),updateImgPageTable(document.getElementById("lectureImgAttPageTable")))});
"img"===$("#lectureText").attr("coursewareType")?$("input[name=lectureDiv][value=lectureTwoDiv]").click():$("input[name=lectureDiv][value=lectureOneDiv]").click();$("input[name=lectureDiv]:checked").parent().parent().siblings().css("fontWeight","normal").end().css("fontWeight","bold");$("#save").click(function(){var a={w_id:$("#w_id").val(),w_name:$("#w_name").val(),w_point:$("#w_point").val(),w_credit:$("#w_credit").val(),w_length:$("#coursewareHours").val(),w_type:$("#remoteUrl").attr("coursewareType"),
w_video:$("#remoteUrl").val(),w_source:$("#w_source").attr("w_source_id"),w_category:$("#w_category").attr("w_category_id"),lectureType:$("#lectureText").attr("coursewareType"),tabList:qsnAddTag.tagList};if(""===$.trim(a.w_name))return window.L.openCom("tip")(window.L.getText("\u8bfe\u4ef6\u540d\u79f0\u4e0d\u4e3a\u7a7a")),$("#w_name").focus(),!1;/^\d+$/.test(a.w_credit)||(a.w_credit=0);if(!/^\d+$/.test(a.w_point))return window.L.openCom("tip")(window.L.getText("\u8bfe\u4ef6\u5b66\u5206\u5fc5\u987b\u662f\u6570\u5b57")),
$("#w_point").focus(),!1;if(!/^\d+(?:\.\d+)?$/.test(a.w_length)||"none"!==$("#remoteUrl").attr("coursewareType")&&0>=a.w_length)return window.L.openCom("tip")(window.L.getText("\u8bfe\u4ef6\u5b66\u65f6\u5fc5\u987b\u662f\u5927\u4e8e0\u6570\u5b57,\u5426\u5219\u65e0\u6cd5\u6b63\u786e\u7edf\u8ba1\u5b66\u4e60\u8fdb\u5ea6")),$("#coursewareHours").focus(),!1;if(""===$.trim(a.w_source))return window.L.openCom("tip")(window.L.getText("\u8bfe\u4ef6\u6765\u6e90\u4e0d\u4e3a\u7a7a")),$("#w_source").focus(),!1;
if(""===$.trim(a.w_category))return window.L.openCom("tip")(window.L.getText("\u8bfe\u4ef6\u5206\u7c7b\u4e0d\u4e3a\u7a7a")),$("#w_category").focus(),!1;"img"===a.lectureType?(a.w_des="",a.w_des_h=a.w_des=$("#lectureText").val()):(a.w_des=$("#lectureText").val(),a.w_des_h=$("#lectureText_Editer").html());window.L.openCom("tip")(window.L.getText("\u6b63\u5728\u4fdd\u5b58,\u8bf7\u7a0d\u540e..."),!1,!1,!0);$.post("?a=saveCourseware",a,function(b){if(b==="1"){window.L.openCom("tip")(window.L.getText(a.w_id!==
"0"?"\u64cd\u4f5c\u6210\u529f,\u5373\u5c06\u8df3\u8f6c\u5230\u5217\u8868\u9875":"\u64cd\u4f5c\u6210\u529f,\u5373\u5c06\u5237\u65b0\u9875\u9762"),null,false,true);coursewareObj.beforeUnloadTip.tipState=false;window.setTimeout(function(){window.location.href=a.w_id!=="0"?"?a=modfiyCourseware":window.location.href},1500)}else if(b==="0"){window.L.openCom("tip")(window.L.getText("\u670d\u52a1\u7aef\u5224\u5b9a,\u60a8\u672a\u505a\u4efb\u4f55\u4fee\u6539"));coursewareObj.beforeUnloadTip.tipState=false}else{window.L.openCom("tip")();
window.L.openCom("oDialogDiv")(window.L.getText("\u64cd\u4f5c\u5931\u8d25:"),"text:"+b,"auto","auto",[1])}});return!1});$("#addTag").click(function(){tagDisplayTag({tagType:"6",callbackFn:"qsnAddTag",targetId:"qsn_add_tag_a"});return!1});$("#w_source").click(function(){getTree({targetId:"w_source",callbackFn:function(a,b){$("#w_source").val(b).attr("w_source_id",a)},dataType:"courseware_source",isCheckBox:!1,isExpand:!1,expandLevel:2,showRoot:!1})});$("#w_category").click(function(){getTree({targetId:"w_category",
callbackFn:function(a,b){$("#w_category").val(b).attr("w_category_id",a)},dataType:"courseware_category",isCheckBox:!1,isExpand:!1,expandLevel:2,showRoot:!1})});$(document).keyup(function(){coursewareObj.beforeUnloadTip.tipState=!0});$(window).bind("beforeunload",coursewareObj.beforeUnloadTip)});
