var Paper={searchPaper:function(){var a=$('table[_pagetabledataset="admin_paper_paperCtl::paperPageProcess"]'),c=this.getSearchPaperParam();window.L.extension.pageTable.classObj.params(a.get(0),c,!0)},getSearchPaperParam:function(){var a={},c={create_tm_start:"",create_tm_end:""};a.papr_name=encodeURIComponent($('input[name="papr_name"]').val());a.papr_category=encodeURIComponent($('input[name="papr_category"]').val());a.papr_point=encodeURIComponent($('input[name="papr_point"]').val());a.papr_qsn_count=
encodeURIComponent($('input[name="papr_qsn_count"]').val());a.papr_status=encodeURIComponent($('select[name="papr_status"]').val());c.create_tm_start=$('input[name="create_tm_start"]').val();c.create_tm_end=$('input[name="create_tm_end"]').val();a.dateParam=c;return a},resetSearchPaper:function(){$('input[name="papr_name"]').val("");$('a[name="papr_category_name"]').html(window.L.getText("\u8bf7\u9009\u62e9"));$('input[name="papr_category"]').val("");$('input[name="papr_point"]').val("");$('input[name="papr_qsn_count"]').val("");
$('select[name="papr_status"]').val("0");$('input[name="create_tm_start"]').val("");$('input[name="create_tm_end"]').val("")},savePaper:function(){var a="",c="",d="",e={},a=!0,f="",g="",a=this.verifyPaperFields();if(!a)return!1;a=this.verifyPaperQuestionTypeFields();if(!a)return!1;f=$("#paper_id").val();g=$("#extract_flag").val();a=this.getPaperParam();c=this.getPaperQuestionTypeParam();d=this.getPaperTagParam();e.paperId=f;e.extract_flag=g;e.paperParam=a;e.paperQuestionTypeParam=c;e.paperTagParam=
d;$.ajax({type:"post",url:window.L._adminUrl+"/paper/paperCtl.php?a=ajaxSavePaper",data:e,dataType:"json",error:function(){},beforSend:function(){window.L.openCom("tip")(window.L.getText("\u64cd\u4f5c\u4e2d\uff0c\u8bf7\u7a0d\u5019..."))},success:function(a){"0"==a.flag?window.L.openCom("tip")(a.info):window.L.openCom("tip")(window.L.getText("\u4fdd\u5b58\u6210\u529f"))}})},verifyPaperFields:function(){return""==$("#papr_name").val()?(window.L.openCom("tip")(window.L.getText("\u8bd5\u5377\u540d\u79f0\u4e0d\u80fd\u4e3a\u7a7a")),
$("#papr_name").focus(),!1):""==$("#papr_category").val()?(window.L.openCom("tip")(window.L.getText("\u8bf7\u9009\u62e9\u8bd5\u5377\u5206\u7c7b")),$("#papr_category").focus(),!1):!0},getPaperParam:function(){var a={},c="",c="0"==$('input[name="paper_type"]:checked').val()?"020301":$('select[name="random_type"]').val();a.papr_type=c;a.papr_status=$('input[name="papr_status"]:checked').val();a.papr_name=$("#papr_name").val();a.papr_des=$("#papr_des").val();a.papr_category=$("#papr_category").val();
return a},verifyPaperQuestionTypeFields:function(){var a=!0,c="",d="",e="",f=$('input[name="paper_type"]:checked').val(),a=a=a="";switch(f){case "0":e="generalPaperQuestionType";break;case "1":e="randomPaperQuestionType";break;default:e="generalPaperQuestionType"}if(1>$("#"+e).find("tbody").find("tr").length)return window.L.openCom("tip")(window.L.getText("\u8bf7\u4e3a\u8bd5\u5377\u6dfb\u52a0\u9898\u578b")),!1;for(var g=0;g<$("#"+e).find("tbody").find("tr").length;g++){c=$("#"+e).find("tbody").find("tr").eq(g);
a=c.find('input[name="qsn_type_title"]').val();if(""==a)return window.L.openCom("tip")(window.L.getText("\u8bf7\u8bbe\u7f6e\u9898\u578b\u6807\u9898")),c.find('input[name="qsn_type_title"]').focus(),!1;a=c.find('input[name="qsn_point"]').val();if(""==a)return window.L.openCom("tip")(window.L.getText("\u8bf7\u8bbe\u7f6e\u9898\u578b\u5206\u6570")),c.find('input[name="qsn_point"]').focus(),!1;a=c.find('input[name="qsn_type_qsn_category"]').val();if(""==a)return window.L.openCom("tip")(window.L.getText("\u8bf7\u8bbe\u7f6e\u9898\u578b\u5206\u7c7b")),
c.find('input[name="qsn_type_qsn_category"]').focus(),!1;if("1"==f){for(var a=!0,j=0;j<c.find("input[name^=qsn_level]").length;j++)if(d=c.find("input[name^=qsn_level]").eq(j),""!=d.val()&&(a=!1),""!=d.val()&&(isNaN(parseInt(d.val()))||1>parseInt(d.val())))return window.L.openCom("tip")(window.L.getText("\u62bd\u53d6\u8bd5\u9898\u7684\u6570\u91cf\u5fc5\u987b\u662f\u6b63\u6574\u6570")),d.focus(),!1;if(a)return window.L.openCom("tip")(window.L.getText("\u8bf7\u8bbe\u7f6e\u8981\u62bd\u53d6\u7684\u8bd5\u9898\u6570\u91cf")),
c.find("input[name^=qsn_level]").eq(0).focus(),!1}}return!0},getPaperQuestionTypeParam:function(){var a={};switch($('input[name="paper_type"]:checked').val()){case "0":a=this.getGeneralPaperQuestionTypeParam();break;case "1":a=this.getRandomPaperQuestionTypeParam();break;default:a=this.getGeneralPaperQuestionTypeParam()}return a},getGeneralPaperQuestionTypeParam:function(){for(var a={},c="",d="",e="",f="",g="",j="",i=0,o=$("#generalPaperQuestionType").find("tbody").find("tr"),g="",h=0;h<o.length;h++)g=
o.eq(h),c=g.find('input[name="qsn_point"]').val(),d=g.find('input[name="qsn_type"]').val(),e=g.find('input[name="qsn_type_title"]').val(),f="",i=g.find('input[name="qsn_type_position_new"]').val(),g=g.find('input[name="qsn_type_position"]').val(),"0"==g&&(g=i),j="",a[h]={},a[h].qsn_point=c,a[h].qsn_type=d,a[h].qsn_type_title=e,a[h].qsn_type_label=f,a[h].qsn_type_position_new=i,a[h].qsn_type_position=g,a[h].qsn_type_qsn_category=j;return a},getRandomPaperQuestionTypeParam:function(){for(var a={},c=
"",d="",e="",f="",g="",j="",i="",o=0,h="",m=$("#randomPaperQuestionType").find("tbody").find("tr"),n=h="",k=0;k<m.length;k++){h=m.eq(k);c=h.find('input[name="qsn_point"]').val();d=h.find('input[name="qsn_type"]').val();e=h.find('input[name="qsn_type_title"]').val();f=h.find('input[name="qsn_type_label"]').val();o=h.find('input[name="qsn_type_position_new"]').val();g=h.find('input[name="qsn_type_position"]').val();"0"==g&&(g=o);for(var j=h.find('input[name="qsn_type_qsn_category"]').val(),i={},n=h.find('input[name^="qsn_level"]'),
l=0;l<n.length;l++)if(!(0==l&&""==n.eq(l).val())){if(0==l&&""!=n.eq(l).val()){h=parseInt(n.eq(l).val());i["0"]=h;break}if(""!=n.eq(l).val())switch(h=parseInt(n.eq(l).val()),l){case 1:i["010201"]=h;break;case 2:i["010202"]=h;break;case 3:i["010203"]=h;break;case 4:i["010204"]=h;break;case 5:i["010205"]=h;break;case 6:i["010206"]=h;break;default:i["010201"]=h}}a[k]={};a[k].qsn_point=c;a[k].qsn_type=d;a[k].qsn_type_title=e;a[k].qsn_type_label=f;a[k].qsn_type_position_new=o;a[k].qsn_type_position=g;a[k].qsn_type_qsn_category=
j;a[k].qsn_type_qsn_quantity=i}return a},getPaperTagParam:function(){for(var a=$("#paperTagList").find('span[id^="tag_"]'),c={},d="",e="",d="",f=0;f<a.length;f++)d=a.eq(f),e=d.attr("tag_id"),d=d.attr("tag_name"),c[f]={},c[f].tag_id=e,c[f].tag_name=d;return c},appendPaperQuestionType:function(a,c){var d="",e="",f="",d=$('input[name="paper_type"]:checked').val();$(a).attr("href","javascript:void(0)");switch(d){case "0":d=this.htmlGeneralPaperQuestionType(c);e="generalPaperQuestionType";break;case "1":d=
this.htmlRandomPaperQuestionType(c);e="randomPaperQuestionType";break;default:d=this.htmlGeneralPaperQuestionType(c),e="generalPaperQuestionType"}f=$("#"+e).find("tbody tr:last").find(".icon_up");this.QsnType.isFirst(f)?this.QsnType.showMoveDownBtn(f):this.QsnType.showBothBtn(f);null==f.html()?(f=$("#"+e).find("tbody").append(d).find(".icon_up"),this.QsnType.showMoveDownBtn(f)):$("#"+e).find("tbody").append(d);$(".table1 tr:odd").removeAttr("class").addClass("odd_bg");$(".table1 tr:even").removeAttr("class").addClass("even_bg");
$(".table1").highlight("tbody tr","highlight","mouseover","mouseout")},htmlGeneralPaperQuestionType:function(a){var c="",d="",e="",d=this.QsnType.getMaxQsnTypePosition(),d=d+1;switch(a){case "010101":e=window.L.getText("\u5355\u9009");break;case "010102":e=window.L.getText("\u591a\u9009");break;case "010103":e=window.L.getText("\u5224\u65ad");break;case "010104":e=window.L.getText("\u586b\u7a7a");break;case "010105":e=window.L.getText("\u8ba1\u7b97");break;case "010106":e=window.L.getText("\u95ee\u7b54");
break;case "010107":e=window.L.getText("\u7efc\u5408");break;case "010108":e=window.L.getText("\u5b8c\u5f62\u586b\u7a7a");break;default:e=window.L.getText("\u5355\u9009")}return c+"<tr>"+('<td><a class="icon_up" href="#" title="\u4e0a\u79fb" onclick="Paper.QsnType.moveUp(this)"></a><a class="icon_down hidden" href="#" title="\u4e0b\u79fb" onclick="Paper.QsnType.moveDown(this)"></a><a class="icon_del" title="\u5220\u9664\u9898\u578b" onclick="Paper.removePaperQuestionType(this)"></a><input type="hidden" name="qsn_type_position_new" value="'+
d+'" /><input type="hidden" name="qsn_type_position" value="0" /></td>')+("<td>"+e+'<input type="hidden" name="qsn_type" value="'+a+'" /></td>')+'<td><input class="input2 auto_width" type="text" value="" name="qsn_type_title"></td><td><input class="input2 auto_width" type="text" value="" name="qsn_point"></td><td class="action"><div class="action_toolbar"><div class="inner"><div class="right"></div><div class="inner_box"><div class="action_link"><a class="iframe" title="\u65b0\u589e\u8bd5\u9898" href="dialog/dialog_disable.html">\u65b0\u589e\u8bd5\u9898</a><a class="iframe" title="\u9009\u62e9\u8bd5\u9898" href="dialog/dialog_disable.html">\u9009\u62e9\u8bd5\u9898</a><a class="iframe" title="\u5220\u9664\u8bd5\u9898" href="dialog/dialog_disable.html">\u5220\u9664\u8bd5\u9898</a><a class="iframe" title="\u8bd5\u9898\u6392\u5e8f" href="dialog/dialog_delete.html">\u8bd5\u9898\u6392\u5e8f</a></div></div></div></div></td></tr>'},
htmlRandomPaperQuestionType:function(a){var c="",d="",e="",d=this.QsnType.getMaxQsnTypePosition(),d=d+1;switch(a){case "010101":e="\u5355\u9009";break;case "010102":e="\u591a\u9009";break;case "010103":e="\u5224\u65ad";break;case "010104":e="\u586b\u7a7a";break;case "010105":e="\u8ba1\u7b97";break;case "010106":e="\u95ee\u7b54";break;case "010107":e="\u7efc\u5408";break;case "010108":e="\u5b8c\u5f62\u586b\u7a7a";break;default:e="\u5355\u9009"}return c+"<tr>"+('<td><a class="icon_up" href="#" title="\u4e0a\u79fb" onclick="Paper.QsnType.moveUp(this)"></a><a class="icon_down hidden" href="#" title="\u4e0b\u79fb"onclick="Paper.QsnType.moveDown(this)"></a><a class="icon_del" title="\u5220\u9664\u9898\u578b" onclick="Paper.removePaperQuestionType(this)"><input type="hidden" name="qsn_type_position_new" value="'+
d+'" /><input type="hidden" name="qsn_type_position" value="0" /></td>')+("<td>"+e+'<input type="hidden" name="qsn_type" value="'+a+'" /></td>')+'<td><input class="input2 auto_width" type="text" value="" name="qsn_type_title"></td><td><input class="input2 auto_width" type="text" value="" name="qsn_point"></td><td>'+('<a name="qsn_type_qsn_category_name" id = "qsn_type_qsn_category_name_'+d+'" href="#" onclick="javascript:paprQsnTypeCategoryTreeShow(\'qsn_type_qsn_category_name_'+d+"','qsn_type_qsn_category_"+
d+"');return false;\">\u8bf7\u9009\u62e9\u5206\u7c7b</a>")+('<input class="input2 auto_width" type="hidden" name="qsn_type_qsn_category" id="qsn_type_qsn_category_'+d+'" value="">')+"</td>"+('<td width="300"><dd><a class="icon_go" href="#" id="selectTag_'+d+'" onclick="Paper.paperTagShow(selectTag, this)"></a><input class="input3 auto_width" type="text" value="" name="qsn_type_label_name" id="qsn_type_label_name_'+d+'" readonly /><input class="input3 auto_width" type="hidden" value="" name="qsn_type_label" id="qsn_type_label_id_'+
d+'" /></dd></td>')+'<td class="align_center"><input class="input1 auto_width" type="text" name="qsn_level_0" value="" title="\u53ef\u62bd\u53d6\u9898\u6570:0" />/<span name="qsnQty_level_0">0</span></td><td class="align_center"><input class="input1 auto_width" type="text" name="qsn_level_1" value="" title="\u53ef\u62bd\u53d6\u9898\u6570:0" />/<span name="qsnQty_level_1">0</span></td><td class="align_center"><input class="input1 auto_width" type="text" name="qsn_level_2" value="" title="\u53ef\u62bd\u53d6\u9898\u6570:0" />/<span name="qsnQty_level_2">0</span></td><td class="align_center"><input class="input1 auto_width" type="text" name="qsn_level_3" value="" title="\u53ef\u62bd\u53d6\u9898\u6570:0" />/<span name="qsnQty_level_3">0</span></td><td class="align_center"><input class="input1 auto_width" type="text" name="qsn_level_4" value="" title="\u53ef\u62bd\u53d6\u9898\u6570:0" />/<span name="qsnQty_level_4">0</span></td><td class="align_center"><input class="input1 auto_width" type="text" name="qsn_level_5" value="" title="\u53ef\u62bd\u53d6\u9898\u6570:0" />/<span name="qsnQty_level_5">0</span></td><td class="align_center"><input class="input1 auto_width" type="text" name="qsn_level_6" value="" title="\u53ef\u62bd\u53d6\u9898\u6570:0" />/<span name="qsnQty_level_6">0</span></td></tr>'},
removePaperQuestionType:function(a){var c=0,d="",e="";if(!confirm("\u60a8\u786e\u8ba4\u5220\u9664\u6b64\u9898\u578b\u5417\uff1f"))return!1;this.QsnType.isFirst(a)&&(d=$(a).parents("tr").next().find(".icon_up"),this.QsnType.showMoveDownBtn(d));this.QsnType.isLast(a)&&(d=$(a).parents("tr").prev().find(".icon_down"),this.QsnType.isFirst(d)||this.QsnType.showMoveUpBtn(d));$(a).attr("href","javascript:void(0)");$(a).parents("tr").nextAll().each(function(){c=parseInt($(this).find('input[name="qsn_type_position_new"]').val());
c=c-1;$(this).find('input[name="qsn_type_position_new"]').val(c);e=$(this).attr("class");e=="even_bg"&&$(this).attr("class","odd_bg");e=="odd_bg"&&$(this).attr("class","even_bg")}).end().remove();""!=$("#paper_id").val()&&Paper.ajaxDeletePaperQuestionType(a)},ajaxDeletePaperQuestionType:function(a){var c={};c.paperQuestionTypeParam=this.getDeletePaperQuestionTypeParam(a);$.ajax({type:"post",url:window.L._adminUrl+"/paper/paperCtl.php?a=ajaxDeletePaperQuestionType",data:c,dataType:"html",error:function(){},
beforSend:function(){window.L.openCom("tip")("\u64cd\u4f5c\u4e2d\uff0c\u8bf7\u7a0d\u5019...")},success:function(a){"1"==a?window.L.openCom("tip")("\u64cd\u4f5c\u6210\u529f"):window.L.openCom("tip")(a)}})},getDeletePaperQuestionTypeParam:function(a){var c="",d="",e="",f="",f="";"undefined"!=typeof a&&(f=$(a).parents("tr"),d=encodeURIComponent($("#paper_id").val()),e=encodeURIComponent(f.find('input[name="qsn_type"]').val()),f=encodeURIComponent(f.find('input[name="qsn_type_position"]').val()),c+="paper_id:"+
d+",qsn_type:"+e+",qsn_type_position:"+f);return c},updatePaper:function(a){var c=window.L._adminUrl+"/paper/paperCtl.php?a=addPaper",d="&id="+$(a).parents("tr").find('input[id^="paper_"]').val();$(a).attr("href",c+d)},deletePaper:function(a,c){var d="",e="",f={},g="",j="";if(0==c)hint="\u60a8\u786e\u8ba4\u8981\u5220\u9664\u8bd5\u5377\u5417\uff1f";else{e=$("#paper").find("table tbody tr").find('input[id^="paper_"]:checked').length;if(0>=e)return window.L.openCom("tip")("\u8bf7\u9009\u62e9\u8981\u5220\u9664\u7684\u8bd5\u5377"),
!1;hint="\u60a8\u786e\u8ba4\u8981\u5220\u9664\u9009\u4e2d\u7684\u8bd5\u5377\u5417\uff1f"}b=window.confirm(hint);if(!b)return!1;$(a).attr("href","javascript:void(0)");if(0==c)j=encodeURIComponent($(a).parents("tr").find('input[id^="paper_"]').val()),g="papr_id:"+j;else{for(var d=$("#paper").find("table tbody tr"),e=d.find('input[id^="paper_"]:checked').length,i=0;i<e;i++)j=encodeURIComponent(d.find('input[id^="paper_"]:checked').eq(i).val()),g+="papr_id:"+j+",";g=g.substr(0,g.length-1)}f.paperParam=
g;$.ajax({type:"post",url:window.L._adminUrl+"/paper/paperCtl.php?a=ajaxDeletePaper",data:f,error:function(){},beforeSend:function(){},success:function(a){"1"==a?window.L.openCom("tip")("\u5220\u9664\u6210\u529f"):window.L.openCom("tip")(a);Paper.searchPaper()}})},getAllowExtractQuantity:function(){var a="",c={},d={},e=a="",f="",a=$('input[name="paper_type"]:checked').val(),a=0!=a?$('select[name="random_type"]').val():"";if(""!=a)for(var g=$("#randomPaperQuestionType").find("tbody tr"),j=0;j<g.length;j++)a=
g.eq(j).find('input[name="qsn_type"]').val(),e=g.eq(j).find('input[name="qsn_type_qsn_category"]').val(),f=g.eq(j).find('input[name="qsn_type_label"]').val(),d[j]={},d[j].qsn_type=a,d[j].qsn_type_qsn_category=e,d[j].qsn_type_label=f;c.paperQuestionTypeParam=d;$.ajax({type:"post",url:window.L._adminUrl+"/paper/paperCtl.php?a=ajaxGetAllowExtractQuantity",data:c,dataType:"json",error:function(){},beforeSend:function(){},success:function(a){""!=a?Paper.setExtractQuantity(a):window.L.openCom("tip")("\u64cd\u4f5c\u5931\u8d25")}})},
setExtractQuantity:function(a){var c,d={};for(c=0;c<a.length;c++)d[c]=a[c];random_type=$('input[name="paper_type"]:checked').val();random_type=0!=random_type?$('select[name="random_type"]').val():"";if(""!=random_type){a=$("#randomPaperQuestionType").find("tbody tr").length;for(c=0;c<a;c++)$("#randomPaperQuestionType").find("tbody tr").eq(c).find('span[name="qsnQty_level_0"]').html(d[c][0]),$("#randomPaperQuestionType").find("tbody tr").eq(c).find('span[name="qsnQty_level_1"]').html(d[c][1]),$("#randomPaperQuestionType").find("tbody tr").eq(c).find('span[name="qsnQty_level_2"]').html(d[c][2]),
$("#randomPaperQuestionType").find("tbody tr").eq(c).find('span[name="qsnQty_level_3"]').html(d[c][3]),$("#randomPaperQuestionType").find("tbody tr").eq(c).find('span[name="qsnQty_level_4"]').html(d[c][4]),$("#randomPaperQuestionType").find("tbody tr").eq(c).find('span[name="qsnQty_level_5"]').html(d[c][5]),$("#randomPaperQuestionType").find("tbody tr").eq(c).find('span[name="qsnQty_level_6"]').html(d[c][6])}},deletePaperQuestionView:function(a){var c="",d={},e=$(a).parents("tr");Paper.elem=a;d.paper_id=
$("#paper_id").val();d.qsn_type=e.find('input[name="qsn_type"]').val();d.qsn_type_position=e.find('input[name="qsn_type_position"]').val();$.ajax({async:!1,type:"post",url:window.L._adminUrl+"/paper/paperCtl.php?a=ajaxDeletePaperQuestionView",data:d,error:function(){},beforeSend:function(){},success:function(a){c=a}});window.L.openCom("oDialogDiv")("\u5220\u9664\u8bd5\u5377\u8bd5\u9898","text:"+c,"auto","auto",[2,function(a){var c=!1,c="";if(a){c=Paper.getDeletePaperQuestionParam();if(""==c)return window.L.openCom("tip")("\u8bf7\u9009\u62e9\u8981\u5220\u9664\u7684\u8bd5\u5377\u8bd5\u9898"),
!1;if(c=confirm("\u60a8\u786e\u8ba4\u8981\u5220\u9664\u9009\u4e2d\u6570\u636e\u5417\uff1f"))Paper.ajaxDeletePaperQuestionByQsnPk();else return!1}}],null,!1);window.L.strVar("L.extension.pageTable.init")()},ajaxDeletePaperQuestionByQsnPk:function(){var a={},c="",c=Paper.getDeletePaperQuestionParam();a.paperQuestionParam=c;$.ajax({async:!1,type:"post",url:window.L._adminUrl+"/paper/paperCtl.php?a=ajaxDeletePaperQuestionByQsnPk",data:a,error:function(){},beforeSend:function(){window.L.openCom("tip")("\u64cd\u4f5c\u4e2d\uff0c\u8bf7\u7a0d\u5019...")},
success:function(a){"1"==a?window.L.openCom("tip")("\u64cd\u4f5c\u6210\u529f"):window.L.openCom("tip")("\u64cd\u4f5c\u5931\u8d25");Paper.deletePaperQuestionView(Paper.elem)}})},getDeletePaperQuestionParam:function(){for(var a="",c="",d="",c=$('input[id^="paper_qsn_pk_"]:checked'),e=0;e<c.length;e++)d=c.eq(e).attr("id"),d=d.replace("paper_qsn_pk_","").split("_"),a+="papr_id:"+d[0]+",qsn_type:"+d[1]+",qsn_type_position:"+d[2]+",qsn_id:"+d[3]+",qsn_sub_id:"+d[4],a+="|";""!=a&&(a=a.substr(0,a.length-
1));return a},paperQuestionSortView:function(a){var c="",d={},e=$(a).parents("tr");Paper.elem=a;d.paper_id=$("#paper_id").val();d.qsn_type=e.find('input[name="qsn_type"]').val();d.qsn_type_position=e.find('input[name="qsn_type_position"]').val();$.ajax({async:!1,type:"post",url:window.L._adminUrl+"/paper/paperCtl.php?a=ajaxPaperQuestionSortView",data:d,error:function(){},beforeSend:function(){},success:function(a){c=a}});window.L.openCom("oDialogDiv")("\u8bd5\u5377\u8bd5\u9898\u6392\u5e8f","text:"+
c,"auto","auto",[1],null,!1);window.L.strVar("L.extension.pageTable.init")()},ajaxPaperQuestionSort:function(){var a={},c="";$("#paperQuestionSort").find("table tbody tr");c=Paper.getPaperQuestionSortParam();a.paperQuestionParam=c;$.ajax({async:!1,type:"post",url:window.L._adminUrl+"/paper/paperCtl.php?a=ajaxPaperQuestionSort",data:a,dataType:"html",error:function(){},beforeSend:function(){window.L.openCom("tip")("\u64cd\u4f5c\u4e2d\uff0c\u8bf7\u7a0d\u5019...")},success:function(a){"1"==a?window.L.openCom("tip")("\u64cd\u4f5c\u6210\u529f"):
window.L.openCom("tip")("\u64cd\u4f5c\u5931\u8d25")}})},getPaperQuestionSortParam:function(){for(var a="",c="",d="",e=0,c=$("#paperQuestionSort").find("table tbody tr"),f=0;f<c.length;f++)e=c.eq(f).find('input[name^="qsn_position"]').val(),d=c.eq(f).find('input[id^="paper_qsn_pk_"]').attr("id"),d=d.replace("paper_qsn_pk_","").split("_"),a+="papr_id:"+d[0]+",qsn_type:"+d[1]+",qsn_type_position:"+d[2]+",qsn_id:"+d[3]+",qsn_sub_id:"+d[4]+",qsn_position:"+e,a+="|";""!=a&&(a=a.substr(0,a.length-1));return a},
clonePaper:function(a,c){var d={},e="",f="",f=!0,f=0;if(0==c)f="\u60a8\u786e\u8ba4\u8981\u590d\u5236\u8bd5\u5377\u5417\uff1f";else{f=$("#paper").find("table tbody tr").find('input[id^="paper_"]:checked').length;if(0>=f)return window.L.openCom("tip")("\u8bf7\u9009\u62e9\u8981\u590d\u5236\u7684\u8bd5\u5377"),!1;f="\u60a8\u786e\u8ba4\u8981\u590d\u5236\u9009\u4e2d\u7684\u8bd5\u5377\u5417\uff1f"}f=window.confirm(f);if(!f)return!1;$(a).attr("href","javascript:void(0)");if(0==c)e=$(a).parents("tr").find('input[id^="paper_"]').val();
else{elem_tr=$("#paper").find("table tbody tr");for(var f=elem_tr.find('input[id^="paper_"]:checked').length,g=0;g<f;g++)e+=elem_tr.find('input[id^="paper_"]:checked').eq(g).val()+",";e=e.substr(0,e.length-1)}d.paperParam=e;$.ajax({async:!1,type:"post",url:window.L._adminUrl+"/paper/paperCtl.php?a=ajaxClonePaper",data:d,dataType:"html",error:function(){},beforeSend:function(){window.L.openCom("tip")("\u64cd\u4f5c\u4e2d\uff0c\u8bf7\u7a0d\u5019...")},success:function(a){"1"==a?window.L.openCom("tip")("\u64cd\u4f5c\u6210\u529f"):
window.L.openCom("tip")("\u64cd\u4f5c\u5931\u8d25");Paper.searchPaper()}})},exportPaper:function(a){$(a).attr("href","javascript:void(0)");a=$(a).parents("tr").find('input[id^="paper_"]').val();if("undefined"==typeof a)return!1;window.open(window.L._adminUrl+"/paper/paperCtl.php?a=exportPaper&id="+a)},selectPaper:function(a,c){var d={},e={},f={};e.a="ajaxSelectPaper";f.excludePaperIds=c||{};d.get=e;d.post=f;d=window.L.JSON.stringify(d);window.L.openCom("oDialogDiv")("\u9009\u62e9\u8bd5\u5377","iframe:"+
window.L._adminUrl+"/paper/paperCtl.php?"+d,"1000","600",[2,{mouseClickFun:function(c,d,e){if(c){var f=$(window.frames["oDialogDiv_iframe_"+e.handle].document),e=f.find('input[id^="paper_"]:checked'),h={};f.find('input[id^="paper_"]:checked').each(function(a){h[a]=f.find('input[id="papr_point_'+$(this).val()+'"]').val()});c=e.length;if(0>=c)return window.L.openCom("tip")("\u8bf7\u9009\u62e9\u8bd5\u5377"),!1;for(var d={},m=0;m<c;m++)d[m]=e.eq(m).val();e={};e.length=c;e.ids=d;e.paprPoints=h;a.call(a,
e)}}}],null,!1)},paperTagShow:function(a,c){var d={},e={},f={},g=$(c).attr("id"),g=g.replace("selectTag_","");tmpTagIds=$("#qsn_type_label_id_"+g).val();tmpTagNames=$("#qsn_type_label_name_"+g).val();tagIds=""!=tmpTagIds?tmpTagIds.split(","):{};e.a="tagShow";f.tag_ids=tagIds;f.tag_names=tmpTagNames;d.get=e;d.post=f;d=window.L.JSON.stringify(d);window.L.openCom("oDialogDiv")("\u9009\u62e9\u8bd5\u5377\u9898\u578b\u6807\u7b7e","iframe:"+window.L._adminUrl+"/paper/paperCtl.php?"+d,"1040","400",[2,{mouseClickFun:function(d,
e,f){d&&(e=$(window.frames["oDialogDiv_iframe_"+f.handle].document),d=e.find("#tag_ids").val(),d=d.substr(0,d.length-1),e=e.find("#tag_names").val(),e=e.substr(0,e.length-1),f={},f.strTagIds=d,f.strTagNames=e,f.eventSourceElem=c,a.call(a,f))}}],null,!1)}};String.prototype.trim=function(){return this.replace(/(^\s*)|(\s*$)/g,"")};String.prototype.ltrim=function(){return this.replace(/(^\s*)/g,"")};String.prototype.rtrim=function(){return this.replace(/(\s*$)/g,"")};
function paprPreviewPaper(a){var c=window.L._adminUrl+"/paper/paperCtl.php?a=previewPaper";window.open(c+("&papr_id="+a))}function paprInitEditPage(){initResetArea({selection:"#papr_params_div",id:"papr_params_div"});paprTypeChange();var a={tableArea:"#normal_papr_tbody",orderMark:"normal_papr_table"};orderInitOrder(a);a={tableArea:"#random_papr_tbody",orderMark:"random_papr_table"};orderInitOrder(a);loadFunctionBar()}
function paprInitManageContentPage(){orderInitOrder({tableArea:"#papr_content_tbody",orderMark:"papr_content_table",showOrderNum:!0})}function paprTypeChange(){var a=$("#papr_type").val();switch(a){case "020301":$("#normal_papr_div").show();$("#random_papr_div").hide();break;default:$("#normal_papr_div").hide(),$("#random_papr_div").show()}return a}PAPR_QSN_TYPE_POSITION={normal:0,random:0};
function paprAddQsnType(a,c){var d="";switch($("#papr_type").val()){case "020301":PAPR_QSN_TYPE_POSITION.normal++;d='<tr id="papr_normal_qsn_type_pos_'+PAPR_QSN_TYPE_POSITION.normal+'" qsn_type_mark="'+PAPR_QSN_TYPE_POSITION.normal+'"><td></td><td>'+c+'<input type="hidden" value="" id="papr_content_'+PAPR_QSN_TYPE_POSITION.normal+'" name="papr_content"/><input type="hidden" value="'+a+'" id="p_qsn_type_'+PAPR_QSN_TYPE_POSITION.normal+'" name="p_qsn_type"/></td><td id="papr_content_count_'+PAPR_QSN_TYPE_POSITION.normal+
'">0</td><td><input class="input2 auto_width" type="text" value="'+c+'" id="qsn_type_title_'+PAPR_QSN_TYPE_POSITION.normal+'" name="qsn_type_title"></td><td><input class="input2 auto_width" type="text" value="0" id="qsn_point_'+PAPR_QSN_TYPE_POSITION.normal+'" name="qsn_point"></td><td><div class="inner"><div class="right"></div><div class="inner_box"><div class="action_link"><a class="iframe" href="javascript:void(0)" onclick="paprModifyContent('+PAPR_QSN_TYPE_POSITION.normal+",'add','"+a+'\');return false;" title="\u6dfb\u52a0\u8bd5\u9898">\u6dfb\u52a0\u8bd5\u9898</a><a class="iframe" href="javascript:void(0)" onclick="paprModifyContent('+
PAPR_QSN_TYPE_POSITION.normal+",'select','"+a+'\');return false;" title="\u9009\u62e9\u8bd5\u9898">\u9009\u62e9\u8bd5\u9898</a><a class="iframe" href="javascript:void(0)" onclick="paprModifyContent('+PAPR_QSN_TYPE_POSITION.normal+",'manage','"+a+'\');return false;" title="\u7ba1\u7406\u8bd5\u9898">\u7ba1\u7406\u8bd5\u9898</a></div></div></div></td></tr>';$("#normal_papr_tbody").append(d);loadFunctionBar();orderResetBtnArea("normal_papr_table");break;default:PAPR_QSN_TYPE_POSITION.random++,d='<tr id="papr_random_qsn_type_pos_'+
PAPR_QSN_TYPE_POSITION.random+'" qsn_type_mark="'+PAPR_QSN_TYPE_POSITION.random+'"><td></td><td>'+c+'<input type="hidden" value="" id="r_papr_content_'+PAPR_QSN_TYPE_POSITION.random+'" name="r_papr_content"/><input type="hidden" value="'+a+'" id="p_r_qsn_type_'+PAPR_QSN_TYPE_POSITION.random+'" name="p_r_qsn_type"/></td><td id="r_papr_content_count_'+PAPR_QSN_TYPE_POSITION.random+'">0</td><td><input class="input2 auto_width" type="text" value="'+c+'" id="r_qsn_type_title_'+PAPR_QSN_TYPE_POSITION.random+
'" name="r_qsn_type_title"></td><td><input class="input2 auto_width" type="text" value="0" id="r_qsn_point_'+PAPR_QSN_TYPE_POSITION.random+'" name="r_qsn_point"></td><td><a href="javascript:void(0)" onclick="paprSelectQsnCategory('+PAPR_QSN_TYPE_POSITION.random+')" id="p_qsn_category_desc_'+PAPR_QSN_TYPE_POSITION.random+'" name="p_qsn_category_desc">\u8bf7\u9009\u62e9\u5206\u7c7b</a><input type="hidden" value="" id="p_qsn_category_'+PAPR_QSN_TYPE_POSITION.random+'" name="p_qsn_category" /></td><td><a href="javascript:void(0)" onclick="paprSelectQsnLevel('+
PAPR_QSN_TYPE_POSITION.random+')" id="p_qsn_level_desc_'+PAPR_QSN_TYPE_POSITION.random+'" name="p_qsn_level_desc">\u8bf7\u9009\u62e9\u96be\u5ea6</a><input type="hidden" value="" id="p_qsn_level_'+PAPR_QSN_TYPE_POSITION.random+'" name="p_qsn_level" /></td></tr>',$("#random_papr_tbody").append(d),orderResetBtnArea("random_papr_table")}}
function paprSelectQsnCategory(a){var c=L.JSON.parse(decodeURIComponent($("#p_qsn_category_"+a).val()));void 0==c&&(c={name:{},id:{}});var d=$("#p_r_qsn_type_"+a).val(),a={targetNameId:"p_qsn_category_desc_"+a,targetValueId:"p_qsn_category_"+a,dataType:"qsn_category",showRoot:!1,treeMark:a,chkboxType:{Y:"",N:""},onCheck:paprQsnCategoryOnCheck,isDiyOnCheck:!1,isCheckBox:!0,checkedId:c.id,enableCheckedId:null!=QSN_TYPE_ALLOW_CATEGORY&&void 0!=QSN_TYPE_ALLOW_CATEGORY[d]?QSN_TYPE_ALLOW_CATEGORY[d]:0,
errorStr:{disableCheck:window.L.getText("\u5f53\u524d\u5206\u7c7b\u4e0b\u6ca1\u6709\u53ef\u7528\u8bd5\u9898\uff0c\u8bf7\u5f55\u5165\u8bd5\u9898\u6216\u4fee\u6539\u8bd5\u9898\u72b6\u6001\u4e3a\u53ef\u7528")}};getTree(a)}
function paprQsnCategoryOnCheck(a){var c=a.treeMark,d=a.name,e=a.id,a=a.checked,f=L.JSON.parse($("#p_qsn_category_"+c).val());if(void 0==f||""==f)f={name:{},id:{},qsn_category_info:{}};a?(f.name[e]=d,f.id[e]=e,f.qsn_category_info[e]={qsn_category:e}):(delete f.name[e],delete f.id[e],delete f.qsn_category_info[e]);var g="";$.each(f.name,function(a,c){g=g+(c+",")});g=g.substring(0,g.length-1);f=L.JSON.stringify(f);""==g&&(g=window.L.getText("\u8bf7\u9009\u62e9\u5206\u7c7b"),f="");$("#p_qsn_category_desc_"+
c).html(g);$("#p_qsn_category_"+c).val(f)}QSN_LEVEL_INFO_LIST={};
function paprSelectQsnLevel(a){var c=$("#p_r_qsn_type_"+a).val(),d=L.JSON.parse($("#p_qsn_category_"+a).val());if(void 0!=d){var e=window.L._adminUrl+"/paper/paperCtl.php?a=getQsnLevel",d="qsn_type="+c+"&qsn_category="+encodeURIComponent(L.JSON.stringify(d.id));$.ajax({type:"POST",async:!1,url:e,data:d,dataType:"json",success:function(d){result=d;if("success"==d.res){$.each(d.info,function(a){d.info[a].selected_qsn_count=0});qsn_level_info=d.info;var e=null,j="",e=L.JSON.parse($("#p_qsn_level_"+a).val());
void 0!=e&&(j=$("#p_r_qsn_type_"+e.qsn_type_pos).val(),j==c&&$.each(e.qsn_level_info,function(a,c){qsn_level_info[a].selected_qsn_count=c.qsn_count}));var i='<table style="margin-top:10px;margin-left:10px;font-size:14px;line-height:1.5;" width="280px" border="0" cellspacing="0" cellpadding="0">';$.each(qsn_level_info,function(a,c){if(parseInt(c.qsn_count)<0)c.qsn_count=0;i=i+('<tr><td width="74" height="35" align="center" valign="middle">'+c.qsn_level_desc+'</td><td width="160" height="35" align="center" valign="middle"><input type="text" value="'+
c.selected_qsn_count+'" name="selected_qsn_count" onclick="$(this).select()" id="selected_qsn_count_'+c.qsn_level+'" qsn_max_count="'+c.qsn_count+'" qsn_level="'+c.qsn_level+'" qsn_level_desc="'+c.qsn_level_desc+'"  style="border:1px solid #CCC;height:25px;line-height:25px;" /></td><td width="20" height="35" align="center" valign="middle">/</td><td width="100" height="35" align="center" valign="middle">'+c.qsn_count+"</td></tr>")});i+='</table><a href="javascript:void(0)" onclick="paprAddQsnLevel('+
a+')" class="btn">\u786e\u5b9a</a><a href="javascript:void(0)" onclick="alertCloseAlertDiv()" class="btn">\u53d6\u6d88</a>';window.L.openCom("oDialogDiv")&&(ALERT_DIV_MARK=oDialogDiv(window.L.getText("\u9009\u62e9\u96be\u5ea6"),"text:"+i,"400px","400px",[1],10,!0))}else oDialogDivInfo(d.info)},error:function(){}})}else oDialogDivInfo(window.L.getText("\u8bf7\u9009\u62e9\u81f3\u5c11\u4e00\u4e2a\u8bd5\u9898\u5206\u7c7b"))}
function paprAddQsnLevel(a){var c="",d={qsn_type_pos:a,qsn_level_info:{}},e="success",f="";$("input[name='selected_qsn_count']").each(function(){if("0"!=$(this).val()&&(c+=$(this).attr("qsn_level_desc")+"("+$(this).val()+"),",d.qsn_level_info[$(this).attr("qsn_level")]={qsn_level:$(this).attr("qsn_level"),qsn_count:parseInt($(this).val()),qsn_type_pos:a},parseInt($(this).val())>parseInt($(this).attr("qsn_max_count"))&&(e="failed",f="\u62bd\u53d6\u6570\u91cf\u4e0d\u80fd\u5927\u4e8e\u8bd5\u9898\u603b\u6570"),
!validPositiveInt($(this).val())))e="failed",f="\u62bd\u53d6\u6570\u91cf\u5fc5\u987b\u4e3a\u6709\u6548\u7684\u6b63\u6574\u6570"});"success"==e?(c=c.substring(0,c.length-1),d=L.JSON.stringify(d),""==c&&(c="\u8bf7\u9009\u62e9\u96be\u5ea6",d=""),$("#p_qsn_level_desc_"+a).html(c),$("#p_qsn_level_"+a).val(d),alertCloseAlertDiv()):oDialogDivInfo(f);paprResetPaprContentCount(a)}
function paprModifyContent(a,c,d){PAPR_TYPE_POS=a;switch(c){case "add":a={qsn_type:d,insert_success:"paprAddContent"};qsnAlertAddQsn(a);break;case "select":var e={},f=null;$("input[name='papr_content']").each(function(){f=L.JSON.parse($(this).val());void 0!=f&&$.each(f,function(a,c){e[c.qsn_id]={qsn_id:c.qsn_id}})});a={qsn_type:d,click_yes:"paprSelectContent",exclude_ids:e};qsnAlertQsnList(a);break;case "manage":var g={},f=null,f=L.JSON.parse($("#papr_content_"+a).val());void 0!=f&&$.each(f,function(a,
c){g[a]={qsn_id:c.qsn_id}});window.L.openCom("oDialogDiv")&&(ALERT_DIV_MARK=oDialogDiv("\u7ba1\u7406\u8bd5\u9898","iframe:"+(window.L._adminUrl+"/paper/paperCtl.php?")+"{'get':{'a':'managePaprContent'}, 'post' : {'include_ids':'"+L.JSON.stringify(g)+"'}}","800px","600px",[1],10,!0))}}
function paprAddContent(a){var c=L.JSON.parse($("#papr_content_"+PAPR_TYPE_POS).val());void 0==c&&(c={});c[a.qsn_id]={qsn_id:a.qsn_id};$("#papr_content_"+PAPR_TYPE_POS).val(L.JSON.stringify(c));paprResetPaprContentCount(PAPR_TYPE_POS)}
function paprSelectContent(a){var c=L.JSON.parse($("#papr_content_"+PAPR_TYPE_POS).val());if(void 0==c||""==c)c={};$.each(a.ids,function(a,e){c[e.qsn_id]={qsn_id:e.qsn_id}});$("#papr_content_"+PAPR_TYPE_POS).val(L.JSON.stringify(c));paprResetPaprContentCount(PAPR_TYPE_POS)}
function paprUpdateContent(){var a={};$("input[name='papr_qsn_content']").each(function(){a[$("#papr_qsn_td_"+$(this).val()).html()]={qsn_id:$(this).val(),qsn_position:$("#papr_qsn_td_"+$(this).val()).html()}});window.parent.paprResetContent(a);window.parent.alertCloseAlertDiv()}function paprResetContent(a){$("#papr_content_"+PAPR_TYPE_POS).val(L.JSON.stringify(a));paprResetPaprContentCount(PAPR_TYPE_POS)}
function paprResetPaprContentCount(a){if("020301"==$("#papr_type").val()){var c=L.JSON.parse($("#papr_content_"+a).val()),d=0;$.each(c,function(){d++});$("#papr_content_count_"+a).html(d)}else{var c=L.JSON.parse($("#p_qsn_level_"+a).val()),e=0;void 0!=c&&$.each(c.qsn_level_info,function(a,c){e+=parseInt(c.qsn_count)});$("#r_papr_content_count_"+a).html(e)}}function paperCategoryTreeShow(a,c,d){getTree({targetNameId:a,targetValueId:c,dataType:"papr_category",showRoot:d?d:!1})}
function paperDisplayTag(){tagDisplayTag({tagType:2,callbackFn:"paperAddTag",targetId:"addTag"})}function paperAddTag(a,c){void 0==$("#papr_tag_"+a).val()&&$("#papr_tag_td").append('<span id="papr_tag_span_'+a+'"><input type="hidden" name="papr_tags" id="papr_tag_'+a+'" value="'+a+'"><a href="javascript:void(0)">'+c+'</a><a class="icon_del" title="\u5220\u9664" href="javascript:void(0)" onclick="paprDelTag(\''+a+"')\"></a></span>")}function paperDelAllTag(){$("#papr_tag_td").html("")}
function paprDelTag(a){$("#papr_tag_span_"+a).remove()}function selectTag(a){var c=$(a.eventSourceElem).attr("id"),c=c.replace("selectTag_","");$("#qsn_type_label_name_"+c).val(a.strTagNames);$("#qsn_type_label_id_"+c).val(a.strTagIds);extractQuestion("qsn_type_label_name_"+c)}
function paprAddOrUpdatePapr(){oDialogDivInfo(window.L.getText("\u64cd\u4f5c\u4e2d..."),3E5);disableBtn("papr_save_btn");var a=paprValidatePaprInfo();if("success"==a.res){var c=paprFormatPaprInfo(),a=window.L._adminUrl+"/paper/paperCtl.php?a=modifyPapr",c="papr_info="+encodeURIComponent(L.JSON.stringify(c));$.ajax({type:"POST",async:!1,url:a,data:c,dataType:"json",success:function(a){if("success"==a.res){var c={};$("input[name='papr_tags']").each(function(a){c[a]=$(this).val()});tagAddTagObj({objId:a.info.papr_id,
tagIds:c,addOrReplace:"replace"});""!=$("#papr_id").val()?oDialogDivInfo(window.L.getText("\u4fee\u6539\u8bd5\u5377\u6210\u529f")):(oDialogDivInfo(window.L.getText("\u6dfb\u52a0\u8bd5\u5377\u6210\u529f")),paprResetAreaParams())}else oDialogDivInfo(a.info);enableBtn("papr_save_btn")},error:function(){oDialogDivInfo(window.L.getText("\u7f51\u7edc\u8fde\u63a5\u51fa\u9519,\u8bf7\u7a0d\u540e\u518d\u8bd5"));enableBtn("papr_save_btn")}})}else oDialogDivInfo(a.info),enableBtn("papr_save_btn")}
function paprModifyPapr(){return result}
function paprValidatePaprInfo(){var a={res:"success",info:""},c=$("#papr_type").val();""==$.trim($("#papr_name").val())&&(a.res="failed",a.info=window.L.getText("\u8bd5\u5377\u540d\u4e0d\u80fd\u4e3a\u7a7a"));switch(c){case "020301":void 0==$("#normal_papr_tbody tr").attr("qsn_type_mark")?(a.res="failed",a.info=window.L.getText("\u8bf7\u81f3\u5c11\u52a0\u5165\u4e00\u9053\u5927\u9898")):(""==$("#papr_category").val()&&(a.res="failed",a.info=window.L.getText("\u8bf7\u9009\u62e9\u8bd5\u5377\u5206\u7c7b")),$('input[name="papr_content"]').each(function(){if($(this).val()==
""){a.res="failed";a.info=window.L.getText("\u8bf7\u81f3\u5c11\u9009\u62e9\u4e00\u9053\u5c0f\u9898")}}),$('input[name="qsn_point"]').each(function(){if(!validPositive($(this).val())){a.res="failed";a.info=window.L.getText("\u5206\u6570\u4e0d\u80fd\u662f\u8d1f\u6570")}}),$('input[name="qsn_type_title"]').each(function(){if($(this).val()==""){a.res="failed";a.info=window.L.getText("\u9898\u578b\u4e0d\u80fd\u4e3a\u7a7a")}}));break;default:void 0==$("#random_papr_tbody tr").attr("qsn_type_mark")?(a.res=
"failed",a.info=window.L.getText("\u8bf7\u81f3\u5c11\u52a0\u5165\u4e00\u9053\u5927\u9898")):(""==$("#papr_category").val()&&(a.res="failed",a.info=window.L.getText("\u8bf7\u9009\u62e9\u8bd5\u5377\u5206\u7c7b")),$('input[name="p_qsn_level"]').each(function(){if($(this).val()==""){a.res="failed";a.info=window.L.getText("\u8bf7\u81f3\u5c11\u62bd\u53d6\u4e00\u9053\u8bd5\u9898")}}),$('input[name="p_qsn_category"]').each(function(){if($(this).val()==""){a.res="failed";a.info=window.L.getText("\u8bf7\u9009\u62e9\u8bd5\u9898\u5206\u7c7b")}}),
$('input[name="r_qsn_point"]').each(function(){if(!validPositive($(this).val())){a.res="failed";a.info=window.L.getText("\u5206\u6570\u4e3a\u4e00\u4e2a\u975e\u8d1f\u6570")}}),$('input[name="r_qsn_type_title"]').each(function(){if($(this).val()==""){a.res="failed";a.info=window.L.getText("\u9898\u578b\u6807\u9898\u4e0d\u80fd\u4e3a\u7a7a")}}))}return a}
function paprFormatPaprInfo(){var a={papr_id:$.trim($("#papr_id").val()),papr_name:$.trim($("#papr_name").val()),papr_type:$("#papr_type").val(),papr_des:$("#papr_des").val(),papr_category:$("#papr_category").val(),papr_status:$("#papr_status").val(),papr_point:0,papr_qsn_count:0,papr_all_qsn_count:0,papr_qsn_type:{}};"020301"==a.papr_type?$("#normal_papr_tbody tr").each(function(c){var d=$(this).attr("qsn_type_mark"),e=$("#p_qsn_type_"+d).val(),f=parseFloat($("#qsn_point_"+d).val());a.papr_qsn_type[c+
1]={qsn_point:f,qsn_type_title:$("#qsn_type_title_"+d).val(),qsn_type:e,qsn_type_position:c+1,papr_qsn_content:{},qsn_type_label:""};var d=L.JSON.parse($("#papr_content_"+d).val()),g=1;$.each(d,function(d,i){a.papr_qsn_type[c+1].papr_qsn_content[g]={qsn_id:i.qsn_id,qsn_sub_id:0,qsn_type_position:c+1,qsn_position:g,qsn_type:e,qsn_point:f};a.papr_qsn_count++;g++});a.papr_point+=(g-1)*f}):$("#random_papr_tbody tr").each(function(c){var d=$(this).attr("qsn_type_mark"),e=$("#p_r_qsn_type_"+d).val(),f=
parseFloat($("#r_qsn_point_"+d).val()),g=L.JSON.parse($("#p_qsn_level_"+d).val()),j=L.JSON.parse($("#p_qsn_category_"+d).val());a.papr_qsn_type[c+1]={qsn_point:f,qsn_type_title:$("#r_qsn_type_title_"+d).val(),qsn_type:e,qsn_type_position:c+1,papr_qsn_content:{},qsn_type_label:"",papr_qsn_level:g.qsn_level_info,papr_qsn_category:j.qsn_category_info};var i=0;void 0!=g&&$.each(g.qsn_level_info,function(a,c){i+=parseInt(c.qsn_count)});a.papr_qsn_count+=i;a.papr_point+=i*f});return a}
function paprResetAreaParams(){resetArea("papr_params_div");PAPR_QSN_TYPE_POSITION={normal:0,random:0};paprInitEditPage()};
