$(function(){$('input[name="paper_type"]').click(function(){var a=!1,a="";switch($(this).val()){case "0":$("#generalPaperQuestionType").show();$("#randomPaperQuestionType").hide();a=!1;break;case "1":$("#generalPaperQuestionType").hide();$("#randomPaperQuestionType").show();a=!0;break;default:$("#generalPaperQuestionType").show(),$("#randomPaperQuestionType").hide(),a=!1}a?(a=$('select[name="random_type"]').attr("class"),a=a.replace(" disable",""),$('select[name="random_type"]').attr("class",a),$('select[name="random_type"]').removeAttr("disabled")):
(a=$('select[name="random_type"]').attr("class"),a=a.replace(" disable",""),$('select[name="random_type"]').attr("class",a+" disable"),$('select[name="random_type"]').attr("disabled","disabled"))});$("#paper_id").val()&&($(".table1 tbody tr").hover(function(){$(".action_toolbar",this).show().animate({marginLeft:"8px"},{queue:!1,duration:200})},function(){$(".action_toolbar",this).hide().animate({marginLeft:"10px"},{queue:!1,duration:200})}),"0"==$('input[name="paper_type"]:checked').val()?($("#generalPaperQuestionType").show(),
$("#randomPaperQuestionType").hide()):($("#randomPaperQuestionType").show(),$("#generalPaperQuestionType").hide()),$('input[name="paper_type"]').attr("disabled",!0),$('select[name="random_type"]').attr("disabled",!0));$("#close").click(function(){$(this).attr("href","javascript:void(0)");window.location.href=window.L._adminUrl+"/paper/paperCtl.php"});$("#preview").click(function(){$(this).attr("href","javascript:void(0)");var a=$("#paper_id").val();if(a==""){window.L.openCom("tip")("\u8bf7\u5148\u4fdd\u5b58\u8bd5\u5377\u540e\u9884\u89c8");
return false}window.location.href=window.L._adminUrl+"/paper/paperCtl.php?a=show&id="+a});var b={};$("#generalPaperQuestionType").find("tbody").find('a[class^="icon_up"]').click(function(){b={position:-1,elemNameForPos:"qsn_type_position_new"};moveTr(b,this)});$("#generalPaperQuestionType").find("tbody").find('a[class^="icon_down"]').click(function(){b={position:1,elemNameForPos:"qsn_type_position_new"};moveTr(b,this)})});
function save(){$(this).attr("href","javascript:void(0)");Paper.savePaper()}function extract(){$("#extract_flag").val("1");Paper.getAllowExtractQuantity()}function appendQsnPaprType(b,a,c){Paper.QsnType.setConfig(c);Paper.appendPaperQuestionType(b,a)}function moveTr(b,a){Paper.QsnType.setConfig(b);Paper.QsnType.move(b,a)}var paper_qsn_type_elem="",paper_qsn_insert_flag="";
function insertQsn(b){paper_qsn_type_elem=b;paper_qsn_insert_flag=1;var a="",a=$(b).parents("tr").find('input[name="qsn_type"]').val();qsnAlertAddQsn({qsn_type:a,insert_success:"ajaxInsertPaperQuestion"})}function selectQsn(b){paper_qsn_type_elem=b;paper_qsn_insert_flag=2;var a="",c={},c=getExcludeIds(),c=window.L.JSON.parse(c),a=$(b).parents("tr").find('input[name="qsn_type"]').val();qsnAlertQsnList({qsn_type:a,click_yes:"ajaxInsertPaperQuestion",exclude_ids:c})}
function ajaxInsertPaperQuestion(b){var a={},c=$(paper_qsn_type_elem).parents("tr"),e=$("#paper_id").val(),d=c.find('input[name="qsn_type"]').val(),c=c.find('input[name="qsn_type_position"]').val();a.paperQuestionParam=b;a.paper_id=e;a.qsn_type=d;a.qsn_type_position=c;a.paper_qsn_insert_flag=paper_qsn_insert_flag;$.ajax({type:"post",url:window.L._adminUrl+"/paper/paperCtl.php?a=ajaxInsertPaperQuestion",data:a,dataType:"html",error:function(){},beforeSend:function(){},success:function(){}})}
function getExcludeIds(){var b={},a={},c=$(paper_qsn_type_elem).parents("tr"),e=$("#paper_id").val(),d=c.find('input[name="qsn_type"]').val(),c=c.find('input[name="qsn_type_position"]').val();a.paper_id=e;a.qsn_type=d;a.qsn_type_position=c;$.ajax({async:!1,type:"post",url:window.L._adminUrl+"/paper/paperCtl.php?a=ajaxGetExcludeIds",data:a,dataType:"html",error:function(){},beforeSend:function(){},success:function(a){b=a}});return b}
function deletePaperQuestion(b){Paper.deletePaperQuestionView(b)}function paperQuestionSort(b){Paper.paperQuestionSortView(b)}function paprQsnTypeCategoryTreeShow(b,a,c){var e={},d=[];elemQsnCategoryNameId=b;elemQsnCategoryId=a;for(var d=$("#"+elemQsnCategoryId).val().split(","),f=0;f<d.length;f++)e[f]=d[f];getTree({targetNameId:b,targetValueId:a,dataType:"qsn_category",showRoot:c?c:!1,treeMark:b,chkboxType:{Y:"",N:""},onCheck:zTreeOnCheck,isCheckBox:!0,checkedId:e})}
function zTreeOnCheck(){for(var b=elemQsnCategoryNameId.substr(elemQsnCategoryNameId.lastIndexOf("_")),a=$("#qsn_type_qsn_category_name"+b),c=$("#qsn_type_qsn_category"+b),e="",d="",f=$.fn.zTree.getZTreeObj("treeListqsn_categorytrueqsn_type_qsn_category_name"+b).getCheckedNodes(!0),g=0,h=f.length;g<h;g++)e+=f[g].name+",",d+=f[g].id+",";e=0<e.length?e.substring(0,e.length-1):"\u8bf7\u9009\u62e9\u5206\u7c7b";d=0<d.length?d.substring(0,d.length-1):"";a.html(e);c.val(d);extractQuestion("qsn_type_qsn_category_name"+
b)}
function extractQuestion(b){var a=$("#"+b).parents("tr"),c=b="",e="",d={},f={},b=a.find('input[name="qsn_type"]').val(),c=a.find('input[name="qsn_type_qsn_category"]').val(),e=a.find('input[name="qsn_type_label"]').val();f[0]={};f[0].qsn_type=b;f[0].qsn_type_qsn_category=c;f[0].qsn_type_label=e;d.paperQuestionTypeParam=f;$.ajax({type:"post",url:window.L._adminUrl+"/paper/paperCtl.php?a=ajaxGetAllowExtractQuantity",data:d,dataType:"json",error:function(){},beforeSend:function(){},success:function(b){if(""!=b)for(var b=
b[0],c=a.find('span[name^="qsnQty_level_"]'),d=0;d<c.length;d++)c.eq(d).html(b[d]);else window.L.openCom("tip")("\u64cd\u4f5c\u5931\u8d25")}})};
