var setUserPermissionsObj={groupListJson:null,stratifiedListJson:null,stratifiedTypeLanguage:[window.L.getText("\u6392\u9664"),window.L.getText("\u5305\u542b")],setStratifiedTableTr:function(a){var c="",b;for(b in setUserPermissionsObj[a])c+="<tr><td>"+window.L.strTranscoding.textToHtml(setUserPermissionsObj[a][b].name)+"</td>"+("stratifiedListJson"===a?"":'<td><input type="checkbox" class="checkbox" onclick="setUserPermissionsObj.tabStratifiedChild(this, \''+b+"', '"+a+"')\" "+("1"==setUserPermissionsObj[a][b].isChild?
"checked":"")+" ></td>")+'<td><a href="#" onclick="setUserPermissionsObj.tabStratifiedType(this, \''+b+"', '"+a+"'); return false;\">"+setUserPermissionsObj.stratifiedTypeLanguage[setUserPermissionsObj[a][b].type]+'</a></td><td><a href="#" onclick="setUserPermissionsObj.delStratified(this, \''+b+"', '"+a+"'); return false;\">"+window.L.getText("\u5220\u9664")+"</a></td></tr>";$("stratifiedListJson"===a?"#stratifiedListTable tbody":"#groupListTable tbody").html(c);window.L.openCom("oDialogDiv").skinLayout(1,
"auto",{maxHeight:"80%"})},tabStratifiedType:function(a,c,b){a.innerHTML=setUserPermissionsObj.stratifiedTypeLanguage[setUserPermissionsObj[b][c].type=parseInt(setUserPermissionsObj[b][c].type)?0:1]},tabStratifiedChild:function(a,c,b){setUserPermissionsObj[b][c].isChild=parseInt(setUserPermissionsObj[b][c].isChild)?0:1},delStratified:function(a,c,b){delete setUserPermissionsObj[b][c];setUserPermissionsObj.setStratifiedTableTr(b)},addUserGroupClickFun:function(a){var c=[],b;for(b in setUserPermissionsObj.groupListJson)c[c.length]=
b;getTree({targetId:a.id,treeMark:a.id,callbackFn:function(a){var b={},c,e;for(e in a)c=a[e].id,b[c]=setUserPermissionsObj.groupListJson[c]?setUserPermissionsObj.groupListJson[c]:{id:c,name:a[e].name,type:1,isChild:0};setUserPermissionsObj.groupListJson=b;setUserPermissionsObj.setStratifiedTableTr("groupListJson")},dataType:"group",isCheckBox:!0,isExpand:!1,showRoot:!1,expandLevel:2,checkedId:c,chkboxType:{Y:"",N:""}})},addStratifiedClickFun:function(){var a={"00":{type:!1}},c;for(c in setUserPermissionsObj.stratifiedListJson)a[c]=
{type:!0};window.L.openCom("oDialogDiv")("\u8bf7\u9009\u62e9\u7528\u6237","iframe:"+window.L._adminUrl+'/course/course.php?{"get" : {"a" : "getAssociatedCourseUserList"}, "post" : {"associatedCourseUserList" : \''+window.L.JSON.stringify(a)+"'}}","auto",{maxHeight:"90%"},[2,function(b,c,f){if(b&&"visible"===f.oDialogDivObj.find("iframe").css("visibility")){var b=f.oDialogDivObj.find("iframe").prop("contentWindow"),c=b.document.getElementById("getAssociatedCourseUserListPageTable"),b=b.L.extension.pageTable.classObj.params(c),
d;for(d in b.associatedCourseUserList)b.associatedCourseUserList[d].attr&&(setUserPermissionsObj.stratifiedListJson[d]={id:d,name:b.associatedCourseUserList[d].attr.userName,type:1}),delete a[d];for(d in a)"00"!==d&&delete setUserPermissionsObj.stratifiedListJson[d];setUserPermissionsObj.setStratifiedTableTr("stratifiedListJson")}}])},getUrlPermissionsStr:function(){var a=[];$("input[id^=urlPermissionsId_]").each(function(){this.checked&&(a[a.length]=this.id.substr(17))});return a.join()},urlPermissionsSelectAll:function(a){$("input[id^=urlPermissionsId_]").each(function(){this.checked=
a.checked})},urlPermissionsInvertSelect:function(){$("input[id^=urlPermissionsId_]").each(function(){this.checked=!this.checked})},userId:null,init:function(a,c,b){setUserPermissionsObj.userId=a;setUserPermissionsObj.stratifiedListJson=c;setUserPermissionsObj.groupListJson=b;setUserPermissionsObj.setStratifiedTableTr("groupListJson");setUserPermissionsObj.setStratifiedTableTr("stratifiedListJson")},save:function(){window.L.openCom("tip")(window.L.getText("\u6b63\u5728\u63d0\u4ea4...",!1));var a="0";
if(""==setUserPermissionsObj.getUrlPermissionsStr()||""==setUserPermissionsObj.groupListJson)return window.L.openCom("tip")(window.L.getText("\u5f53\u524d\u7528\u6237\u7684\u89d2\u8272\uff0f\u7ba1\u7406\u8303\u56f4\u6ca1\u6709\u8bbe\u7f6e")),a;$.ajax({url:"?a=saveUserPermissions",type:"post",data:{userId:setUserPermissionsObj.userId,stratified:setUserPermissionsObj.stratifiedListJson,group:setUserPermissionsObj.groupListJson,urlPermissions:setUserPermissionsObj.getUrlPermissionsStr()},success:function(c){"1"===
c?window.L.openCom("tip")(window.L.getText("\u6743\u9650\u8bbe\u7f6e\u6210\u529f"),null,0):window.L.openCom("tip")(window.L.getText("\u64cd\u4f5c\u5931\u8d25,\u8bf7\u8054\u7cfb\u7ba1\u7406\u5458"));a=c},async:!1});return a},tabPermissions:function(a){$("div.tab_content").hide();$("#"+a.value).show();$("div.tab_title > a").removeClass("current");a.parentNode.parentNode.className="current";window.L.openCom("oDialogDiv").skinLayout(-1,"auto",{maxHeight:"80%"})}};
