var SDIV_LIST={},SDIV_ANIMAING={};
function initSwitchDiv(a){var b={sdiv_list:null,target_div:null,prev:null,next:null,seed_id:(new Date).getTime(),pos_now:0,target_width:null,target_height:null,is_del_sdiv:!0,prev_style:"default",next_style:"default",is_round:!0,auto_interval:0},a=$.extend({},b,a),d=0,b=$(a.target_div).width(),c=$(a.target_div).height();a.target_width=null===a.target_width?b:a.target_width;a.target_height=null===a.target_height?c:a.target_height;SDIV_LIST[a.seed_id]={div_content:{},pos_now:a.pos_now,pos_max:0,option:a};
$.each(a.sdiv_list,function(c,b){$(b).show();SDIV_LIST[a.seed_id].div_content[d]=$("<div></div>").append($(b).clone()).html();SDIV_LIST[a.seed_id].pos_max=d;d++;a.is_del_sdiv&&$(b).remove()});b='<div id="scontain_div_'+a.seed_id+'" style="width:'+a.target_width+"px;height:"+a.target_height+'px;" ><div id="sdiv_'+a.seed_id+"_"+a.pos_now+'" style="width:'+a.target_width+"px;height:"+a.target_height+'px;" align="center"></div></div>';$(a.target_div).append(b);$(a.target_div).css("overflow","hidden");
$("#sdiv_"+a.seed_id+"_"+a.pos_now).append(SDIV_LIST[a.seed_id].div_content[a.pos_now]);null!==a.prev&&$(a.prev).bind("click",function(){switchDiv(a.seed_id,"prev",a.prev_style)});null!==a.next&&$(a.next).bind("click",function(){switchDiv(a.seed_id,"next",a.next_style)});return a.seed_id}
function switchDiv(a,b,d){var c=b?b:"next",b=d?d:"default";if(!(SDIV_LIST[a].pos_now==parseInt(c)||0==SDIV_LIST[a].pos_max||"first"==c&&0==SDIV_LIST[a].pos_now||"last"==c&&SDIV_LIST[a].pos_now==SDIV_LIST[a].pos_max||SDIV_ANIMAING[a])){SDIV_ANIMAING[a]=!0;switch(c){case "next":c=SDIV_LIST[a].pos_now+1>SDIV_LIST[a].pos_max?0:SDIV_LIST[a].pos_now+1;b="default"==b?"slideLeft":b;break;case "prev":c=0>SDIV_LIST[a].pos_now-1?SDIV_LIST[a].pos_max:SDIV_LIST[a].pos_now-1;b="default"==b?"slideRight":b;break;
case "first":c=0;b="default"==b?"slideRight":b;break;case "last":c=SDIV_LIST[a].pos_max;b="default"==b?"slideLeft":b;break;default:c=parseInt(c),c=c>SDIV_LIST[a].pos_max?SDIV_LIST[a].pos_max:c,b=c>SDIV_LIST[a].pos_max&&"default"==b?"slideLeft":"slideRight"}switch(b){case "slideLeft":$("#sdiv_"+a+"_"+SDIV_LIST[a].pos_now).css("float","left");$("#scontain_div_"+a).width($("#scontain_div_"+a).width()+SDIV_LIST[a].option.target_width);b='<div id="sdiv_'+a+"_"+c+'" style="width:'+SDIV_LIST[a].option.target_width+
"px;height:"+SDIV_LIST[a].option.target_height+'px; float:right;" align="center"></div>';$("#scontain_div_"+a).append(b);$("#sdiv_"+a+"_"+c).append(SDIV_LIST[a].div_content[c]);$("#scontain_div_"+a).animate({marginLeft:"-"+SDIV_LIST[a].option.target_width+"px"},1E3,function(){$("#sdiv_"+a+"_"+SDIV_LIST[a].pos_now).remove();$("#scontain_div_"+a).width(SDIV_LIST[a].option.target_width);$("#scontain_div_"+a).css("marginLeft","0px");SDIV_LIST[a].pos_now=c;SDIV_ANIMAING[a]=!1});break;case "slideRight":$("#sdiv_"+
a+"_"+SDIV_LIST[a].pos_now).css("float","right");$("#scontain_div_"+a).width($("#scontain_div_"+a).width()+SDIV_LIST[a].option.target_width);$("#scontain_div_"+a).css("marginLeft","-"+SDIV_LIST[a].option.target_width+"px");b='<div id="sdiv_'+a+"_"+c+'" style="width:'+SDIV_LIST[a].option.target_width+"px;height:"+SDIV_LIST[a].option.target_height+'px; float:left;" align="center"></div>';$("#scontain_div_"+a).append(b);$("#sdiv_"+a+"_"+c).append(SDIV_LIST[a].div_content[c]);$("#scontain_div_"+a).animate({marginLeft:"0px"},
1E3,function(){$("#sdiv_"+a+"_"+SDIV_LIST[a].pos_now).remove();$("#scontain_div_"+a).width(SDIV_LIST[a].option.target_width);SDIV_LIST[a].pos_now=c;SDIV_ANIMAING[a]=!1});break;case "slideUp":$("#scontain_div_"+a).height($("#scontain_div_"+a).height()+SDIV_LIST[a].option.target_height);b='<div id="sdiv_'+a+"_"+c+'" style="width:'+SDIV_LIST[a].option.target_width+"px;height:"+SDIV_LIST[a].option.target_height+'px; " align="center"></div>';$("#scontain_div_"+a).append(b);$("#sdiv_"+a+"_"+c).append(SDIV_LIST[a].div_content[c]);
$("#scontain_div_"+a).animate({marginTop:"-"+SDIV_LIST[a].option.target_height+"px"},1E3,function(){$("#sdiv_"+a+"_"+SDIV_LIST[a].pos_now).remove();$("#scontain_div_"+a).height(SDIV_LIST[a].option.target_height);$("#scontain_div_"+a).css("marginTop","0px");SDIV_LIST[a].pos_now=c;SDIV_ANIMAING[a]=!1});break;case "slideDown":$("#scontain_div_"+a).height($("#scontain_div_"+a).height()+SDIV_LIST[a].option.target_height);$("#scontain_div_"+a).css("marginTop","-"+SDIV_LIST[a].option.target_height+"px");
b='<div id="sdiv_'+a+"_"+c+'" style="width:'+SDIV_LIST[a].option.target_width+"px;height:"+SDIV_LIST[a].option.target_height+'px; " align="center"></div>';$("#scontain_div_"+a).prepend(b);$("#sdiv_"+a+"_"+c).append(SDIV_LIST[a].div_content[c]);$("#scontain_div_"+a).animate({marginTop:"0px"},1E3,function(){$("#sdiv_"+a+"_"+SDIV_LIST[a].pos_now).remove();$("#scontain_div_"+a).height(SDIV_LIST[a].option.target_height);SDIV_LIST[a].pos_now=c;SDIV_ANIMAING[a]=!1});break;case "fade":$("#sdiv_"+a+"_"+SDIV_LIST[a].pos_now).fadeOut("fast",
function(){var b='<div id="sdiv_'+a+"_"+c+'" style="width:'+SDIV_LIST[a].option.target_width+"px;height:"+SDIV_LIST[a].option.target_height+'px; display:none;" align="center"></div>';$("#scontain_div_"+a).append(b);$("#sdiv_"+a+"_"+c).append(SDIV_LIST[a].div_content[c]);$("#sdiv_"+a+"_"+c).fadeIn("fast");$("#sdiv_"+a+"_"+SDIV_LIST[a].pos_now).remove();SDIV_LIST[a].pos_now=c;SDIV_ANIMAING[a]=!1})}}}
function runSwitchDivAutoInterval(a){0!=SDIV_LIST[a].option.auto_interval&&(null===SDIV_LIST[a].option.next_style&&(SDIV_LIST[a].option.next_style="default"),setTimeout("switchDiv('"+a+"','next','"+SDIV_LIST[a].option.next_style+"')",SDIV_LIST[a].option.auto_interval))};
