function examscoreInitExamscoreManage(){initResetArea({selection:"#examscore_search_param_div",id:"examscore_search_param_div"});window.L.openCom("wDate",{obj:$("#exam_begin_tm").get(0),params:{readOnly:!0}});window.L.openCom("wDate",{obj:$("#exam_end_tm").get(0),params:{readOnly:!0}});window.L.openCom("oDialogDiv")}function examscoreResetSearchParams(){resetArea("examscore_search_param_div");examscoreInitExamscoreManage()}
function examscoreSearchExamscoreList(){var c=examscoreGetSearchCondition(),a=$('table[_pagetabledataset="admin_examscore_examscoreCtl::displayCheckExamScoreList"]');window.L.extension.pageTable.classObj.params(a.get(0),c,!0)}
function examscoreGetSearchCondition(){return{exam_name:escape($.trim($("#exam_name").val())),exam_times:$("#exam_times").val(),user_name:$("#user_name").val(),exam_category:"3"==$("#exam_category").val()?"":$("#exam_category").val(),group_id:"false"==$("#group_id").attr("key")?"":$("#group_id").attr("key"),exam_begin_tm:$("#exam_begin_tm").val(),exam_end_tm:$.trim($("#exam_end_tm").val()),min_score:$.trim($("#min_score").val()),max_score:$.trim($("#max_score").val()),is_failed:$("#is_failed").val()}}
function examscoreUpdateScore(c){var a={},b="success",e="";if("selected"==c){var d,f=!1;$(":checkbox[name='es_cb']:checked").each(function(c){var g=$(this).val().split("_");f=!0;a[c]={};d=$(this).val().split("_");a[c].exam_id=d[0];a[c].user_id=d[1];a[c].exam_times=d[2];a[c].exam_score=parseFloat($("#es_text_"+g[0]+"_"+g[1]+"_"+g[2]).val());if(isNaN(a[0].exam_score))return b="failed",e=window.L.getText("\u8003\u8bd5\u6210\u7ee9\u5fc5\u987b\u4e3a\u6709\u6548\u7684\u6570\u5b57"),!1});f||(b="failed",
e=window.L.getText("\u8bf7\u81f3\u5c11\u9009\u4e2d\u4e00\u6761\u6570\u636e"))}else d=c.split("_"),a[0]={},a[0].exam_id=d[0],a[0].user_id=d[1],a[0].exam_times=d[2],a[0].exam_score=parseFloat($("#es_text_"+c).val()),isNaN(a[0].exam_score)&&(b="failed",e=window.L.getText("\u8003\u8bd5\u6210\u7ee9\u5fc5\u987b\u4e3a\u6709\u6548\u7684\u6570\u5b57"));"success"==b?(c=window.L._adminUrl+"/examscore/examscoreCtl.php?a=updateUserExamscore",a="params="+encodeURIComponent(L.JSON.stringify(a)),$.ajax({type:"POST",
async:!1,url:c,data:a,dataType:"json",success:function(a){"success"==a.res?(oDialogDivInfo(window.L.getText("\u66f4\u65b0\u6210\u529f")),a=$('table[_pagetabledataset="admin_examscore_examscoreCtl::displayCheckExamScoreList"]'),window.L.extension.pageTable.classObj.pageClickFn(a.get(0),0)()):oDialogDivInfo(a.info)},error:function(){}})):oDialogDivInfo(e)}
function examscoreAlertDeleteScore(){var c=window.L.getText("\u6ce8\uff1a\u6b64\u64cd\u4f5c\u4e0d\u53ef\u6062\u590d")+'<br><a href="javascript:void(0)" onclick="examscoreDeleteScore(\'selected\')" class="btn2" >'+window.L.getText("\u5220\u9664\u9009\u4e2d\u6210\u7ee9")+'</a><a href="javascript:void(0)" onclick="examscoreDeleteScore(\'search\')" class="btn2" >'+window.L.getText("\u5220\u9664\u641c\u7d22\u6210\u7ee9")+'</a><a href="javascript:void(0)" onclick="alertCloseAlertDiv()" class="btn2" >'+
window.L.getText("\u5173\u95ed")+"</a>";window.L.openCom("oDialogDiv")&&(ALERT_DIV_MARK=oDialogDiv(window.L.getText("\u5220\u9664\u6210\u7ee9"),"text:"+c,"auto","auto",[1]))}
function examscoreDeleteScore(c){var a={params:{},del_method:"selected",del_condition:{}},b="success",e="",d=0;if("selected"==c){var f;$(":checkbox[name='es_cb']:checked").each(function(b){d++;a.params[b]={};f=$(this).val().split("_");a.params[b].exam_id=f[0];a.params[b].user_id=f[1];a.params[b].exam_times=f[2];a.params[b].exam_score=$("#es_text_"+$(this).val()).val()});void 0==a.params[0]&&(b="failed",e=window.L.getText("\u8bf7\u81f3\u5c11\u9009\u62e9\u4e00\u6761\u6570\u636e"))}else"search"==c?(a.del_method=
"search",a.del_condition=examscoreGetSearchCondition()):(f=c.split("_"),a.params[0]={},a.params[0].exam_id=f[0],a.params[0].user_id=f[1],a.params[0].exam_times=f[2],a.params[0].exam_score=$("#es_text_"+c).val());"success"==b?oDialogDiv(window.L.getText("\u786e\u5b9a\u5220\u9664\uff1f"),'text:<div style="width:200px; height:30px;">'+window.L.getText("\u786e\u8ba4\u5220\u9664\u6210\u7ee9")+"?</div>","auto","auto",[2,function(b){b&&(b=window.L._adminUrl+"/examscore/examscoreCtl.php?a=deleteUserExamscore",
a="params="+encodeURIComponent(L.JSON.stringify(a)),$.ajax({type:"POST",async:!1,url:b,data:a,dataType:"json",success:function(a){"success"==a.res?(oDialogDivInfo(window.L.getText("\u5220\u9664\u7528\u6237\u6210\u7ee9\u6210\u529f")),a=$('table[_pagetabledataset="admin_examscore_examscoreCtl::displayCheckExamScoreList"]'),""!=ALERT_DIV_MARK&&(alertCloseAlertDiv(),ALERT_DIV_MARK=""),window.L.extension.pageTable.classObj.pageClickFn(a.get(0),0)()):oDialogDivInfo(a.info)},error:function(){}}))}]):oDialogDivInfo(e)}
function examscoreAlertRemakeScore(){var c=window.L.getText("\u6ce8\uff1a\u6b64\u64cd\u4f5c\u4e0d\u53ef\u6062\u590d")+'<br><a href="javascript:void(0)" onclick="examscoreRemakeScore(\'selected\')" class="btn2" >'+window.L.getText("\u91cd\u7b97\u9009\u4e2d\u6210\u7ee9")+'</a><a href="javascript:void(0)" onclick="examscoreRemakeScore(\'search\')" class="btn2" >'+window.L.getText("\u91cd\u7b97\u641c\u7d22\u6210\u7ee9")+'</a><a href="javascript:void(0)" onclick="alertCloseAlertDiv()" class="btn2" >'+
window.L.getText("\u5173\u95ed")+"</a>";window.L.openCom("oDialogDiv")&&(ALERT_DIV_MARK=oDialogDiv(window.L.getText("\u91cd\u7b97\u6210\u7ee9"),"text:"+c,"auto","auto",[1]))}
function examscoreRemakeScore(c){window.L.openCom("oDialogDiv")("\u91cd\u7b97\u6210\u7ee9\u786e\u8ba4","text:<span>\u5c06\u6839\u636e\u8bd5\u5377\u4e2d\u8bbe\u5b9a\u7684\u8bd5\u9898\u5206\u503c\u91cd\u65b0\u8ba1\u7b97\u7528\u6237\u6210\u7ee9\uff0c\u5982\u5df2\u5bf9\u6539\u7528\u6237\u8bd5\u5377\u8fdb\u884c\u4eba\u5de5\u8bc4\u5377\uff0c\u4eba\u5de5\u8bc4\u5377\u7684\u7ed3\u679c\u4e5f\u4f1a\u88ab\u6e05\u9664\uff0c\u786e\u5b9a\u6267\u884c\u91cd\u65b0\u8ba1\u7b97\u6210\u7ee9\uff1f</span>","auto","auto",
[2,function(a){if(a){var b={params:{},remake_method:"selected",remake_condition:{}},a="success",e="";if("selected"==c){var d;$(":checkbox[name='es_cb']:checked").each(function(a){b.params[a]={};d=$(this).val().split("_");b.params[a].exam_id=d[0];b.params[a].user_id=d[1];b.params[a].exam_times=d[2];b.params[a].papr_id=d[3];b.params[a].exam_score=$("#es_text_"+$(this).val()).val()});void 0==b.params[0]&&(a="failed",e=window.L.getText("\u8bf7\u81f3\u5c11\u9009\u62e9\u4e00\u6761\u6570\u636e"))}else"search"==
c?(b.remake_method="search",b.remake_condition=examscoreGetSearchCondition()):(d=c.split("_"),b.params[0]={},b.params[0].exam_id=d[0],b.params[0].user_id=d[1],b.params[0].exam_times=d[2],b.params[0].papr_id=d[3],b.params[0].exam_score=$("#es_text_"+c).val());"success"==a?(a=window.L._adminUrl+"/examscore/examscoreCtl.php?a=remakeUserExamScore",b="params="+encodeURIComponent(L.JSON.stringify(b)),$.ajax({type:"POST",async:!1,url:a,data:b,dataType:"json",success:function(a){"success"==a.res?(oDialogDivInfo(window.L.getText("\u91cd\u7b97\u6210\u529f")),
a=$('table[_pagetabledataset="admin_examscore_examscoreCtl::displayCheckExamScoreList"]'),""!=ALERT_DIV_MARK&&(alertCloseAlertDiv(),ALERT_DIV_MARK=""),window.L.extension.pageTable.classObj.pageClickFn(a.get(0),0)()):oDialogDivInfo(a.info)},error:function(){}})):oDialogDivInfo(e)}}])}
function examscoreAlertExportScore(){var c='<a href="javascript:void(0)" onclick="examscoreExportScore(\'selected\')" class="btn2" >'+window.L.getText("\u5bfc\u51fa\u9009\u4e2d\u6210\u7ee9")+'</a><a href="javascript:void(0)" onclick="examscoreExportScore(\'search\')" class="btn2" >'+window.L.getText("\u5bfc\u51fa\u641c\u7d22\u6210\u7ee9")+'</a><a href="javascript:void(0)" onclick="alertCloseAlertDiv()" class="btn2" >'+window.L.getText("\u5173\u95ed")+"</a>";window.L.openCom("oDialogDiv")&&(ALERT_DIV_MARK=
oDialogDiv(window.L.getText("\u5bfc\u51fa\u6210\u7ee9"),"text:"+c,"auto","auto",[1]))}
function examscoreExportScore(c){var a={params:{},export_method:"selected",export_condition:{}},b="success",e="";if("selected"==c){var d;$(":checkbox[name='es_cb']:checked").each(function(b){a.params[b]={};d=$(this).val().split("_");a.params[b].exam_id=d[0];a.params[b].user_id=d[1];a.params[b].exam_times=d[2];a.params[b].exam_score=$("#es_text_"+$(this).val()).val()});void 0==a.params[0]&&(b="failed",e=window.L.getText("\u8bf7\u81f3\u5c11\u9009\u62e9\u4e00\u6761\u6570\u636e"))}else"search"==c&&(a.export_method=
"search",a.export_condition=examscoreGetSearchCondition());"success"==b?(a=encodeURIComponent(L.JSON.stringify(a)),$("#export_params").val(a),$("#examscore_export_form").submit()):oDialogDivInfo(e)}function examCategoryTreeShow(c,a,b){getTree({targetNameId:c,targetValueId:a,dataType:"exam_category",showRoot:b?b:!1})}
function examGroupTreeShow(c){getTree({targetId:"group_id",callbackFn:function(a){window.L.each(a,function(a,c){idList[a]=c[a].id;nameList[a]=c[a].name},idList=[],nameList=[]);$(c).attr("key",idList.join(",")).val(nameList.join(","))},dataType:"group",isExpand:!1,showRoot:!1,isCheckBox:!0,chkboxType:{Y:"s",N:"ps"}})}
function examAlertExamUserList(c,a,b){var e=window.L._adminUrl+"/examscore/examscoreCtl.php?";ALERT_DIV_MARK=oDialogDiv(window.L.getText("\u4eba\u5458\u5217\u8868"),"iframe:"+e+'{"get":{"a":"alertExamUserList"}, "post" : {"exam_id":"'+c+'","exam_times":"'+a+'","list_type":"'+b+'"}}',"800px","600px",[1],10,!0)}function exportExamUserList(c,a,b){window.open(window.L._adminUrl+"/examscore/examscoreCtl.php?a=exportExamUserList&exam_id="+c+"&exam_times="+a+"&list_type="+b)};
