function inviteInitAlert(){}function inviteAlertAddInvite(a){a=L.JSON.stringify($.extend({},{inviteContent:{}},a));window.L.openCom("oDialogDiv")&&(ALERT_DIV_MARK=oDialogDiv("\u6dfb\u52a0\u9080\u8bf7","url:post?"+(window.L._adminUrl+"/invite/inviteCtl.php?")+"{'get':{'a':'alertAddInvitePage'}, 'post' : {'invite_info':'"+a+"'}}","300px","260px",[1,{layoutFun:inviteInitAlert}]))}function inviteAlertIncludeUser(){user(inviteAddUser)}
function inviteAddUser(a){var b="",c;for(c in a){var d=!1;$("input[name='invite_target_2']").each(function(){$(this).val()==a[c].id&&(d=!0)});d||(b+='<span id="invite_target_2_'+a[c].id+'_lb"><input type="hidden" value="'+a[c].id+'" id="invite_target_2_'+a[c].id+'" name="invite_target_2" />'+a[c].name+'[<a href="javascript:void(0)" onclick="inviteDelUser(\''+a[c].id+"')\">\u5220\u9664</a>]</span>")}$("#invite_target_2_div").append(b)}
function inviteDelUser(a){$("#invite_target_2_"+a+"_lb").remove()}
function inviteChangeInviteType(){switch($("#invite_type").val()){case "0":$("#send_tm_lb").hide();$("#interval_tm_lb").hide();break;case "1":$("#send_tm_lb").show();$("#send_tm_1_lb").show();$("#send_tm_2_lb").hide();$("#interval_tm_lb").hide();break;case "2":$("#send_tm_lb").show();$("#send_tm_1_lb").hide();$("#send_tm_2_lb").show();$("#interval_tm_lb").show();$("#interval_tm_2_lb").show();$("#interval_tm_3_lb").hide();break;case "3":$("#send_tm_lb").hide(),$("#interval_tm_lb").show(),$("#interval_tm_2_lb").hide(),
$("#interval_tm_3_lb").show()}}
function inviteChangeInviteTargetType(){switch($("#invite_target_type").val()){case "1":$("#invite_target_type_2_div").hide(),$("#invite_target_type_3_div").hide(),$("#invite_target_type_4_div").hide();case "2":$("#invite_target_type_2_div").show();$("#invite_target_type_3_div").hide();$("#invite_target_type_4_div").hide();break;case "3":$("#invite_target_type_2_div").hide();$("#invite_target_type_3_div").show();$("#invite_target_type_4_div").hide();break;case "4":$("#invite_target_type_2_div").hide(),$("#invite_target_type_3_div").hide(),
$("#invite_target_type_4_div").show()}}function inviteGroupTreeShow(a){getTree({targetId:"group_tree_a",dataType:"group",showRoot:a?a:!1,callbackFn:inviteAddGroup})}
function inviteAddGroup(a,b){void 0==$("#invite_target_3_"+a).val()&&$("#invite_target_3_div").append('<span id="invite_target_3_'+a+'_lb"><input type="hidden" value="'+a+'" id="invite_target_3_'+a+'" name="invite_target_3" />'+b+'<input name="is_include_sub" type="checkbox" class="checkbox" id="is_include_sub_'+a+'" checked="checked" />\u5305\u542b\u4e0b\u7ea7\u7ec4[<a href="javascript:void(0)" onclick="inviteDelGroup(\''+a+"')\">\u5220\u9664</a>]</span>")}
function inviteDelGroup(a){$("#invite_target_3_"+a+"_lb").remove()}
function inviteAddEmail(){var a=1,b=$("input[name='invite_target_4']").size();0<b&&(a=Number($($("label[name='invite_target_4_item_lb']").get(b-1)).attr("value"))+1);$("#invite_target_4_div").append('<span id="invite_target_4_'+a+'_lb" name="invite_target_4_item_lb" value="'+a+'"><input type="text" value="" id="invite_target_4_'+a+'" name="invite_target_4"/>[<a href="javascript:void(0)" onclick="inviteDelEmail(\''+a+"')\">\u5220\u9664</a>]</span>")}
function inviteDelEmail(a){$("#invite_target_4_"+a+"_lb").remove()}
function inviteModifyInvite(){var a={res:"success",info:""},b={invite_type:$("#invite_type").val(),invite_status:1,send_tm:"",invite_content_type:$("#invite_content_type").val(),link_flg:"checked"==$("#link_flg").attr("checked")?1:0,invite_target_type:$("#invite_target_type").val(),invite_note:$("#invite_content").val(),interval_tm:0,invite_target:{},invite_content:{}};switch(b.invite_type){case "1":b.send_tm=$("#send_tm").val();b.interval_tm=$("#interval_tm").val();break;case "2":b.send_tm=$("#send_tm").val();
break;case "3":b.interval_tm=$("#interval_tm").val()}switch(b.invite_target_type){case "3":var c=0;$("input[name='invite_target_3']").each(function(a){c++;b.invite_target[a]={target_id:$(this).val(),is_include_sub:"checked"==$("#is_include_sub_"+$(this).val()).attr("checked")?1:0}});0==c&&(a.res="failed",a.info="\u8bf7\u6dfb\u52a0\u81f3\u5c11\u4e00\u4e2a\u7ec4");break;case "4":var d=0;$("input[name='invite_target_4']").each(function(c){d++;b.invite_target[c]={target_id:$(this).val()};validEmail($(this).val())||
(a.res="failed",a.info="\u90ae\u7bb1\u683c\u5f0f\u9519\u8bef")});0==d&&(a.res="failed",a.info="\u8bf7\u6dfb\u52a0\u81f3\u5c11\u4e00\u4e2a\u90ae\u7bb1")}$("input[name='invite_content']").each(function(a){b.invite_content[a]={content_id:$(this).val()}});if("success"==a.res){oDialogDivInfo("\u53d1\u9001\u4e2d...",3E5);var e=window.L._adminUrl+"/invite/inviteCtl.php?a=modifyInvite",f="invite_obj="+encodeURIComponent(L.JSON.stringify(b));$.ajax({type:"POST",async:!1,url:e,data:f,dataType:"json",success:function(b){a=
b;"success"==a.res?oDialogDivInfo("\u53d1\u9001\u6210\u529f"):oDialogDivInfo(a.info)},error:function(){}})}else oDialogDivInfo(a.info)}function inviteStartOrStopAutoSending(){$.ajax({type:"POST",async:!0,url:window.L._adminUrl+"/invite/inviteCtl.php?a=startOrStopAutoSending",data:"",dataType:"json",timeout:"2000",success:function(){},error:function(){}});$("#auto_remind_lb").html("\u64cd\u4f5c\u4e2d......");inviteGetAutoSendingStatus()}
function inviteGetAutoSendingStatus(){$.ajax({type:"POST",async:!0,url:window.L._adminUrl+"/invite/inviteCtl.php?a=getAutoSendingStatus",data:"",dataType:"text",success:function(a){"1"==a?$("#auto_remind_lb").html('\u5df2\u542f\u52a8[<a href="javascript:void(0)" onclick="inviteStartOrStopAutoSending()">\u505c\u6b62</a>]'):$("#auto_remind_lb").html('\u672a\u542f\u52a8[<a href="javascript:void(0)" onclick="inviteStartOrStopAutoSending()">\u542f\u52a8</a>]')},error:function(){}})};
