function backupAlertBackupDiv(){var a='<div id="backup_info_div" align="center" style="width:330px"><label><input id="is_backup_data" name="backup_info" value="0" type="checkbox" />'+window.L.getText("\u5907\u4efd\u9644\u4ef6")+'</label><label><input id="is_backup_sql" value="0" name="backup_info" type="checkbox" />'+window.L.getText("\u5907\u4efd\u6570\u636e\u5e93")+'</label><br><a href="javascript:void(0)" onclick="backupStartBackup()" class="btn2" >'+window.L.getText("\u786e\u5b9a")+'</a> <a href="javascript:void(0)" onclick="alertCloseAlertDiv()" class="btn2" >'+
window.L.getText("\u53d6\u6d88")+"</a></div>";ALERT_DIV_MARK=window.L.openCom("oDialogDiv")(window.L.getText("\u8bf7\u9009\u62e9\u5907\u4efd\u5185\u5bb9"),"text:"+a,"342px","128px",[0])}
function backupStartBackup(){var a=$("#is_backup_data").is(":checked")||"1"==$("#is_backup_data").val()?1:0,b=$("#is_backup_sql").is(":checked")||"1"==$("#is_backup_sql").val()?1:0;1==a||1==b?$.ajax({type:"POST",async:!0,url:window.L._adminUrl+"/backup/backupCtl.php?a=backup",data:"is_backup_data="+a+"&is_backup_sql="+b,dataType:"json",beforeSend:function(){$("#backup_info_div").html('<img src="'+L._rootUrl+'/images/preload.gif"/><br>'+window.L.getText("\u6b63\u5728\u5907\u4efd\u4e2d\uff0c\u8bf7\u7a0d\u540e\u2026\u2026"))},
success:function(c){if("success"==c.res){var d=window.L.getText("\u5907\u4efd\u5b8c\u6210")+"<br>";1==a&&(d+='<a class="btn2" href="javascript:void(0)" onclick="backupDownload(\''+c.info+"','data')\" >"+window.L.getText("\u4e0b\u8f7d\u9644\u4ef6")+"</a>");1==b&&(d+='<a class="btn2" href="javascript:void(0)" onclick="backupDownload(\''+c.info+"','sql')\" >"+window.L.getText("\u4e0b\u8f7d\u6570\u636e\u5e93")+"</a>");d+='<a href="javascript:void(0)" onclick="alertCloseAlertDiv()" class="btn2" >'+window.L.getText("\u5173\u95ed")+
"</a>";$("#backup_info_div").html(d)}else $("#backup_info_div").html('<input id="is_backup_sql" value="'+b+'" name="backup_info" type="hidden" /><input id="is_backup_data" name="backup_info" value="'+a+'" type="hidden" />'+window.L.getText("\u5907\u4efd\u5931\u8d25")+":"+c.info+'<br><a href="javascript:void(0)" onclick="backupStartBackup()" class="btn2" >'+window.L.getText("\u518d\u6b21\u5907\u4efd")+'</a> <a href="javascript:void(0)" onclick="alertCloseAlertDiv()" class="btn2" >'+window.L.getText("\u53d6\u6d88")+
"</a>")},error:function(){$("#backup_info_div").html('<input id="is_backup_sql" value="'+b+'" name="backup_info" type="hidden" /><input id="is_backup_data" name="backup_info" value="'+a+'" type="hidden" />'+window.L.getText("\u5907\u4efd\u5931\u8d25")+':<br><a href="javascript:void(0)" onclick="backupStartBackup()" class="btn2" >'+window.L.getText("\u518d\u6b21\u5907\u4efd")+'</a> <a href="javascript:void(0)" onclick="alertCloseAlertDiv()" class="btn2" >'+window.L.getText("\u53d6\u6d88")+"</a>")}}):
oDialogDivInfo(window.L.getText("\u8bf7\u81f3\u5c11\u9009\u4e2d\u4e00\u4e2a\u5907\u4efd\u9879"))}
function backupDownload(a,b){$.ajax({type:"POST",async:!1,url:window.L._adminUrl+"/backup/backupCtl.php?a=checkFileExist",data:"file_name="+a+"&backup_type="+b,dataType:"html",success:function(c){"1"!=c?oDialogDivInfo(window.L.getText("\u65e0\u6cd5\u4e0b\u8f7d\uff0c\u6587\u4ef6\u4e0d\u5b58\u5728")):window.location.href=window.L._adminUrl+"/backup/backupCtl.php?a=downloadBackupFile&file_name="+a+"&backup_type="+b},error:function(){oDialogDivInfo(window.L.getText("\u65e0\u6cd5\u4e0b\u8f7d\uff0c\u6587\u4ef6\u4e0d\u5b58\u5728"))}})}
function backupDeleteFile(a){var b="success",c="",d={};window.L.openCom("oDialogDiv");if("selected"==a){var e=!1;$(":checkbox[name='backup_file_cb']:checked").each(function(a){d[a]=$(this).val();e=!0});e||(b="failed",c=window.L.getText("\u8bf7\u81f3\u5c11\u9009\u4e2d\u4e00\u6761\u6570\u636e"))}else d[0]=a;"success"==b?oDialogDiv(window.L.getText("\u5220\u9664\u5907\u4efd\u6587\u4ef6"),'text:<div style="width:200px; height:30px;">'+window.L.getText("\u786e\u8ba4\u5220\u9664\u5907\u4efd\u6587\u4ef6")+
"?</div>","auto","auto",[2,function(a){if(a){var a=window.L._adminUrl+"/backup/backupCtl.php?a=deleteBackupFile",b="file_name="+encodeURIComponent(L.JSON.stringify(d));$.ajax({type:"POST",async:!1,url:a,data:b,dataType:"html",success:function(a){"1"!=a?oDialogDivInfo(window.L.getText("\u5220\u9664\u6587\u4ef6\u51fa\u9519")):(a=$('table[_pagetabledataset="admin_backup_backupCtl::displayBackupList"]'),window.L.extension.pageTable.classObj.pageClickFn(a.get(0),0)(),oDialogDivInfo(window.L.getText("\u5220\u9664\u6210\u529f")))},
error:function(){oDialogDivInfo(window.L.getText("\u5220\u9664\u6587\u4ef6\u51fa\u9519"))}})}}]):oDialogDivInfo(c)}
function backupAlertUploadDataFile(){var a='<div id="backup_upload_div" align="center" style="width:330px"><input name="backup_upload_data_file" type="file" class="" id="backup_upload_data_file" size="35" style="display: none; " filecount="0" width="60" height="21"><input name="backup_upload_sql_file" type="file" class="" id="backup_upload_sql_file" size="35" style="display: none;" filecount="0" width="60" height="21"><input type="hidden" value="" id="new_upload_file_name" /><input type="hidden" value="0" id="has_new_upload_data_file" /><input type="hidden" value="0" id="has_new_upload_sql_file" /><br><a href="javascript:void(0)" onclick="backupReturnFile(\'new\')" class="btn2" >'+window.L.getText("\u8fd8\u539f")+
'</a> <a href="javascript:void(0)" onclick="alertCloseAlertDiv()" class="btn2" >'+window.L.getText("\u53d6\u6d88")+"</a></div>";ALERT_DIV_MARK=window.L.openCom("oDialogDiv")(window.L.getText("\u8bf7\u4e0a\u4f20\u5907\u4efd\u6587\u4ef6"),"text:"+a,"342px","121px",[0]);var a=window.L.openCom("upload"),b={file_name:"",upload_file_url:"",file_type:"sql"},c=window.L._adminUrl+"/backup/backupCtl.php?a=moveUploadFile";a("backup_upload_data_file",function(a){b.file_name=$("#new_upload_file_name").val();b.upload_file_url=
a;b.file_type="data";a="upload_info="+encodeURIComponent(L.JSON.stringify(b));$.ajax({type:"POST",async:!1,url:c,data:a,dataType:"json",success:function(a){"success"==a.res?($("#new_upload_file_name").val(a.info),$("#has_new_upload_data_file").val("1"),oDialogDivInfo(window.L.getText("\u4e0a\u4f20\u6210\u529f"))):oDialogDivInfo(window.L.getText("\u4e0a\u4f20\u6587\u4ef6\u51fa\u9519"))},error:function(){oDialogDivInfo(window.L.getText("\u4e0a\u4f20\u6587\u4ef6\u51fa\u9519"))}})},"zip",'<font color="#0000ff" size="14" >'+
window.L.getText("\u4e0a\u4f20\u9644\u4ef6\u6587\u4ef6")+"</font>",95,28,{folder:"/backup/backupdata/"},{auto:!0,queueID:!0,multi:!1});a("backup_upload_sql_file",function(a){b.file_name=$("#new_upload_file_name").val();b.upload_file_url=a;b.file_type="sql";a="upload_info="+encodeURIComponent(L.JSON.stringify(b));$.ajax({type:"POST",async:!1,url:c,data:a,dataType:"json",success:function(a){"success"==a.res?($("#new_upload_file_name").val(a.info),$("#has_new_upload_sql_file").val("1"),oDialogDivInfo(window.L.getText("\u4e0a\u4f20\u6210\u529f"))):
oDialogDivInfo(window.L.getText("\u4e0a\u4f20\u6587\u4ef6\u51fa\u9519"))},error:function(){oDialogDivInfo(window.L.getText("\u4e0a\u4f20\u6587\u4ef6\u51fa\u9519"))}})},"zip;sql",'<font color="#0000ff" size="14" >'+window.L.getText("\u4e0a\u4f20\u6570\u636e\u6587\u4ef6")+"</font>",95,28,{folder:"/backup/"},{auto:!0,queueID:!0,multi:!1})}
function backupReturnFile(a){""!=ALERT_DIV_MARK&&alertCloseAlertDiv();"new"==a&&(a=$("#new_upload_file_name").val());window.L.openCom("oDialogDiv");oDialogDiv(window.L.getText("\u6062\u590d\u6570\u636e"),"text:<div>"+window.L.getText("\u662f\u5426\u786e\u8ba4\u6062\u590d\u6570\u636e")+"</div>","400px","auto",[2,function(b){b&&(b='<div id="backup_info_div" align="center" style="width:330px; height:50px;"><img src="'+L._rootUrl+'/images/preload.gif"/><br>'+window.L.getText("\u6b63\u5728\u8fd8\u539f\u4e2d\uff0c\u8bf7\u7a0d\u540e\u2026\u2026")+
"</div>",ALERT_DIV_MARK=window.L.openCom("oDialogDiv")(window.L.getText("\u8fd8\u539f"),"text:"+b,"auto","120px",[0]),$.ajax({type:"POST",async:!0,url:window.L._adminUrl+"/backup/backupCtl.php?a=returnFile",data:"file_name="+a,dataType:"json",success:function(b){"success"==b.res?(oDialogDivInfo(window.L.getText("\u8fd8\u539f\u6570\u636e\u6210\u529f")),$("#backup_info_div").html(window.L.getText("\u8fd8\u539f\u6570\u636e\u6210\u529f")+'<br><a href="javascript:void(0)" onclick="alertCloseAlertDiv()" class="btn2" >'+
window.L.getText("\u5173\u95ed")+"</a>")):(oDialogDivInfo(window.L.getText("\u8fd8\u539f\u6570\u636e\u51fa\u9519")+b.info),$("#backup_info_div").html(window.L.getText("\u8fd8\u539f\u6570\u636e\u51fa\u9519")+'<br><a href="javascript:void(0)" onclick="backupReturnFile(\''+a+'\')" class="btn2" >'+window.L.getText("\u91cd\u65b0\u8fd8\u539f")+'</a><a href="javascript:void(0)" onclick="alertCloseAlertDiv()" class="btn2" >'+window.L.getText("\u5173\u95ed")+"</a>"))},error:function(){oDialogDivInfo(window.L.getText("\u8fd8\u539f\u6570\u636e\u51fa\u9519"));
$("#backup_info_div").html(window.L.getText("\u8fd8\u539f\u6570\u636e\u51fa\u9519")+'<br><a href="javascript:void(0)" onclick="backupReturnFile(\''+a+'\')" class="btn2" >'+window.L.getText("\u91cd\u65b0\u8fd8\u539f")+'</a><a href="javascript:void(0)" onclick="alertCloseAlertDiv()" class="btn2" >'+window.L.getText("\u5173\u95ed")+"</a>")}}))}])};
