var define,require;
(function(x){function o(a,b){ja(a);var c=i.waitSeconds;p(a)&&c&&(I&&clearTimeout(I),I=setTimeout(ka,1E3*c));return la(a,b)}function ka(){var a=[],b=[],c={},e,d;for(d in f)j(d)||(a.push(d),e=1),g(f[d].realDeps||[],function(a){if(!f[a]&&!c[a]){e=1;b.push(a);c[a]=1}});if(e)throw Error("[MODULE_TIMEOUT]Hang( "+(a.join(", ")||"none")+" ) Miss( "+(b.join(", ")||"none")+" )");}function W(){var a=arguments.length;if(a){for(var b,c,e=arguments[--a];a--;){var d=arguments[a];q(d)?b=d:p(d)&&(c=d)}a=window.opera;
!b&&(document.attachEvent&&!(a&&"[object Opera]"===a.toString()))&&(b=(b=ma())&&b.getAttribute("data-require-id"));c=c||["require","exports","module"];b?(X(b,c,e),J&&clearTimeout(J),J=setTimeout(K,10)):y.push({deps:c,factory:e})}}function na(a){var b=[],c;for(c in f){var e=f[c];e.state==a&&b.push(e)}return b}function Y(){var a=i.config[this.id];return a&&"object"===typeof a?a:{}}function X(a,b,c){a in f||(f[a]={id:a,deps:b,factory:c,exports:{},config:Y,state:Z,hardDeps:{}})}function K(){var a=[],
b={},c=na(Z);g(c,function(c){var d=c.deps.slice(0);c.realDeps=d;var m=c.factory,k=/require\(\s*(['"'])([^'"]+)\1\s*\)/g,h=/(\/\*([\s\S]*?)\*\/|([^:]|^)\/\/(.*)$)/mg;"function"==typeof m&&m.toString().replace(h,"").replace(k,function(a,c,b){d.push(b)});g(d,function(d){d=z(d);d.resource&&(d=l(d.module,c.id),b[d]||(a.push(d),b[d]=1))});c.state=$});s(a,function(){aa(c)})}function aa(a){var b=[];g(a,function(a){if(a.state===$){var e=a.id,d=a.deps,m=a.hardDeps,k="function"==typeof a.factory?a.factory.length:
0;g(d,function(a,b){a=l(a,e);d[b]=a;b<k&&(m[a]=1)});for(var h=a.realDeps,n=h.length,f={};n--;){var r=l(h[n],e);!r||r in f||r in A?h.splice(n,1):(f[r]=1,h[n]=r,b.push(r))}a.realDepsIndex=f;a.state=L;oa(a);M(e)}});s(b)}function oa(a){function b(){d++;var b=1,c=[];g(a.realDeps,function(d){if(d in f&&f[d].state>=L){if(!j(d))switch(ba(e,d)){case N:case ca:b=0;break;case O:a.hardDeps[d]&&c.push(d)}}else b=0;return!!b});b&&g(c,function(a){da(a)});(b=b&&0===c.length)&&(a.state=pa);d--;return b}function c(){if(!(a.state==
B||1<d||!b())){try{var c=a.factory,f="function"==typeof c?c.apply(x,ea(a.deps,{require:P(e),exports:a.exports,module:a})):c;"undefined"!=typeof f&&(a.exports=f);a.state=B;a.invokeFactory=null}catch(h){if(/^\[MODULE_MISS\]"([^"]+)/.test(h.message)){a.hardDeps[RegExp.$1]=1;return}throw h;}M(e);fa(e)}}var e=a.id;a.invokeFactory=c;c();var d=0}function ea(a,b){var c=[];g(a,function(a,d){c[d]=b[a]||C(a)});return c}function ba(a,b,c){if(!(b in f&&f[b].state>=L))return N;c=c||{};c[b]=1;if(b==a)return O;if(b=
(b=f[b])&&b.realDeps)for(var e=b.length;e--;){var d=b[e];if(!c[d])switch(d=ba(a,d,c),d){case N:case O:return d}}return ca}function M(a){for(var b in f)(f[b].realDepsIndex||{})[a]&&da(b)}function da(a){(a=f[a])&&a.invokeFactory&&a.invokeFactory()}function fa(a){Q++;g(D,function(b){b&&b(a)});Q--;qa()}function qa(){1>Q&&(E.sort(function(a,b){return b-a}),g(E,function(a){D.splice(a,1)}),E=[])}function ra(a){g(D,function(b,c){a==b&&E.push(c)})}function j(a){return a in f&&f[a].state==B}function C(a){return j(a)?
f[a].exports:null}function ga(a){var b=y.slice(0);y.length=0;y=[];g(b,function(b){X(b.id||a,b.deps,b.factory)});K()}function s(a,b,c){function e(){function c(a){var b=1;g(a,function(a){if(!k[a]&&(k[a]=1,!A[a]&&(!j(a)||!c(f[a].realDeps))))return b=0,!1});return b}if(!d){var k={};c(a)&&(d=1,ra(e),b.apply(x,ea(a,A)))}}b=b||new Function;c=c||"";if(q(a)){if(!j(a))throw Error('[MODULE_MISS]"'+a+'" is not exists!');return C(a)}if(p(a))if(0===a.length)b();else{var d=0;D.push(e);g(a,function(a){a in A||(0<
a.indexOf("!")?sa:ta)(a,c)});e()}}function ta(a){function b(){var b=c.readyState;if("undefined"==typeof b||/^(loaded|complete)$/.test(b))c=c.onload=c.onreadystatechange=null,ga(a),delete R[a]}if(!R[a])if(a in f)aa([f[a]]);else{R[a]=1;var c=document.createElement("script");c.setAttribute("data-require-id",a);c.src=S(a);c.async=!0;c.readyState?c.onreadystatechange=b:c.onload=b;ua(c)}}function sa(a,b){function c(b){var c=a;f[c]={exports:b||!0,state:B};M(c);fa(c)}function e(d){j(a)||d.load(g,P(b),c,Y.call({id:a}))}
var d=z(a),m=d.module,g=d.resource;c.fromText=function(a,b){(new Function(b))();ga(a)};j(m)?e(C(m)):s([m],e)}function va(a,b){var c=i[a],e=typeof c;if("string"==e||"number"==e)i[a]=b;else if(p(c))g(b,function(a){c.push(a)});else for(var d in b)c[d]=b[d]}function ha(){i.baseUrl=i.baseUrl.replace(/\/$/,"")+"/";T=F(i.paths);T.sort(t());wa();xa();U=F(i.urlArgs);U.sort(t())}function xa(){u=[];g(i.packages,function(a){var b=a;q(a)&&(b={name:a.split("/")[0],location:a,main:"main"});b.location=b.location||
b.name;b.main=(b.main||"main").replace(/\.js$/i,"");u.push(b)});u.sort(t("name"))}function wa(){v=[];v=F(i.map);v.sort(t());g(v,function(a){var b=a.k;a.v=F(a.v);a.v.sort(t());a.reg="*"==b?/^/:w(b)})}function S(a){function b(a){j||(h+=(0<h.indexOf("?")?"&":"?")+a,j=1)}var c=/(\.[a-z0-9]+)$/i,e=/(\?[^#]*)$/i,d=".js",f=a,k="";e.test(a)&&(k=RegExp.$1,a=a.replace(e,""));c.test(a)&&(d=RegExp.$1,f=a.replace(c,""));if(!ia.test(f))return a;var h=f,n;g(T,function(a){var b=a.k;if(w(b).test(f)){h=h.replace(b,
a.v);n=1;return false}});n||g(u,function(a){var b=a.name;if(w(b).test(f)){h=h.replace(b,a.location);return false}});/^([a-z]{2,10}:\/)?\//i.test(h)||(h=i.baseUrl+h);var h=h+(d+k),j;g(U,function(a){if(w(a.k).test(f)){b(a.v);return false}});V&&b(V);return h}function P(a){function b(b,d){if(q(b)){var f;if(!(f=c[b]))f=s(l(b,a),d,a),c[b]=f;return f}if(p(b)){var k=[];g(b,function(b){var b=z(b),c=l(b.module,a);b.resource&&!j(c)&&k.push(c)});s(k,function(){var c=[];g(b,function(b){c.push(l(b,a))});s(c,d,
a)},a)}}var c={};b.toUrl=function(b){return S(l(b,a))};return b}function l(a,b){if(!a)return"";var c=z(a);if(!c)return a;var e=c.resource,d=ya(c.module,b);g(u,function(a){var b=a.name,a=b+"/"+a.main;if(b==d)return d=d.replace(b,a),!1});d=za(d,b);return e?(e=(c=C(d))&&c.normalize?c.normalize(e,function(a){return l(a,b)}):l(e,b),d+"!"+e):d}function ya(a,b){if(/^\.{1,2}/.test(a)){var c=b.split("/"),e=a.split("/"),d=c.length-1,f=e.length,g=0,h=0,i=0;a:for(;i<f;i++)switch(e[i]){case "..":if(g<d)g++,h++;
else break a;break;case ".":h++;break;default:break a}c.length=d-g;e=e.slice(h);c.push.apply(c,e);return c.join("/")}return a}function ja(a){function b(a){/^\.{1,2}/.test(a)&&c.push(a)}var c=[];q(a)?b(a):g(a,function(a){b(a)});if(0<c.length)throw Error("[REQUIRE_FATAL]Relative ID is not allowed in global require: "+c.join(", "));}function z(a){a=a.split("!");return ia.test(a[0])?{module:a[0],resource:a[1]||""}:null}function za(a,b){g(v,function(c){if(c.reg.test(b))return g(c.v,function(b){var c=b.k;
if(w(c).test(a))return a=a.replace(c,b.v),!1}),!1});return a}function F(a){var b=[],c;for(c in a)a.hasOwnProperty(c)&&b.push({k:c,v:a[c]});return b}function ma(){if(G)return G;if(H&&"interactive"==H.readyState)return H;for(var a=document.getElementsByTagName("script"),b=a.length;b--;){var c=a[b];if("interactive"==c.readyState)return H=c}}function ua(a){G=a;var b=document;(b.getElementsByTagName("head")[0]||b.body).appendChild(a);G=null}function w(a){return RegExp("^"+a+"(/|$)")}function p(a){return a instanceof
Array}function q(a){return"string"==typeof a}function g(a,b){if(p(a))for(var c=0,e=a.length;c<e&&!1!==b(a[c],c);c++);}function t(a){a=a||"k";return function(b,c){var e=b[a],d=c[a];return"*"==d?-1:"*"==e?1:d.length-e.length}}var f={},Z=1,$=2,L=3,pa=4,B=5,la=P(""),I;o.toUrl=S;var J;W.amd={};var N=0,ca=1,O=2,D=[],E=[],Q=0,A={require:o,exports:1,module:1},y=[],R={},i={baseUrl:"./",paths:{},config:{},map:{},packages:[],waitSeconds:0,urlArgs:{}};o.config=function(a){for(var b in i)if(a.hasOwnProperty(b)){var c=
a[b];"urlArgs"==b&&q(c)?V=c:va(b,c)}ha()};ha();var u,T,V,U,v,ia=/^[-_a-z0-9\.]+(\/[-_a-z0-9\.]+)*$/i,G,H;o.modPreAnalyse=K;o.modIsDefined=j;x.define=W;x.require=o})(this);
