function examInitExamManage(){initResetArea({selection:"#exam_search_param_div",id:"exam_search_param_div"});window.L.openCom("wDate",{obj:$("#exam_begin_tm").get(0),params:{readOnly:!0}});window.L.openCom("wDate",{obj:$("#exam_end_tm").get(0),params:{readOnly:!0}});window.L.openCom("oDialogDiv")}function examResetSearchParams(){resetArea("exam_search_param_div");examInitExamManage()}
function examSearchExamList(){var a=examGetSearchCondition(),c=$('table[_pagetabledataset="admin_exam_examCtl::displayExamList"]');window.L.extension.pageTable.classObj.params(c.get(0),a,!0)}function examSearchExerciseList(){var a=examGetSearchCondition(),c=$('table[_pagetabledataset="admin_exam_exerciseCtl::displayExerciseList"]');window.L.extension.pageTable.classObj.params(c.get(0),a,!0)}
function examGetSearchCondition(){return{exam_name:escape($.trim($("#exam_name").val())),exam_category:"3"==$("#exam_category").val()?"":$("#exam_category").val(),exam_type:$("#exam_type").val(),exam_end_tm:$("#exam_end_tm").val(),exam_begin_tm:$("#exam_begin_tm").val(),exam_status:$("#exam_status").val(),tag_names:escape($.trim($("#tag_names").val()))}}
function examUpdateExam(a){var c=$('table[_pagetabledataset="admin_exam_examCtl::displayExamList"]').attr("_pagetablecurpage"),b=$('table[_pagetabledataset="admin_exam_examCtl::displayExamList"]').attr("_pagetablepagesize"),e=$('table[_pagetabledataset="admin_exam_examCtl::displayExamList"]').attr("_pagetableparams");$("#search_condition").val(e);$("#cur_page").val(c);$("#page_size").val(b);$("#update_exam_id").val(a);$("form#update_exam_form").submit();return!1}
function examUpdateExercise(a){var c=$('table[_pagetabledataset="admin_exam_exerciseCtl::displayExerciseList"]').attr("_pagetablecurpage"),b=$('table[_pagetabledataset="admin_exam_exerciseCtl::displayExerciseList"]').attr("_pagetablepagesize"),e=$('table[_pagetabledataset="admin_exam_exerciseCtl::displayExerciseList"]').attr("_pagetableparams");$("#search_condition").val(e);$("#cur_page").val(c);$("#page_size").val(b);$("#update_exam_id").val(a);$("form#update_exercise_form").submit()}
function examCategoryTreeShow(a,c,b){getTree({targetNameId:a,targetValueId:c,dataType:"exam_category",showRoot:b?b:!1})}EXAM_LINE_COUNT=null;
function examModifyExamStatus(a,c,b){var e=$('table[_pagetabledataset="admin_exam_examCtl::displayExamList"]'),d=window.L.getText("\u8003\u8bd5");void 0==e.get(0)&&(e=$('table[_pagetabledataset="admin_exam_exerciseCtl::displayExerciseList"]'),d=window.L.getText("\u7ec3\u4e60"));var b=b?b:"",h=0,g={exam_id:{},conditions:{},target_status:c},f="success",i="";if("selected"==a){var j=!1;$(":checkbox[name='exam_cb']:checked").each(function(a){h++;g.exam_id[a]=$(this).val();j=true});j||(f="failed",i=window.L.getText(window.L.getText("\u8bf7\u81f3\u5c11\u9009\u4e2d\u4e00\u6761"))+
d);b=window.L.getText("\u8fd9")+h+window.L.getText("\u6761")+d}else g.exam_id[0]=a,b="&nbsp;"+b+"&nbsp;";if("success"==f){a=window.L.getText("\u786e\u8ba4\u5220\u9664")+b+"\uff1f";f=window.L.getText("\u5220\u9664")+d;switch(c){case "030302":a=window.L.getText("\u786e\u8ba4\u7981\u7528")+b+"\uff1f";f=window.L.getText("\u7981\u7528")+d;break;case "030301":a=window.L.getText("\u786e\u8ba4\u53ef\u7528")+b+"\uff1f",f=window.L.getText("\u53ef\u7528")+d}oDialogDiv(f,"text:<div>"+a+"</div>","400px","auto",
[2,function(a){if(a){var a=window.L._adminUrl+"/exam/examCtl.php?a=modifyExamStatus",b="modify_info="+encodeURIComponent(L.JSON.stringify(g));$.ajax({type:"POST",async:false,url:a,data:b,dataType:"json",success:function(a){if(a.res=="success"){a=d+window.L.getText("\u5220\u9664\u6210\u529f");switch(c){case "030302":a=d+window.L.getText("\u7981\u7528\u6210\u529f");break;case "030301":a=d+window.L.getText("\u53ef\u7528\u6210\u529f")}oDialogDivInfo(a);var a=L.extension.pageTable.classObj,b=e.get(0);
a.params(b,null,true)}else oDialogDivInfo(a.info)},error:function(){}})}}])}else oDialogDivInfo(i)}
function examAddInvite(a){var c={inviteContent:{content_id:{},contentType:1}},b="success",e="";if("selected"==a){var d=!1;$(":checkbox[name='exam_cb']:checked").each(function(a){c.inviteContent.content_id[a]=$(this).val();d=!0});d||(b="failed",e=window.L.getText("\u8bf7\u81f3\u5c11\u9009\u4e2d\u4e00\u4e2a\u8003\u8bd5"))}else c.inviteContent.content_id[0]=a;"success"==b?inviteAlertAddInvite(c):oDialogDivInfo(e)};
