EXAM_RESET_AREA_MARK="";
function examInitEditPage(){EXAM_RESET_AREA_MARK=""==EXAM_RESET_AREA_MARK?initResetArea({selection:"#exam_info_div"}):EXAM_RESET_AREA_MARK;window.L.openCom("oEditor")&&(new oEditor({buttonList:"bold italic underline left center right justify ol ul fontSize fontFamily fontFormat image forecolor bgcolor table subscript superscript strikethrough removeformat hr media".split(" "),maxHeight:300,CustomConfig:{AnswerSelect:{AnswerType:"textbox"},oFileManager:{quickUploadDir:{img:img_quick_upload_dir,media:media_quick_upload_dir,
attachment:attachment_quick_upload_dir},browseDir:{img:img_browse_upload_dir,media:media_browse_upload_dir,attachment:attachment_browse_upload_dir}}}})).panelInstance("exam_notice");window.L.openCom("upload")("frontCoverImgUpload",{onComplete:function(a){$("#frontCoverImg").attr({src:window.L._rootUrl+"/include/oFileManager/fileExtension.php?fileUrl="+a,fileUrl:a});document.getElementById("frontCoverImgProgress").childNodes[1].nodeValue=window.L.getText("\u4e0a\u4f20\u5c01\u9762\u56fe\u7247")},onProgress:function(a){document.getElementById("frontCoverImgProgress").childNodes[1].nodeValue=
a.percentage+"%"}},"gif;jpg;bmp;png"," ",65,18,{auto:!0,queueID:"  ",multi:!1,folder:"/frontCover"});window.L.openCom("wDate",{obj:$("#exam_begin_tm").get(0),params:{readOnly:!0,dateFmt:"yyyy-MM-dd HH:mm:ss"}});window.L.openCom("wDate",{obj:$("#exam_user_signup_end").get(0),params:{readOnly:!0,dateFmt:"yyyy-MM-dd HH:mm:ss"}});window.L.openCom("wDate",{obj:$("#exam_end_tm").get(0),params:{readOnly:!0,dateFmt:"yyyy-MM-dd HH:mm:ss"}});window.L.openCom("wDate",{obj:$("#exam_user_signup_time").get(0),
params:{readOnly:!0,dateFmt:"yyyy-MM-dd HH:mm:ss"}});void 0!=$("#exam_publish_result_tm").get(0)&&window.L.openCom("wDate",{obj:$("#exam_publish_result_tm").get(0),params:{readOnly:!0,dateFmt:"yyyy-MM-dd HH:mm:ss"}});var a;a=$("#allowIp > div");1===a.length&&""===$.trim(a.find("input:eq(0)").val())&&""===$.trim(a.find("input:eq(1)").val())?$("input[name=allowIpRadio][value=0]").click():$("input[name=allowIpRadio][value=1]").click();examChangeTotalTmMode();examChangeTimesMode();examChangeExamManualMode();
examChangePointType();examChangeExamTarget();loadFunctionBar();examChangeExamQsnLimitTime();examChangeSignupflg()}function examResetArea(){resetArea(EXAM_RESET_AREA_MARK)}function examChangeTotalTmMode(){"0"==$("#exam_total_tm_mode").val()?$("#exam_total_tm_lb").hide():$("#exam_total_tm_lb").show()}
function examChangeSignupflg(){$("#exam_user_signup_flg").attr("checked")?($("#exam_user_auto_verify_flg").parent("label").show(),$("#exam_user_signup_time").parent("span").show()):($("#exam_user_auto_verify_flg").parent("label").hide(),$("#exam_user_signup_time").parent("span").hide())}function examChangeTimesMode(){"0"==$("#exam_times_mode").val()?$("#exam_times_lb").hide():$("#exam_times_lb").show()}
function examChangePublishResultTmMode(){"checked"!=$("#exam_publish_result_tm_mode").attr("checked")?$("#exam_publish_result_tm_lb").hide():$("#exam_publish_result_tm_lb").show()}
function examChangeExamManualMode(){"checked"!=$("#exam_manual").attr("checked")?($("#exam_manual_lb").hide(),$("#exam_publish_result_tm_mode").removeAttr("disabled"),$("#exam_publish_result_tm_lb").removeAttr("disabled")):($("#exam_manual_lb").show(),$("#exam_submit_display_result").removeAttr("checked","checked"),$("#exam_publish_result_tm_mode").removeAttr("checked","checked"),$("#exam_publish_result_tm_mode").attr("disabled","disabled"),$("#exam_publish_result_tm_lb").attr("checked","checked"),
$("#exam_publish_result_tm_lb").attr("disabled","disabled"))}function examChangePointType(){"030203"==$("#exam_point_type").val()?$("#exam_point_lb").show():$("#exam_point_lb").hide()}
function examPublishType(a){"lb"===a?$("#exam_submit_display_result").removeAttr("checked","checked"):(a="type",window.L.openCom("oDialogDiv")(window.L.getText("\u662f\u5426\u7acb\u5373\u663e\u793a\u6210\u7ee9"),"text:","auto","auto",[2,function(a){a?$("#exam_submit_display_result").attr("checked","checked"):$("#exam_submit_display_result").removeAttr("checked","checked")}]),$("#exam_publish_result_tm").val(""))}
function examAddManual(a,b){void 0==$("#exam_manual_"+a).val()&&$("#exam_manual_list_lb").append('<label id="exam_manual_'+a+'_lb"><input type="hidden" name="exam_manual_list" id="exam_manual_'+a+'" value="'+a+'"/>'+b+'<a class="icon_del" title="\u5220\u9664" a href="javascript:void(0)" onclick="examDelManual(\''+a+'\')""></a></label>')}function examDelManual(a){$("#exam_manual_"+a+"_lb").remove()}
function examAdminTreeShow(a,b,c){getTree({targetId:a,dataType:"admin",showRoot:c?c:!1,callbackFn:b})}function examCategoryTreeShow(a,b,c){getTree({targetNameId:a,targetValueId:b,dataType:"exam_category",showRoot:c?c:!1})}function examAlertAddPaper(){var a={};$("input[name='exam_papr_id']").each(function(b){a[b]=$(this).val()});Paper.selectPaper(examAddPaper,a)}
function examDelPaper(a){"selected"==a?$("input[name='exam_papr_id']:checked").each(function(){$("#exam_papr_tr_"+$(this).val()).remove()}):$("#exam_papr_tr_"+a).remove()}
function examAddPaper(a){var b=window.L._adminUrl+"/exam/examCtl.php?a=getAddExamPaper",c="papr_id="+encodeURIComponent(L.JSON.stringify(a.ids));if("030201"==$("#exam_point_type").val()){var d="-1";$("input[name='exam_papr_point']").each(function(){if("-1"!=d&&$(this).val()!=d)return window.L.openCom("tip")(window.L.getText("\u591a\u5f20\u8bd5\u5377\u603b\u5206\u4e0d\u76f8\u540c"),2E3,!1),!1;d=$(this).val()});for(var f="-1",e=0;e<a.length;e++){if("-1"!=d&&a.paprPoints[e]!=d||"-1"!=f&&a.paprPoints[e]!=
d)return window.L.openCom("tip")(window.L.getText("\u591a\u5f20\u8bd5\u5377\u603b\u5206\u4e0d\u76f8\u540c"),2E3,!1),!1;f=a.paprPoints[e]}}$.ajax({type:"POST",async:!1,url:b,data:c,dataType:"html",success:function(a){$("#exam_paprs_tbody").append(a)},error:function(){}})}function examGroupTreeShow(a){getTree({isCheckBox:!0,targetId:"exam_group_a",dataType:"group",showRoot:a?a:!1,callbackFn:examAddGroup})}
function examChangeExamTarget(){"exam_all_person"==$("input[name='exam_target']:checked").val()?($("#exam_group_div").hide(),$("#exam_user_div").hide(),$("#exam_group_user_lb").hide()):($("#exam_group_div").show(),$("#exam_user_div").show(),$("#exam_group_user_lb").show())}function examDelGroup(a){"selected"==a?$("input[name='exam_group_id']:checked").each(function(){$("#exam_group_tr_"+$(this).val()).remove()}):$("#exam_group_tr_"+a).remove()}
function examAddGroup(a){var b=[],c=[];if(void 0!==a[0]&&($("input[name='exam_group_id']").each(function(a){c[a]=$(this).val()}),$.each(a,function(d){-1==$.inArray(a[d].id,c)&&(b+=a[d].id+",")}),0<b.length)){var d=window.L._adminUrl+"/exam/examCtl.php?a=getAddExamGroup",f="gids="+b.substring(0,b.length-1);$.ajax({type:"POST",async:!1,url:d,data:f,dataType:"text",success:function(a){$("#exam_group_tbody").append(a);loadFunctionBar()},error:function(){}})}}
function examAlertAddUser(){user(examAddUser)}function examAlertExcludeUser(){user(examExcludeUser)}
function examAddUser(a){var b={},c;for(c in a){var d=!1;$("input[name='exam_user_id']").each(function(){$(this).val()==a[c].id&&(d=!0)});d||(b[c]=a[c].id)}var f=window.L._adminUrl+"/exam/examCtl.php?a=getAddExamUser",b="user_id="+encodeURIComponent(L.JSON.stringify(b));$.ajax({type:"POST",async:!1,url:f,data:b,dataType:"html",success:function(a){$("#exam_user_tbody").append(a);loadFunctionBar()},error:function(){}})}
function examExcludeUser(a){var b={},c;for(c in a){var d=!1;$("input[name='exam_exclude_user_id']").each(function(){$(this).val()==a[c].id&&(d=!0)});d||(b[c]=a[c].id)}var f=window.L._adminUrl+"/exam/examCtl.php?a=getExcludeExamUser",b="user_id="+encodeURIComponent(L.JSON.stringify(b));$.ajax({type:"POST",async:!1,url:f,data:b,dataType:"html",success:function(a){$("#exam_exclude_user_tbody").append(a)},error:function(){}})}
function examDelUser(a){"selected"==a?$("input[name='exam_user_id']:checked").each(function(){$("#exam_user_tr_"+$(this).val()).remove()}):$("#exam_user_tr_"+a).remove()}function examDelExcludeUser(a){"selected"==a?$("input[name='exam_exclude_user_id']:checked").each(function(){$("#exam_exclude_user_tr_"+$(this).val()).remove()}):$("#exam_exclude_user_tr_"+a).remove()}
function examValidateExamInfo(){var a={res:"success",info:""};""==$("#exam_name").val()&&(a.res="failed",a.info=window.L.getText("\u8bf7\u586b\u5199\u8003\u8bd5\u540d\u79f0"));""==$("#exam_category").val()&&(a.res="failed",a.info=window.L.getText("\u8bf7\u9009\u62e9\u8003\u8bd5\u5206\u7c7b"));""==$("#exam_begin_tm").val()&&(a.res="failed",a.info=window.L.getText("\u8bf7\u9009\u62e9\u8003\u8bd5\u8d77\u59cb\u65f6\u95f4"));""==$("#exam_end_tm").val()&&(a.res="failed",a.info=window.L.getText("\u8bf7\u9009\u62e9\u8003\u8bd5\u7ed3\u675f\u65f6\u95f4"));
$("#exam_end_tm").val()<=$("#exam_begin_tm").val()&&(a.res="failed",a.info=window.L.getText("\u8bf7\u9009\u62e9\u8003\u8bd5\u7ed3\u675f\u65f6\u95f4\u5fc5\u987b\u5927\u4e8e\u8d77\u59cb\u65f6\u95f4"));"checked"==$("#exam_user_signup_flg").attr("checked")&&(""!=$("#exam_user_signup_time").val()&&$("#exam_user_signup_time").val()>$("#exam_begin_tm").val())&&(a.res="failed",a.info=window.L.getText("\u62a5\u540d\u5f00\u59cb\u65f6\u95f4\u5fc5\u987b\u5c0f\u4e8e\u8003\u8bd5\u5f00\u59cb\u65f6\u95f4"));"checked"==
$("#exam_user_signup_flg").attr("checked")&&(""!=$("#exam_user_signup_end").val()&&$("#exam_user_signup_end").val()>$("#exam_begin_tm").val())&&(a.res="failed",a.info=window.L.getText("\u62a5\u540d\u7ed3\u675f\u65f6\u95f4\u5fc5\u987b\u5c0f\u4e8e\u8003\u8bd5\u5f00\u59cb\u65f6\u95f4"));"checked"==$("#exam_user_signup_flg").attr("checked")&&(""!=$("#exam_user_signup_time").val()&&$("#exam_user_signup_end").val()<=$("#exam_user_signup_time").val())&&(a.res="failed",a.info=window.L.getText("\u8bf7\u9009\u62e9\u62a5\u540d\u7ed3\u675f\u65f6\u95f4\u5fc5\u987b\u5927\u4e8e\u8d77\u59cb\u65f6\u95f4"));
"checked"==$("#exam_user_signup_flg").attr("checked")&&(""!=$("#exam_user_signup_end").val()&&""==$("#exam_user_signup_time").val())&&(a.res="failed",a.info=window.L.getText("\u8bf7\u9009\u62e9\u62a5\u540d\u8d77\u59cb\u65f6\u95f4"));"1"==$("#exam_times_mode").val()&&!validPositiveInt($("#exam_times").val())&&(a.res="failed",a.info=window.L.getText("\u9650\u5236\u6bcf\u4eba\u6700\u591a\u53c2\u52a0\u6b21\u6570\u5fc5\u987b\u4e3a\u6b63\u6574\u6570"));"030203"==$("#exam_point_type").val()&&!validPositive($("#exam_point").val())&&
(a.res="failed",a.info=window.L.getText("\u6298\u7b97\u8bd5\u5377\u5206\u6570\u5fc5\u987b\u4e3a\u6b63\u6570"));validPositive($("#exam_passing_grade").val())||(a.res="failed",a.info=window.L.getText("\u53ca\u683c\u5206\u6570\u5fc5\u987b\u4e3a\u6b63\u6570"));void 0!=$("#exam_disable_minute").val()&&(""!=$("#exam_disable_minute").val()&&!validPositiveInt($("#exam_disable_minute").val()))&&(a.res="failed",a.info=window.L.getText("\u8d85\u65f6\u7981\u6b62\u5b66\u751f\u53c2\u52a0\u7684\u65f6\u95f4\u5fc5\u987b\u4e3a\u4e00\u4e2a\u6b63\u6574\u6570"));
void 0!=$("#exam_disable_submit").val()&&(""!=$("#exam_disable_submit").val()&&!validPositiveInt($("#exam_disable_submit").val()))&&(a.res="failed",a.info=window.L.getText("\u7981\u6b62\u5b66\u751f\u4ea4\u5377\u7684\u65f6\u95f4\u5fc5\u987b\u4e3a\u4e00\u4e2a\u6b63\u6574\u6570"));"checked"==$("#exam_manual").attr("checked")&&void 0==$("input[name='exam_manual_list']").val()&&(a.res="failed",a.info=window.L.getText("\u8bf7\u9009\u62e9\u4e00\u4e2a\u8bc4\u5377\u4eba"));void 0==$("input[name='exam_papr_id']").val()&&
(a.res="failed",a.info=window.L.getText("\u8bf7\u9009\u62e9\u4e00\u5f20\u8bd5\u5377"));"checked"==$("#exam_publish_result_tm_lb").attr("checked")&&""===$("#exam_publish_result_tm").val()&&(a.res="failed",a.info=window.L.getText("\u8bf7\u586b\u5199\u53d1\u5e03\u65f6\u95f4"));"checked"==$("#exam_publish_result_tm_lb").attr("checked")&&$("#exam_publish_result_tm").val()<=$("#exam_begin_tm").val()&&(a.res="failed",a.info=window.L.getText("\u6210\u7ee9\u53d1\u5e03\u53d1\u5e03\u65f6\u95f4\u5fc5\u987b\u5927\u4e8e\u7b49\u4e8e\u8003\u8bd5\u5f00\u59cb\u65f6\u95f4"));
"checked"!==$("#exam_publish_result_tm_lb").attr("checked")&&("checked"!==$("#exam_publish_result_tm_mode").attr("checked")&&"1"!==$("#exam_type").val())&&(a.res="failed",a.info=window.L.getText("\u8bf7\u9009\u62e9\u7acb\u5373\u53d1\u5e03\u6216\u6307\u5b9a\u65f6\u95f4\u53d1\u5e03"));if("030201"==$("#exam_point_type").val()){var b="-1";$("input[name='exam_papr_point']").each(function(){if(b!="-1"&&$(this).val()!=b){a.res="failed";a.info=window.L.getText("\u591a\u5f20\u8bd5\u5377\u5206\u6570\u4e0d\u540c")}b=
$(this).val()})}"checked"==$("#exam_group_user").attr("checked")&&(void 0==$("input[name='exam_group_id']").val()&&void 0==$("input[name='exam_user_id']").val())&&(a.res="failed",a.info=window.L.getText("\u8bf7\u9009\u62e9\u4e00\u4e2a\u7ec4\u6216\u7528\u6237"));return a}
function examAddOrUpdateExam(){oDialogDivInfo(window.L.getText("\u64cd\u4f5c\u4e2d..."),3E5);disableBtn("exam_save_btn");var a=examValidateExamInfo(),b="1"==$("#exam_type").val()?"\u7ec3\u4e60":"\u8003\u8bd5";if("success"==a.res){var c=examFormatExamInfo(),a=window.L._adminUrl+"/exam/examCtl.php?a=modifyExam",c="exam_info="+encodeURIComponent(L.JSON.stringify(c));$.ajax({type:"POST",async:!1,url:a,data:c,dataType:"json",success:function(a){if("success"==a.res){var c={};$("input[name='exam_tags']").each(function(a){c[a]=
$(this).val()});a={objId:a.info,tagIds:c,addOrReplace:"replace"};void 0!=c[0]&&tagAddTagObj(a);""==$("#exam_id").val()?(oDialogDivInfo(window.L.getText("\u6dfb\u52a0"+b+"\u6210\u529f")),examResetArea(),examInitEditPage()):oDialogDivInfo(window.L.getText("\u4fee\u6539"+b+"\u6210\u529f"))}else oDialogDivInfo(a.info);enableBtn("exam_save_btn")},error:function(){oDialogDivInfo(window.L.getText("\u7f51\u7edc\u8fde\u63a5\u51fa\u9519,\u8bf7\u7a0d\u540e\u518d\u8bd5"));enableBtn("exam_save_btn")}})}else oDialogDivInfo(a.info),
enableBtn("exam_save_btn")}function examDelCoverImg(){""!=$("#frontCoverImg").attr("fileUrl")&&window.L.openCom("oDialogDiv")(window.L.getText("\u786e\u5b9a\u8981\u5220\u9664\u5c01\u9762\u5417?"),"","auto","auto",[2,function(a){a&&($("#frontCoverImg").get(0).src=window.L._rootUrl+"/include/oFileManager/fileExtension.php?fileUrl=/images/icon/icon_thumb_default1.png",$("#frontCoverImg").get(0).setAttribute("fileUrl",""))}])}
function examFormatExamInfo(){return{exam_id:$("#exam_id").val(),exam_name:$.trim($("#exam_name").val()),exam_type:$.trim($("#exam_type").val()),exam_notice:$("#exam_notice").val(),exam_status:$("#exam_status").val(),exam_category:$("#exam_category").val(),exam_total_tm:"0"==$("#exam_total_tm_mode").val()?"":$("#exam_total_tm").val(),exam_begin_tm:$("#exam_begin_tm").val(),exam_end_tm:$("#exam_end_tm").val(),exam_mode:$("#exam_mode").val(),exam_times:"0"==$("#exam_times_mode").val()?"0":$("#exam_times").val(),
exam_point_type:$("#exam_point_type").val(),exam_point:examGetExamPoint(),exam_passing_grade:$("#exam_passing_grade").val(),exam_manual:"checked"==$("#exam_manual").attr("checked")?"1":"0",exam_all_person:"checked"==$("#exam_all_person").attr("checked")?"1":"0",exam_group_person:"checked"==$("#exam_group_user").attr("checked")&&void 0!=$("input[name='exam_group_id']").val()?"1":"0",exam_spec_person:"checked"==$("#exam_group_user").attr("checked")&&void 0!=$("input[name='exam_user_id']").val()?"1":
"0",exam_publish_result_tm:"checked"==$("#exam_publish_result_tm_lb").attr("checked")?$("#exam_publish_result_tm").val():"",exam_allow_ip:examGetAllowIpStr(),exam_cloze_flg:"checked"==$("#exam_cloze_flg").attr("checked")?"1":"0",exam_time_consistency_flg:"checked"==$("#exam_time_consistency_flg").attr("checked")?"1":"0",exam_publish_answer_flg:"checked"==$("#exam_publish_answer_flg").attr("checked")?"1":"0",exam_publish_result_flg:"checked"==$("#exam_publish_result_flg").attr("checked")?"1":"0",exam_blank_flg:"checked"==
$("#exam_blank_flg").attr("checked")?"1":"0",exam_full_screen_flg:"checked"==$("#exam_full_screen_flg").attr("checked")?"1":"0",exam_mouse_right_flg:"checked"==$("#exam_mouse_right_flg").attr("checked")?"1":"0",exam_disable_paste_flg:"checked"==$("#exam_mouse_right_flg").attr("checked")?"1":"0",exam_submit_display_result:"checked"==$("#exam_submit_display_result").attr("checked")?"1":"0",exam_ie_only_flg:"checked"==$("#exam_ie_only_flg").attr("checked")?"1":"0",exam_paper_only_one_flg:"checked"==
$("#exam_paper_only_one_flg").attr("checked")?"1":"0",exam_passing_again_flg:"checked"==$("#exam_passing_again_flg").attr("checked")?"1":"0",exam_qsn_random_flg:"checked"==$("#exam_qsn_random_flg").attr("checked")?"1":"0",exam_disable_monitor_flg:"checked"==$("#exam_disable_monitor_flg").attr("checked")?"0":"1",exam_recovery_flg:"checked"==$("#exam_recovery_flg").attr("checked")?"1":"0",exam_user_verify_flg:"checked"==$("#exam_user_verify_flg").attr("checked")?"1":"0",exam_user_signup_flg:"checked"==
$("#exam_user_signup_flg").attr("checked")?"1":"0",exam_user_signup_end:"checked"==$("#exam_user_signup_flg").attr("checked")?$("#exam_user_signup_end").val():"",exam_user_signup_time:"checked"==$("#exam_user_signup_flg").attr("checked")?$("#exam_user_signup_time").val():"",exam_user_auto_verify_flg:"checked"==$("#exam_user_signup_flg").attr("checked")&&"checked"==$("#exam_user_auto_verify_flg").attr("checked")?"1":"0",exam_disable_minute:""==$.trim($("#exam_disable_minute").val())?"0":$.trim($("#exam_disable_minute").val()),
exam_disable_submit:""==$.trim($("#exam_disable_submit").val())?"0":$.trim($("#exam_disable_submit").val()),exam_marker:examGetExamMarker(),exam_papr:examGetExamPapr(),exam_user:examGetExamUser(),exam_group:examGetExamGroup(),exam_exclude_user:examGetExamExcludeUser(),exam_credit:void 0==$("#exam_credit").val()?0:parseInt($("#exam_credit").val()),cover_img:$("#frontCoverImg").attr("fileUrl")}}
function examGetExamPoint(){var a=0;switch($("#exam_point_type").val()){case "030201":a=$("input[name='exam_papr_point']").val();break;case "030203":a=$("#exam_point").val()}return a}
function examGetAllowIpStr(){if($("input[name=allowIpRadio][value=0]").prop("checked"))return"";var a=[];$("#allowIp > div").each(function(){var b=$("input",this),c=$.trim(b.eq(0).val()),d=$.trim(b.eq(1).val());if(!(""===c&&""===d)){if(examObj.inputIpBlurCheckFun(b.get(0))&&examObj.inputIpBlurCheckFun(b.get(1))){""===c?c="0.0.0.0":""===d&&(d="255.255.255.255");for(var b=c.split("."),f=d.split("."),e=0;4>e;++e)if(b[e]>f[e]){b=c;c=d;d=b;break}else if(b[e]<f[e])break}else return a=!1;a[a.length]=c+"-"+
d}});return a?a.join(","):""}function examGetExamMarker(){var a={};"checked"==$("#exam_manual").attr("checked")&&$("input[name='exam_manual_list']").each(function(b){a[b]={user_id:$(this).val()}});return a}function examGetExamPapr(){var a={};$("input[name='exam_papr_id']").each(function(b){a[b]={papr_id:$(this).val()}});return a}
function examGetExamUser(){var a={};"checked"==$("#exam_group_user").attr("checked")&&$("input[name='exam_user_id']").each(function(b){a[b]={user_id:$(this).val()}});return a}function examGetExamGroup(){var a={};"checked"==$("#exam_group_user").attr("checked")&&$("input[name='exam_group_id']").each(function(b){a[b]={group_id:$(this).val(),is_include_sub:"checked"==$("#exam_is_include_sub_"+$(this).val()).attr("checked")?"1":"0"}});return a}
function examGetExamExcludeUser(){var a={};$("input[name='exam_exclude_user_id']").each(function(b){a[b]={user_id:$(this).val()}});return a}
function examAllowIpShow(){var a=(new Date).getTime();$("#allow_ip_td").append('<div id="allow_ip_div_'+a+'"><input type="hidden" name="allow_ip_mark" id="allow_ip_mark_'+a+'" value="'+a+'"/><input type="text" value="" id="exam_allow_ip_start_'+a+'" name="exam_allow_ip_start" class="input3 ~auto_width">-<input type="text" value="" id="exam_allow_ip_end_'+a+'" name="exam_allow_ip_end" class="input3 ~auto_width"><a href="javascript:void(0)" class="icon_del" onclick="examDelAllowIp(\''+a+"')\"></a></div>")}
function examDelAllowIp(a){$("#allow_ip_div_"+a).remove()}
function examChangeExamQsnLimitTime(){"checked"==$("#exam_ie_only_flg").attr("checked")?($("#exam_qsn_random_flg").removeAttr("checked"),$("#exam_qsn_random_flg").attr("disabled","disabled"),$("#exam_recovery_flg").attr("checked","checked"),$("#exam_recovery_flg").attr("disabled","disabled"),$("#exam_mode").val("030102"),$("#exam_mode").attr("disabled","disabled")):($("#exam_qsn_random_flg").removeAttr("disabled"),$("#exam_recovery_flg").removeAttr("disabled"),$("#exam_mode").removeAttr("disabled"))}
function examDisplayTag(){tagDisplayTag({tagType:"3",callbackFn:"examAddTag",targetId:"exam_add_tag_a"})}function examAddTag(a,b){if(void 0==$("#exam_tag_"+a).val()){var c='<span class="icon_link" id="exam_tag_span_'+a+'"><input type="hidden" name="exam_tags" id="exam_tag_'+a+'" value="'+a+'"><a href="javascript:void(0)" >'+b+'</a><a class="icon_del" title="'+window.L.getText("\u5220\u9664")+'" href="javascript:void(0)" onclick="examDelTag(\''+a+"')\"></a></span>";$("#exam_tag_td").append(c)}}
function examDelTag(a){$("#exam_tag_span_"+a).remove()}function examDelAllTag(){$("#exam_tag_td").html("")}
var examObj={allowIpRadioClickFun:function(a){"0"===a.value?$(document.getElementById("allowIp").parentNode).hide():$(document.getElementById("allowIp").parentNode).show()},inputIpBlurCheckFun:function(a){if(/^(?:(?:1?\d{1,2}|2[0-4]\d|25[0-5])\.){3}(?:1?\d{1,2}|2[0-4]\d|25[0-5])$/.test(a.value)||""===$.trim(a.value))return!0;window.L.openCom("tip")(window.L.getText("IP\u5730\u5740\u65e0\u6548,\u8bf7\u786e\u8ba4"));window.setTimeout(function(){a.focus();a.select()},0);return!1},addIpClickFun:function(a){var b=
!0;$("#allowIp > div").each(function(){if(""===$.trim($("input:eq(0)",this).val())&&""===$.trim($("input:eq(1)",this).val()))return $("input:eq(0)",this).focus(),b=!1});b&&$(a.parentNode).clone().appendTo(a.parentNode.parentNode).find("input").val("")},delIpClickFun:function(a){1<$("> div",a.parentNode.parentNode).length?$(a.parentNode).remove():($("input",a.parentNode).val(""),$("input[name=allowIpRadio][value=0]").click())}};
